backend:
  - pyproject.toml
  - poetry.lock
  - rasa/**/*
  - tests/**/*
  - data/**/*
  - examples/**/*
  - Makefile
  - .github/workflows/continous-integration.yml
  - .github/workflows/security-scans.yml

providers:
  - rasa/shared/providers/**

dm1-tensorflow-files:
  - data/project_templates/nlu_based/**
  - rasa/core/featurizers/**
  - rasa/core/policies/ensemble.py
  - rasa/core/policies/memoization.py
  - rasa/core/policies/rule_policy.py
  - rasa/core/policies/ted_policy.py
  - rasa/core/policies/unexpected_intent_policy.py
  - rasa/core/training/**
  - rasa/graph_components/converters/**
  - rasa/graph_components/providers/domain_for_core_training_provider.py
  - rasa/graph_components/providers/forms_provider.py
  - rasa/graph_components/providers/rule_only_provider.py
  - rasa/graph_components/providers/story_graph_provider.py
  - rasa/nlu/classifiers/diet_classifier.py
  - rasa/nlu/classifiers/fallback_classifier.py
  - rasa/nlu/classifiers/keyword_intent_classifier.py
  - rasa/nlu/classifiers/mitie_intent_classifier.py
  - rasa/nlu/classifiers/regex_message_handler.py
  - rasa/nlu/classifiers/sklearn_intent_classifier.py
  - rasa/nlu/emulators/**
  - rasa/nlu/extractors/entity_synonyms.py
  - rasa/nlu/extractors/mitie_entity_extractor.py
  - rasa/nlu/extractors/regex_entity_extractor.py
  - rasa/nlu/extractors/spacy_entity_extractor.py
  - rasa/nlu/featurizers/dense_featurizer/convert_featurizer.py
  - rasa/nlu/featurizers/dense_featurizer/mitie_featurizer.py
  - rasa/nlu/featurizers/dense_featurizer/spacy_featurizer.py
  - rasa/nlu/selectors/**
  - rasa/nlu/tokenizers/jieba_tokenizer.py
  - rasa/nlu/tokenizers/mitie_tokenizer.py
  - rasa/nlu/tokenizers/spacy_tokenizer.py
  - rasa/nlu/utils/mitie_utils.py
  - rasa/shared/core/training_data/
  - rasa/shared/nlu/**
  - rasa/utils/tensorflow/**
  - rasa/utils/plotting.py
  - tests/core/featurizers/**
  - tests/core/policies/**
  - tests/nlu/**
  - tests/core/training/**
  - tests/graph_components/converters/**
  - tests/graph_components/providers/**
  - tests/shared/core/training_data/**
  - tests/shared/nlu/**
  - tests/utils/tensorflow/**
  - tests/utils/test_plotting.py

docker:
  - pyproject.toml
  - poetry.lock
  - rasa/**/*
  - docker/**/*
  - Dockerfile
  - .dockerignore
  - Makefile.docker
  - Makefile

lock_file:
  - poetry.lock

pii-management:
  - rasa/privacy/**
  - tests_deployment/integration_tests_pii_management_in_calm/**
  - tests/integration_tests/privacy/**

voice-files:
  - rasa/core/channels/voice_ready/**
  - rasa/core/channels/voice_stream/**
  - rasa/core/channels/channel.py
  - rasa/core/channels/socketio.py
  - rasa/core/channels/studio_chat.py
  - tests/core/channels/voice_ready/**
  - tests/core/channels/voice_stream/**
  - tests/core/test_channels.py
  - tests/core/channels/test_socketio.py
  - tests/core/channels/test_studio_chat.py
  - tests/integration_tests/core/channels/test_voice_primitives.py
  - tests/integration_tests/core/channels/test_websocket_channel.py
  - tests/integration_tests/core/channels/websocket_replay.py
  - tests/integration_tests/core/channels/twilio_media_stream_replay.py
  - tests/integration_tests/core/channels/test_twilio_media_stream_replay.py
  - .github/workflows/voice-e2e-ci.yml
  - .github/workflows/run-voice-channel-tests.yml


broker-files:
  - rasa/core/brokers/**
  - tests/core/test_brokers.py
  - tests_deployment/docker-compose.broker.yml
  - tests/integration_tests/core/brokers/**
  - tests_deployment/integration_tests_channel_and_broker/**

tracing-and-metrics-files: # files imported by tracing and metrics functionality are also added here
  - rasa/tracing/**
  - rasa/core/**
  - rasa/dialogue_understanding/generator/**
  - rasa/dialogue_understanding/processor/**
  - rasa/graph_components/**
  - rasa/agents/**
  - rasa/engine/**
  - rasa/shared/core/domain.py
  - tests/integration_tests/tracing/**
  - tests/integration_tests/test_telemetry.py
  - tests_deployment/integration_tests_metrics_setup/**
  - tests_deployment/integration_tests_tracing_deployment/**

sequential-integration-files: # files related to sequential integration feature.Only tests run here are from tests/integration_tests/core/test_tracker_store.py
  - rasa/core/tracker_stores/redis_tracker_store.py
  - rasa/core/tracker_stores/sql_tracker_store.py
  - rasa/core/tracker_stores/tracker_store.py
  - rasa/shared/core/trackers.py
  - rasa/shared/core/domain.py
  - rasa/shared/core/events.py
  - tests_deployment/integration_tests_tracker_stores/**
  - tests/core/tracker_stores/**
  - tests/core/test_lock_store.py
  - tests/integration_tests/core/tracker_stores/**
  - tests/integration_tests/core/test_tracker_store.py
  - tests/integration_tests/core/test_auth_retry_tracker_store.py
  - tests/shared/core/test_trackers.py

non-sequential-integration-files:
  - rasa/studio/**
  - rasa/shared/providers/_utils.py
  - rasa/shared/core/domain.py
  - rasa/shared/core/events.py
  - rasa/shared/core/trackers.py
  - rasa/e2e_tests/**
  - rasa/core/actions/**
  - rasa/core/agent.py
  - rasa/core/tracker_stores/**
  - rasa/core/processor.py
  - rasa/core/lock_store.py
  - rasa/core/agent.py
  - rasa/cli/e2e_test.py
  - rasa/cli/data.py
  - rasa/cli/telemetry.py
  - rasa/model_training.py
  - rasa/telemetry.py
  - rasa/hooks.py
  - rasa/plugin.py
  - rasa/core/channels/channel.py
  - rasa/shared/core/events.py
  - rasa/utils/licensing.py
  - rasa/core/secrets_manager/**
  - tests/studio/**
  - tests/e2e_tests/**
  - tests/core/actions/**
  - tests/core/test_agent.py
  - tests/core/tracker_stores/**
  - tests/core/test_processor.py
  - tests/core/test_agent.py
  - tests/cli/test_rasa_e2e_test.py
  - tests/cli/test_rasa_data.py
  - tests/test_telemetry.py
  - tests/test_model_training.py
  - tests/test_plugin.py
  - tests/shared/core/test_events.py
  - tests/utils/test_licensing.py
  - tests/core/secrets_manager/**
  - tests/integration_tests/test_licensing.py
  - tests/integration_tests/test_hooks.py
  - tests/integration_tests/test_model_training.py
  - tests/integration_tests/test_telemetry.py
  - tests/integration_tests/cli/**
  - tests/integration_tests/e2e_tests/**
  - tests/integration_tests/shared/**
  - tests/integration_tests/studio/**

enterprise-search-policy-files:
  - rasa/core/policies/enterprise_search_policy*
  - rasa/core/policies/policy.py
  - rasa/dialogue_understanding/**
  - rasa/engine/**
  - rasa/shared/core/policies/**
  - tests_deployment/integration_tests_enterprise_search/**
  - tests/integration_tests/enterprise_search/**

channel-connector-files:
  - rasa/core/channels/**
  - tests_deployment/integration_tests_channel_connectors/**
  - tests/integration_tests/core/channels/test_rest_channel.py
  - tests/integration_tests/core/channels/test_websocket_channel.py
  - tests/integration_tests/core/channels/test_jambonz_channel.py

mongo-db-files:
  - rasa/core/tracker_stores/mongo_tracker_store.py
  - rasa/core/tracker_stores/**
  - rasa/shared/core/trackers.py
  - rasa/shared/core/domain.py
  - tests/integration_tests/core/tracker_stores/test_mongo_tracker_store.py
  - tests_deployment/integration_tests_tracker_stores/mongo_db_tracker_store/**
  - tests/core/tracker_stores/test_mongo_tracker_store.py

dynamo-db-files:
  - rasa/core/tracker_stores/dynamo_tracker_store.py
  - rasa/core/tracker_stores/**
  - rasa/shared/core/trackers.py
  - rasa/shared/core/events.py
  - rasa/shared/core/domain.py
  - tests/integration_tests/core/tracker_stores/test_dynamo_tracker_store.py
  - tests_deployment/integration_tests_tracker_stores/dynamo_tracker_store/**
  - tests/core/tracker_stores/test_dynamo_tracker_store.py

poetry-dependency-updates:
  - pyproject.toml
  - poetry.lock

rasa-core-dependencies-files: # added an extra filters for rasa core dependencies
  - rasa/core/**
  - rasa/shared/core/**

concurrent-lockstore-files:
  - rasa/core/channels/**
  - rasa/core/concurrent_lock_store.py
  - rasa/core/lock_store.py
  - rasa/utils/endpoints.py
  - tests/integration_tests/core/concurrent_lock_stores/**

cli-files:
  - rasa/cli/**
  - rasa/shared/**
  - rasa/utils/**
  - tests/cli/**
  - tests/integration_tests/cli/**

agent-files:
  - rasa/dialogue_understanding/**
  - rasa/engine/**
  - rasa/cli/**/train.py
  - rasa/core/policies/flows/**
  - rasa/shared/core/**
  - rasa/shared/engine/**

sub-agent-files:
  - rasa/agents/**
  - rasa/shared/agents/**
  - rasa/shared/utils/mcp/**
  - tests/agents/**
  - tests/shared/agents/**
  - rasa/core/**/*agent*.py

nlu-files:
  - rasa/nlu/**
  - rasa/shared/nlu/**
  - tests/nlu/**
  - tests/shared/nlu/**

policy-files:
  - rasa/core/policies/**
  - rasa/shared/core/policies/**
  - tests/core/policies/**

custom-action-files:
  - rasa/core/actions/**
  - rasa/shared/core/**
  - rasa/shared/utils/**
  - tests_deployment/integration_tests_custom_action_server/**
  - tests/integration_tests/core/actions/**
  - tests/core/actions/**
  - tests/core/test_actions.py
  - tests/regressions/**

channel-files:
  - rasa/core/channels/**

builder-files:
  - rasa/builder/**
  - tests/builder/**

timer-store-files:
  - rasa/core/timer_managers/**
  - rasa/core/timer_stores/**
  - tests/core/test_timer_managers/**
  - tests/core/test_timer_stores/**
  - tests/core/timer_test_helpers.py
  - tests/integration_tests/core/timer_stores/**

sql-store-files:
  - rasa/core/tracker_stores/sql_tracker_store.py
  - rasa/core/iam_credentials_providers/aws_iam_credentials_provider.py
  - tests/integration_tests/core/tracker_stores/test_sql_tracker_store.py
  - tests/core/tracker_stores/test_sql_tracker_store.py
  - .github/workflows/helm-deploy.yml
