backend:
  - pyproject.toml
  - poetry.lock
  - rasa/**/*
  - tests/**/*
  - data/**/*
  - examples/**/*
  - Makefile
  - .github/workflows/continous-integration.yml
  - .github/workflows/security-scans.yml

providers:
  - rasa/shared/providers/**

dm1-tensorflow-files:
  - data/project_templates/nlu_based/**
  - rasa/core/featurizers/**
  - rasa/core/policies/ensemble.py
  - rasa/core/policies/memoization.py
  - rasa/core/policies/rule_policy.py
  - rasa/core/policies/ted_policy.py
  - rasa/core/policies/unexpected_intent_policy.py
  - rasa/core/training/**
  - rasa/graph_components/converters/**
  - rasa/graph_components/providers/domain_for_core_training_provider.py
  - rasa/graph_components/providers/forms_provider.py
  - rasa/graph_components/providers/rule_only_provider.py
  - rasa/graph_components/providers/story_graph_provider.py
  - rasa/nlu/classifiers/diet_classifier.py
  - rasa/nlu/classifiers/fallback_classifier.py
  - rasa/nlu/classifiers/keyword_intent_classifier.py
  - rasa/nlu/classifiers/mitie_intent_classifier.py
  - rasa/nlu/classifiers/regex_message_handler.py
  - rasa/nlu/classifiers/sklearn_intent_classifier.py
  - rasa/nlu/emulators/**
  - rasa/nlu/extractors/entity_synonyms.py
  - rasa/nlu/extractors/mitie_entity_extractor.py
  - rasa/nlu/extractors/regex_entity_extractor.py
  - rasa/nlu/extractors/spacy_entity_extractor.py
  - rasa/nlu/featurizers/dense_featurizer/convert_featurizer.py
  - rasa/nlu/featurizers/dense_featurizer/mitie_featurizer.py
  - rasa/nlu/featurizers/dense_featurizer/spacy_featurizer.py
  - rasa/nlu/selectors/**
  - rasa/nlu/tokenizers/jieba_tokenizer.py
  - rasa/nlu/tokenizers/mitie_tokenizer.py
  - rasa/nlu/tokenizers/spacy_tokenizer.py
  - rasa/nlu/utils/mitie_utils.py
  - rasa/shared/core/training_data/
  - rasa/shared/nlu/**
  - rasa/utils/tensorflow/**
  - rasa/utils/plotting.py

docker:
  - pyproject.toml
  - poetry.lock
  - rasa/**/*
  - docker/**/*
  - Makefile

lock_file:
  - poetry.lock

pii-management:
  - rasa/privacy/**
  - tests_deployment/integration_tests_pii_management_in_calm/**

voice-files:
  - rasa/core/channels/voice_ready/**
  - rasa/core/channels/voice_stream/**
  - rasa/core/channels/channel.py
  - rasa/core/channels/socketio.py
  - rasa/core/channels/studio_chat.py

broker-files:
  - rasa/core/brokers/**

tracing-and-metrics-files:
  - rasa/tracing/**
  - rasa/core/policies/**
  - rasa/dialogue_understanding/generator/**
  - rasa/engine/**
  - rasa/shared/core/domain.py
  - tests_deployment/integration_tests_metrics_setup/**

sequential-integration-files: # files related to sequential integration feature.Only tests run here are from tests/integration_tests/core/test_tracker_store.py
  - rasa/core/tracker_stores/redis_tracker_store.py
  - rasa/core/tracker_stores/sql_tracker_store.py
  - rasa/core/tracker_stores/tracker_store.py
  - rasa/shared/core/trackers.py
  - rasa/shared/core/domain.py
  - rasa/shared/core/events.py

non-sequential-integration-files:
  - rasa/studio/**
  - rasa/shared/providers/_utils.py
  - rasa/shared/core/domain.py
  - rasa/shared/core/events.py
  - rasa/shared/core/trackers.py
  - rasa/e2e_tests/**
  - rasa/core/actions/**
  - rasa/core/agent.py
  - rasa/core/tracker_stores/**
  - rasa/core/processor.py
  - rasa/core/lock_store.py
  - rasa/core/agent.py
  - rasa/cli/e2e_test.py
  - rasa/cli/data.py
  - rasa/cli/telemetry.py
  - rasa/model_training.py
  - rasa/telemetry.py
  - rasa/hooks.py
  - rasa/plugin.py
  - rasa/core/channels/channel.py
  - rasa/shared/core/events.py
  - rasa/utils/licensing.py
  - rasa/core/secrets_manager/**

enterprise-search-policy-files:
  - rasa/core/policies/enterprise_search_policy*
  - rasa/core/policies/policy.py
  - rasa/dialogue_understanding/**
  - rasa/engine/**
  - rasa/shared/core/policies/**
  - tests_deployment/integration_tests_enterprise_search/**

channel-connector-files:
  - rasa/core/brokers/**
  - rasa/core/channels/**
  - tests_deployment/integration_tests_channel_connectors/**

mongo-db-files:
  - rasa/core/tracker_stores/mongo_tracker_store.py
  - rasa/core/tracker_stores/**
  - rasa/shared/core/trackers.py
  - rasa/shared/core/domain.py

dynamo-db-files:
  - rasa/core/tracker_stores/dynamo_tracker_store.py
  - rasa/core/tracker_stores/**
  - rasa/shared/core/trackers.py
  - rasa/shared/core/events.py
  - rasa/shared/core/domain.py

poetry-dependency-updates:
  - pyproject.toml
  - poetry.lock

rasa-core-dependencies-files: # added an extra filters for rasa core dependencies
  - rasa/core/**
  - rasa/shared/core/**

concurrent-lockstore-files:
  - rasa/core/channels/**
  - rasa/core/concurrent_lock_store.py
  - rasa/core/lock_store.py
  - rasa/utils/endpoints.py

cli-files:
  - rasa/cli/**
  - rasa/shared/**
  - rasa/utils/**

agent-files:
  - rasa/agents/**
  - rasa/dialogue_understanding/**
  - rasa/engine/**
  - rasa/core/**/*agent*.py
  - rasa/cli/**/train.py
  - rasa/core/policies/flows/**
  - rasa/shared/agents/**
  - rasa/shared/core/**
  - rasa/shared/engine/**
  - rasa/shared/utils/mcp/**

nlu-files:
  - rasa/nlu/**
  - rasa/shared/nlu/**

policy-files:
  - rasa/core/policies/**
  - rasa/shared/core/policies/**

custom-action-files:
  - rasa/core/actions/**
  - rasa/shared/core/**
  - rasa/shared/utils/**
  - tests_deployment/integration_tests_custom_action_server/**

channel-files:
  - rasa/core/channels/**
