version: 2
updates:
  - package-ecosystem: pip
    # we enforce `increase` here because it ensures that we maintain a small range of
    # compatible versions; it speeds up installation with pip for our customers
    versioning-strategy: increase
    directory: "/"
    schedule:
      interval: weekly
      time: "02:00"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 20
    labels:
      - type:dependencies
      - release:main
    groups:
      engine-squad:
        dependency-type: production
        patterns:
          - "dask"
          - "numpy"
          - "scipy"
          - "litellm"
          - "openai"
          - "langchain"
          - "sklearn-crfsuite"
          - "scikit-learn"
          - "faiss-cpu"
          - "tiktoken"
          - "matplotlib"
          - "gliner"
          - "onnxruntime"
      atom-squad:
        dependency-type: production
        patterns:
          - "sanic"
          - "sanic-cors"
          - "sanic-jwt"
          - "sanic-routing"
          - "redis"
          - "ruamel.yaml"
          - "pyyaml"
          - "packaging"
          - "websockets"
          - "aiohttp"
          - "python-socketio"
          - "python-engineio"
          - "confluent-kafka"
          - "pypred"
          - "structlog"
          - "jinja2"
          - "jsonpatch"
          - "sqlalchemy"
          - "psycopg2-binary"
      cloud-and-channels:
        dependency-type: production
        patterns:
          - "boto3"
          - "google-cloud-storage"
          - "azure-storage-blob"
          - "fbmessenger"
          - "twilio"
          - "webexteamssdk"
          - "mattermostwrapper"
          - "rocketchat_API"
          - "aiogram"
          - "google-auth"
          - "slack-sdk"
          - "pymilvus"
          - "qdrant-client"
          - "azure-identity"
      static-analysis-tools:
        dependency-type: production
        patterns:
          - "ruff"
          - "mypy"
          - "types-protobuf"
          - "typing-extensions"
          - "typing-utils"
          - "protobuf"
          - "jsonschema"
          - "pep440-version-utils"
          - "presidio-analyzer"
          - "pykwalify"
          - "pydantic"
          - "towncrier"
      other-production-dependencies:
        dependency-type: production
        patterns:
          - "*"
      dev-dependencies:
        dependency-type: development
    ignore:
      - dependency-name: prompt-toolkit
        versions:
          - "> 2.0.10"
      - dependency-name: setuptools
        versions:
          - "> 70.0.0"
      - dependency-name: tensorflow # tensorflow version is pinned in pyproject.toml
        versions:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "01:00"
    groups:
      actions-deps:
        patterns:
          - "*"
        exclude-patterns:
        # internal git repo, not reachable for depenabot
          - "RasaHQ/get-release-records-from-datocms-gha"
          - "RasaHQ/push-release-record-to-datocms-gha"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 10
    reviewers:
      - RasaHQ/atom-squad
    labels:
      - type:dependencies
