version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 0
    labels:
      - type:dependencies
      - release:main
    ignore:
      - dependency-name: prompt-toolkit
        versions:
          - "> 2.0.10"
      - dependency-name: pytest-asyncio
        versions:
          - "> 0.10.0"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 0
    reviewers:
      - RasaHQ/infrastructure-squad
    labels:
      - type:dependencies
