name: Debug tracing test containers
description: Encapsulates steps for tracing test debugging

inputs:
  COMPOSE_FILE_PATH:
    description: 'tracing tests docker compose path'
    required: true

runs:
  using: 'composite'
  steps:
  - name: Check otel-collector container logs
    run: |
      docker compose -f ${{ inputs.COMPOSE_FILE_PATH }} logs otel-collector
    shell: bash
  
  - name: Check jaeger container logs
    run: |
      docker compose -f ${{ inputs.COMPOSE_FILE_PATH }} logs jaeger
    shell: bash
  
  - name: Check rasa-pro-jaeger container logs
    run: |
      docker compose -f ${{ inputs.COMPOSE_FILE_PATH }} logs rasa-pro-jaeger
    shell: bash
  
  - name: Check rasa-pro-otlp container logs
    run: |
      docker compose -f ${{ inputs.COMPOSE_FILE_PATH }} logs rasa-pro-otlp
    shell: bash

  - name: Check rasa-pro-jaeger-no-action-server container logs
    run: |
      docker compose -f ${{ inputs.COMPOSE_FILE_PATH }} logs rasa-pro-jaeger-no-action-server
    shell: bash

  - name: Check rasa-pro-otlp-no-action-server container logs
    run: |
      docker compose -f ${{ inputs.COMPOSE_FILE_PATH }} logs rasa-pro-otlp-no-action-server
    shell: bash

  - name: Check action-server-jaeger container logs
    run: |
      docker compose -f ${{ inputs.COMPOSE_FILE_PATH }} logs action-server-jaeger
    shell: bash

  - name: Check action-server-otlp container logs
    run: |
      docker compose -f ${{ inputs.COMPOSE_FILE_PATH }} logs action-server-otlp
    shell: bash