name: 'Deploy Rasa Pro Dev Helm Chart'
description: 'Installs dependencies, configures AWS, deploys with Pulumi, and comments deployment details on PR.'
inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.10'
  aws-region:
    description: 'AWS region'
    required: true
  aws-assume-role-session-token:
    description: 'AWS role to assume'
    required: true
  rasa-pro-helm-repo:
    description: 'Rasa Pro Helm repository'
    required: true
  rasa-pro-helm-version:
    description: 'Rasa Pro Helm chart version'
    required: true
  rasa-pro-version:
    description: 'Rasa Pro Docker image tag'
    required: true
  rasa-pro-dev-repository:
    description: 'Rasa Pro Dev Docker repository'
    required: true
  helm-deploy-rasa-pro-license:
    description: 'Rasa Pro license for Helm deploy'
    required: true
  helm-deploy-openai-api-key:
    description: 'OpenAI API key for Helm deploy'
    required: true
  helm-deploy-certificate-arn:
    description: 'Certificate ARN for Helm deploy'
    required: true
  helm-deploy-hosted-zone-id:
    description: 'Hosted zone ID for Helm deploy'
    required: true
  helm-deploy-pulumi-access-token:
    description: 'Pulumi access token for Helm deploy'
    required: true
  model-file-name:
    description: 'Model file name'
    required: true
  aws-model-s3-bucket:
    description: 'S3 bucket for model'
    required: true
  aws-model-s3-endpoint-url:
    description: 'S3 endpoint URL'
    required: true
  aws-model-s3-access-key-id:
    description: 'S3 access key ID'
    required: true
  aws-model-s3-secret-access-key:
    description: 'S3 secret access key'
    required: true
  stack-name:
    description: 'Pulumi stack name'
    required: true
  project-name:
    description: 'Project name'
    required: true
  pr-name:
    description: 'PR name'
    required: true
  domain-name:
    description: 'Domain name'
    required: true
  postgres-user:
    description: 'Postgres user (if using SQL tracker store)'
    required: false
  postgres-password:
    description: 'Postgres password (if using SQL tracker store)'
    required: false
  postgres-host:
    description: 'Postgres host (if using SQL tracker store)'
    required: false
  postgres-port:
    description: 'Postgres port (if using SQL tracker store)'
    required: false
  postgres-db:
    description: 'Postgres database name (if using SQL tracker store)'
    required: false

runs:
  using: "composite"
  steps:
    - name: Install Dependencies
      working-directory: ./infrastructure/eks-helm
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ inputs.aws-assume-role-session-token }}
        aws-region: ${{ inputs.aws-region }}

    - name: Set up kubeconfig
      env:
          AWS_REGION: ${{ inputs.aws-region }}
      shell: bash
      run: |
        aws eks update-kubeconfig --name rasa-pro-ci-cluster --region $AWS_REGION

    - name: Pulumi Up (Deploy)
      uses: pulumi/actions@v5
      with:
        command: up
        refresh: true
        stack-name: rasa/${{ inputs.stack-name }}
        work-dir: ./infrastructure/eks-helm
        upsert: true
      env:
        DOMAIN_NAME: ${{ inputs.domain-name }}
        PROJECT_NAME: ${{ inputs.project-name }}
        PR_NAME: ${{ inputs.pr-name }}
        RASA_PRO_HELM_REPO: ${{ inputs.rasa-pro-helm-repo }}
        RASA_PRO_HELM_VERSION: ${{ inputs.rasa-pro-helm-version }}
        RASA_PRO_VERSION: ${{ inputs.rasa-pro-version }}
        RASA_PRO_DEV_REPOSITORY: ${{ inputs.rasa-pro-dev-repository }}
        RASA_PRO_LICENSE: ${{ inputs.helm-deploy-rasa-pro-license }}
        OPENAI_API_KEY: ${{ inputs.helm-deploy-openai-api-key }}
        CERTIFICATE_ARN: ${{ inputs.helm-deploy-certificate-arn }}
        HOSTED_ZONE_ID: ${{ inputs.helm-deploy-hosted-zone-id }}
        PULUMI_ACCESS_TOKEN: ${{ inputs.helm-deploy-pulumi-access-token }}
        MODEL_FILE_NAME: ${{ inputs.model-file-name }}
        AWS_MODEL_S3_BUCKET: ${{ inputs.aws-model-s3-bucket }}
        AWS_MODEL_S3_ENDPOINT_URL: ${{ inputs.aws-model-s3-endpoint-url }}
        AWS_DEFAULT_REGION: ${{ inputs.aws-region }}
        AWS_MODEL_S3_ACCESS_KEY_ID: ${{ inputs.aws-model-s3-access-key-id }}
        AWS_MODEL_S3_SECRET_ACCESS_KEY: ${{ inputs.aws-model-s3-secret-access-key }}
        # POSTGRES_USER: ${{ inputs.postgres-user }}
        # POSTGRES_PASSWORD: ${{ inputs.postgres-password }}
        # POSTGRES_HOST: ${{ inputs.postgres-host }}
        # POSTGRES_PORT: ${{ inputs.postgres-port }}
        # POSTGRES_DB: ${{ inputs.postgres-db }}

#    - name: Add deployment details as comment
#      if: success()
#      uses: marocchino/sticky-pull-request-comment@v2
#      with:
#        header: deployment
#        recreate: true
#        message: |
#          🎉 PR Helm Deployment of Rasa Pro Dev passed!
#          🚀 Helm chart version: ${{ inputs.rasa-pro-helm-version }}
