# This is a sample .typo-ci.yml file, it's used to configure how Typo CI will behave.
# Add it to the root of your project and push it to github.
---

# What language dictionaries should it use? Currently Typo CI supports:
# de
# en
# en_GB
# es
# fr
# it
# pt
# pt_BR
dictionaries:
  - en

# # Any files/folders we should ignore?
excluded_files:
  - "*.py"
  - "*.css"
  - "*.scss"
  - "*.yml"
  - "*.yaml"
  - "*.html"
  - "*.json"
  - "*.lock"
  - "*.js"
  - "*.jsx"
  - "*.ts"
  - "*.tsx"
  - "*.md"
  - "CHANGELOG.md"
  - "CODE_OF_CONDUCT.md"
  - "CONTRIBUTING.md"
  - "Dockerfile"
  - "LICENSE.txt"
  - "Makefile"
  - "NOTICE"
  - "WORKFLOW_README.md"
  - "README.md"
  - "cloudbuild.yaml"
  - "pyproject.toml"
  - "secrets.tar.enc"
  - "setup.cfg"
  - ".codeclimate.yml"
  - ".coveragerc"
  - ".deepsource.toml"
  - ".dockerignore"
  - ".env"
  - ".git"
  - ".gitattributes"
  - ".gitignore"
  - ".pre-commit-config.yaml"
  - ".typo-ci.yml"
  - ".github/**/*"
  - "binder/**/*"
  - "data/**/*"
  - "docker/**/*"
  - "examples/**/*"
  - "rasa/**/*"
  - "scripts/**/*"
  - "tests/**/*"
  - "tests_deployment/integration_tests_tracing_deployment/**/*"
  - "CODEOWNERS"

# # Any typos we should ignore?
excluded_words:
  - CDD
  - Comerica
  - ConveRTFeaturizer
  - ConveRTTokenizer
  - HookimplMarker
  - Juste
  - NLG
  - README
  - Tanja
  - Vova
  - analytics
  - anonymization
  - anonymized
  - asyncio
  - backends
  - bot
  - bot's
  - cdd
  - cmdline
  - conftest
  - conveRT
  - crf
  - crfentityextractor
  - crfsuite
  - crypto
  - custom-nlg-service
  - customizable
  - daksh
  - dataset
  - db's
  - deduplicate
  - deduplication
  - deque
  - docusaurus
  - donath
  - dslim
  - entitysynonymmapper
  - extractor
  - fbmessenger
  - featurization
  - featurize
  - featurized
  - featurizer
  - featurizers
  - featurizes
  - featurizing
  - forni
  - gzip
  - gzipped
  - hallo
  - hftransformersnlp
  - hookimpl
  - initializer
  - instaclient
  - ish
  - jieba
  - jupyter
  - jupyterhub
  - jwt
  - jwt's
  - karpathy
  - keras
  - knowledgebase
  - knowledgebasebot
  - linenos
  - llm
  - luis
  - matmul
  - matplotlib
  - mattermost
  - memoization
  - memoizationpolicy
  - miniconda
  - mitie
  - mitie's
  - mitiefeaturizer
  - mitienlp
  - mongod
  - mrkdown
  - mrkdwn
  - myio
  - mymodelname
  - myuser
  - networkx
  - ngram
  - nlg
  - nlu
  - nlu's
  - non-latin
  - numpy
  - perceptron
  - pii-management
  - pika
  - pika's
  - pluggy
  - pre
  - pretrained
  - prototyper
  - prototyper
  - pycodestyle
  - pykwalify
  - pymessenger
  - pyobject
  - python-engineio
  - quickstart
  - rasa
  - rasa's
  - readthedocs
  - regexes
  - regexfeaturizer
  - regularizer
  - repo
  - rst
  - ruamel
  - rustc
  - rustup
  - rustup-init
  - sanic
  - sanitization
  - scipy
  - sklearn
  - socketio
  - spaCy
  - spaCy's
  - spacy
  - spacyfeaturizer
  - spacynlp
  - subsampled
  - testagent
  - thisismysecret
  - tokenization
  - tokenize
  - tokenized
  - tokenizer
  - tokenizers
  - tokenizing
  - typoci
  - unfeaturized
  - unschedule
  - venv
  - walkthroughs
  - webexteams
  - whitespaced
  - winpty
  - wsgi

spellcheck_filenames: false
