########################################################################################################################
# Dockerfile to build rasa container images
# Based on Ubuntu 18.04
########################################################################################################################
ARG DEPS_IMAGE_VER=latest
ARG IMAGE_SERVER=gitlab.devtechmo.pl:5000/

##################################################################################################################
### !!! CAUTION !!! Remember to increment DEPS_VER .gitlab-ci.yml upon modifying this section. !!! CAUTION !!! ###
##################################################################################################################
FROM ${IMAGE_SERVER}rasa-deps:${DEPS_IMAGE_VER} AS rasa-venv

MAINTAINER Bartłomiej Kuśmirek "<bartlomiej.kusmirek@techmo.pl>"

ADD ./requirements.txt /RASA/
ADD ./requirements-dev.txt /RASA/
ADD ./deps/create-venv.sh /RASA/deps/
ADD ./Makefile /RASA/
ADD ./alt_requirements/ /RASA/alt_requirements/
WORKDIR /RASA/

RUN /RASA/deps/create-venv.sh
