########################################################################################################################
# Dockerfile to build rasa container images
# Based on Ubuntu 18.04
########################################################################################################################
ARG DEPS_IMAGE_VER=latest
ARG IMAGE_SERVER=gitlab.devtechmo.pl:5000/

FROM ${IMAGE_SERVER}rasa-venv:${DEPS_IMAGE_VER} AS rasa-dev

MAINTAINER Bartłomiej Kuśmirek "<bartlomiej.kusmirek@techmo.pl>"


ADD ./ /RASA/
WORKDIR /RASA/

RUN ./install-rasa.sh
