# If makefile_vars is not included, include it.
# It is a good practice to check if common variables are included across all makefiles.
ifndef MAKEFILE_VAR
include ./makefile_vars
endif

DOCKER_BUILD_COMMAND = build

POETRY_VERSION ?= 2.1.2
PLATFORM ?= "linux/arm64"
BASE_IMAGE_HASH ?= localdev
BASE_BUILDER_IMAGE_HASH ?= localdev
RASA_DEPS_IMAGE_HASH ?= localdev
RASA_BASE_REPOSITORY ?= rasa-pro
RASA_BASE_IMAGE_TAG ?= latest
BASE_DOCKER_IMAGE_TAG = base-$(RASA_BASE_IMAGE_TAG)
BASE_BUILDER_DOCKER_IMAGE_TAG = base-builder-$(RASA_BASE_IMAGE_TAG)
BASE_RASA_DEPS_DOCKER_IMAGE_TAG = rasa-deps-$(RASA_BASE_IMAGE_TAG)

build-docker-base: ## Build base Docker image which contains dependencies necessary to create builder and Rasa images.
	docker $(DOCKER_BUILD_COMMAND) . \
		-t $(RASA_BASE_REPOSITORY)\:$(BASE_DOCKER_IMAGE_TAG) \
		-f docker/Dockerfile.base \
		--progress=plain \
		--platform=$(PLATFORM)

build-docker-builder:  ## Build Docker image which contains dependencies necessary to install Rasa's dependencies. Make sure to run build-docker-base before running this target.
	docker $(DOCKER_BUILD_COMMAND) . \
		-t $(RASA_BASE_REPOSITORY)\:$(BASE_BUILDER_DOCKER_IMAGE_TAG) \
		-f docker/Dockerfile.base-builder \
		--build-arg IMAGE_BASE_NAME=$(RASA_BASE_REPOSITORY) \
		--build-arg BASE_IMAGE_HASH=$(BASE_DOCKER_IMAGE_TAG) \
		--progress=plain \
		--platform=$(PLATFORM)

build-docker-rasa-deps:  ## Build Docker image which contains Rasa dependencies. Make sure to run build-docker-builder before running this target.
	docker $(DOCKER_BUILD_COMMAND) . \
		-t $(RASA_BASE_REPOSITORY)\:$(BASE_RASA_DEPS_DOCKER_IMAGE_TAG) \
		-f docker/Dockerfile.rasa-deps \
		--build-arg IMAGE_BASE_NAME=$(RASA_BASE_REPOSITORY) \
		--build-arg BASE_BUILDER_IMAGE_HASH=$(BASE_BUILDER_DOCKER_IMAGE_TAG) \
		--build-arg POETRY_VERSION=$(POETRY_VERSION) \
		--progress=plain \
		--platform=$(PLATFORM)

## RASA_IMAGE_TAGS is a list of tags that will be applied to the Rasa Pro Docker image.
## It enables us to tag the image with multiple tags without having to rebuild the image.
## This is mainly used in release pipelines to tag the image for different registries.
RASA_IMAGE_TAGS ?= -t $(RASA_REPOSITORY)\:$(RASA_IMAGE_TAG)

build-docker-rasa-image:  ## Build Rasa Pro Docker image. Make sure to run build-docker-base, build-docker-builder and build-docker-rasa-deps before running this target.
	docker $(DOCKER_BUILD_COMMAND) . \
		$(RASA_IMAGE_TAGS) \
		-f Dockerfile \
		--build-arg IMAGE_BASE_NAME=$(RASA_BASE_REPOSITORY) \
		--build-arg BASE_IMAGE_HASH=$(BASE_DOCKER_IMAGE_TAG) \
		--build-arg RASA_DEPS_IMAGE_HASH=$(BASE_RASA_DEPS_DOCKER_IMAGE_TAG) \
		--progress=plain \
		--platform=$(PLATFORM)

build-foundation-images: build-docker-base build-docker-builder build-docker-rasa-deps ## Build foundation Docker images (base, builder and rasa-deps).

build-docker: build-foundation-images build-docker-rasa-image## Build foundation images and Rasa Pro Docker image.

build-full-multi-platform-rasa-docker: PLATFORM = "linux/amd64,linux/arm64"
build-full-multi-platform-rasa-docker: DOCKER_BUILD_COMMAND = buildx build --push
build-full-multi-platform-rasa-docker: build-docker  ## Build foundation images and Rasa Pro Docker image for arm64 and amd64 platforms.

build-multi-platform-base-docker: PLATFORM = "linux/amd64,linux/arm64"
build-multi-platform-base-docker: DOCKER_BUILD_COMMAND = buildx build --push
build-multi-platform-base-docker: build-foundation-images # Build foundation images for arm64 and amd64 platforms.

build-multi-platform-rasa-docker: PLATFORM = "linux/amd64,linux/arm64"
build-multi-platform-rasa-docker: DOCKER_BUILD_COMMAND = buildx build --push
build-multi-platform-rasa-docker: build-docker-rasa-image  ## Build only Rasa Pro Docker image for arm64 and amd64 platforms.
