sonar.projectKey=RasaHQ_rasa-private
sonar.organization=rasahq
sonar.python.version=3.9
sonar.verbose=true
sonar.sources=/home/runner/work/rasa-private/rasa-private/rasa
sonar.tests=/home/runner/work/rasa-private/rasa-private/tests
sonar.exclusions=/home/runner/work/rasa-private/rasa-private/tests/**
sonar.python.coverage.reportPaths=/home/runner/work/rasa-private/rasa-private/artifacts/unit-tests-results-test-policies-python-3.9.xml,\
  /home/runner/work/rasa-private/rasa-private/artifacts/unit-tests-results-test-cli-python-3.9.xml,/home/runner/work/rasa-private/rasa-private/artifacts/unit-tests-results-test-nlu-featurizers-python-3.9.xml,\
  /home/runner/work/rasa-private/rasa-private/artifacts/unit-tests-results-test-nlu-predictors-python-3.9.xml,/home/runner/work/rasa-private/rasa-private/artifacts/unit-tests-results-test-full-model-training-python-3.9.xml,\
  /home/runner/work/rasa-private/rasa-private/artifacts/unit-tests-results-test-other-unit-tests-python-3.9.xml,/home/runner/work/rasa-private/rasa-private/artifacts/unit-tests-results-test-performance-python-3.9.xml,/home/runner/work/rasa-private/rasa-private/artifacts/unit-tests-results-test-flaky-python-3.9.xml,\
  /home/runner/work/rasa-private/rasa-private/artifacts/unit-tests-results-test-anonymization-python-3.9.xml
