help:
	@echo "    run"
	@echo "        Runs the bot on the command line."
	@echo "    train"
	@echo "        Train a stacked model using Rasa core & NLU."

run:
	rasa shell -m models --endpoints endpoints.yml

train:
	rasa train
