name: Destroy Pulumi Resources
description: Destroys Pulumi resources and removes the stack.
inputs:
  aws-region:
    description: AWS region
    required: true
  role-to-assume:
    description: AWS role to assume
    required: true
  pulumi-access-token:
    description: Pulumi access token
    required: true
  stack-name:
    description: Pulumi stack name
    required: true



runs:
  using: "composite"
  steps:

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@50ac8dd1e1b10d09dac7b8727528b91bed831ac0 # v3.0.2
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.aws-region }}

    - name: Set up kubeconfig
      env:
        AWS_REGION: ${{ inputs.aws-region }}
      shell: bash
      run: |
        aws eks update-kubeconfig --name rasa-pro-cluster --region $AWS_REGION

    - uses: pulumi/actions@cd99a7f8865434dd3532b586a26f9ebea596894f # v5.5.1
    - name: Destroy resources and remove the stack
      shell: bash
      env:
        PULUMI_ACCESS_TOKEN: ${{ inputs.pulumi-access-token }}
        STACK_NAME: ${{ inputs.stack-name }}
      run: |
        # Check if stack exists before attempting to destroy it
        if pulumi stack select rasa/rasa-pro-eks-helm/${{ env.STACK_NAME }} 2>/dev/null; then
          echo "Stack exists, destroying..."
          pulumi destroy -s rasa/rasa-pro-eks-helm/${{ env.STACK_NAME }} --yes
          pulumi stack rm rasa/rasa-pro-eks-helm/${{ env.STACK_NAME }} --yes
        else
          echo "Stack rasa/rasa-pro-eks-helm/${{ env.STACK_NAME }} does not exist, nothing to destroy"
        fi
