name: eks-integration-tests
description: RDS database for integration tests in EKS cluster
runtime:
  name: python
  options:
    toolchain: pip
    virtualenv: venv
config:
  pulumi:tags:
    value:
      pulumi:template: aws-python
