name: rasa-pro-eks-lb-controller
description: AWS EKS Load Balancer Controller for Rasa Pro
runtime:
  name: python
  options:
    toolchain: pip
    virtualenv: venv
config:
  pulumi:tags:
    value:
      pulumi:template: aws-python
