name: Debug broker test containers
description: Encapsulates steps for broker test debugging

inputs:
  COMPOSE_FILE_PATH:
    description: 'Broker tests docker compose path'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Check zookeeper logs
      env:
        COMPOSE_FILE: ${{ inputs.COMPOSE_FILE_PATH }}
      run: |
        docker compose -f "$COMPOSE_FILE" logs zookeeper
      shell: bash

    - name: Check kafka container logs
      env:
        COMPOSE_FILE: ${{ inputs.COMPOSE_FILE_PATH }}
      run: |
        docker compose -f "$COMPOSE_FILE" logs kafka
      shell: bash

    - name: Check rabbitmq container logs
      env:
        COMPOSE_FILE: ${{ inputs.COMPOSE_FILE_PATH }}
      run: |
        docker compose -f "$COMPOSE_FILE" logs rabbitmq
      shell: bash
