name: Setup Python Environment
description: Encapsulates steps for Testing

inputs:
  PYTHON_VERSION:
    description: 'Default Python Version'
    required: true
  WORKING_DIRECTORY:
    description: 'Directory to run `make install` in'
    required: false
    default: ${{ github.workspace }}
  MATRIX_JOB:
    description: "Matrix job name to create unique cache key for jobs"
    required: false
  RASA_DEFAULT_INSTALLATION_ONLY:
    description: "Install via `make install` target, which does not include any additional groups"
    required: false
    default: "false"
  OPTIONAL_GROUP_TO_INSTALL:
    description: "Optional group to install, from: nlu, channels or full. Incompatible with `RASA_DEFAULT_INSTALLATION_ONLY` input"
    required: false
    default: "full"
outputs:
  cache-hit:
    description: "Cache found or not"
    value: ${{ steps.cached-poetry-dependencies.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
      - name: Set up Python ${{ inputs.PYTHON_VERSION }} 🐍
        id: setup-python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: ${{ inputs.PYTHON_VERSION }}

      - name: Read Poetry Version 🔢
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
        run: |
          echo "POETRY_VERSION=$(scripts/poetry-version.sh)" >> $GITHUB_ENV
        shell: bash

      # Install & configure poetry
      -  name: Install Poetry ${{ env.POETRY_VERSION }}
         uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a # v1.4.1
         with:
          version: ${{ env.POETRY_VERSION }}
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      # Load cached venv if cache exists
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ${{ github.workspace }}/**/.venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock', '**/requirements.txt') }}-${{ inputs.MATRIX_JOB }}

      - name: Install Dependencies (Linux) 📦
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
        if: ${{ steps.cached-poetry-dependencies.outputs.cache-hit != 'true' }}
        env:
          RASA_DEFAULT_INSTALLATION_ONLY: ${{ inputs.RASA_DEFAULT_INSTALLATION_ONLY }}
          OPTIONAL_GROUP_TO_INSTALL: ${{ inputs.OPTIONAL_GROUP_TO_INSTALL }}
        run: |
          if [[ "${RASA_DEFAULT_INSTALLATION_ONLY}" == "true" ]]; 
          then
              poetry sync --only-root
          else
              poetry sync -E "${OPTIONAL_GROUP_TO_INSTALL}" --only-root
          fi
        shell: bash

      - name: Activate virtualenv
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
        run: |
          . .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
        shell: bash
