name: Debug metric test containers
description: Encapsulates steps for metric test debugging

inputs:
  COMPOSE_FILE_PATH:
    description: 'Metric tests docker compose path'
    required: true

runs:
  using: 'composite'
  steps:
  - name: Check otlp-collector container logs
    run: |
      docker compose -f ${{ inputs.COMPOSE_FILE_PATH }} logs otlp-collector
  
  - name: Check prometheus container logs
    run: |
      docker compose -f ${{ inputs.COMPOSE_FILE_PATH }} logs prometheus
  
  - name: Check rasa-pro-assistent container logs
    run: |
      docker compose -f ${{ inputs.COMPOSE_FILE_PATH }} logs rasa-pro-assistant
  
  - name: Check action-server container logs
    run: |
      docker compose -f ${{ inputs.COMPOSE_FILE_PATH }} logs action-server