name: Debug metric test containers
description: Encapsulates steps for metric test debugging

inputs:
  COMPOSE_FILE_PATH:
    description: 'Metric tests docker compose path'
    required: true

runs:
  using: 'composite'
  steps:
    - name: List containers
      run: sudo docker ps -a
      shell: bash

    - name: Check otlp-collector container logs
      env:
        COMPOSE_FILE: ${{ inputs.COMPOSE_FILE_PATH }}
      run: |
        docker compose -f "$COMPOSE_FILE" logs otlp-collector
      shell: bash

    - name: Check prometheus container logs
      env:
        COMPOSE_FILE: ${{ inputs.COMPOSE_FILE_PATH }}
      run: |
        docker compose -f "$COMPOSE_FILE" logs prometheus
      shell: bash

    - name: Check rasa-pro-assistant container logs
      env:
        COMPOSE_FILE: ${{ inputs.COMPOSE_FILE_PATH }}
      run: |
        docker compose -f "$COMPOSE_FILE" logs rasa-pro-assistant
      shell: bash

    - name: Check action-server container logs
      env:
        COMPOSE_FILE: ${{ inputs.COMPOSE_FILE_PATH }}
      run: |
        docker compose -f "$COMPOSE_FILE" logs action-server
      shell: bash
