name: Test prerequisites
description: Encapsulates steps for Testing

inputs:
  PYTHON_VERSION:
    description: "Default Python Version"
    required: true
  LOAD_CACHE:
    description: "Load cached Rasa or not. Default = true"
    required: false
    default: "true"
  RASA_INSTALL_GROUP:
    description: "Rasa install group."
    required: false
    default: "full"
outputs:
  CACHE_LOADED:
    description: "Cache hit and cache loaded or not"
    value: ${{ steps.cached-poetry-dependencies.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.PYTHON_VERSION }} 🐍
      id: setup-python
      uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
      with:
        python-version: ${{ inputs.PYTHON_VERSION }}

    - name: Read Poetry Version 🔢
      run: |
        echo "POETRY_VERSION=$(scripts/poetry-version.sh)" >> $GITHUB_ENV
      shell: bash

    # Install & configure poetry
    - name: Install Poetry ${{ env.POETRY_VERSION }}
      uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a # v1.4.1
      with:
        version: ${{ env.POETRY_VERSION }}
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    # Load cached venv if exists, save cache after job on miss
    - name: Cache venv
      id: cached-poetry-dependencies
      if: ${{ inputs.LOAD_CACHE == 'true' }}
      uses: WarpBuilds/cache@8f10197bad216ec3a6ba6188e7e41e5f52f894cc # v1.4.7
      with:
        path: ${{ github.workspace }}/.venv
        key: rasa-${{ inputs.RASA_INSTALL_GROUP }}-install-${{ runner.os }}-${{ inputs.PYTHON_VERSION }}-${{ hashFiles('poetry.lock') }}

    # Install if no cache hits. This is a workaround for the fact that a cache could get evicted.
    - name: Install Rasa dependencies
      if: ${{ steps.cached-poetry-dependencies.outputs.cache-hit != 'true' }}
      run: |
        if [ "${{ env.RASA_INSTALL_GROUP }}" = "default" ]; then
          make install | tee .output
        else
          make install-${{ env.RASA_INSTALL_GROUP }} | tee .output
        fi
        if grep 'The lock file is not up to date' .output; then exit 1; fi
      shell: bash
      env:
        RASA_INSTALL_GROUP: ${{ inputs.RASA_INSTALL_GROUP }}
