name: Debug custom actions integration test containers
description: Encapsulates steps for custom actions test debugging

inputs:
  COMPOSE_FILE_PATH:
    description: 'Custom action docker compose path'
    required: true

runs:
  using: 'composite'
  steps:
  - name: Check rasa-pro container logs
    run: |
      docker compose -f ${{ inputs.COMPOSE_FILE_PATH }} logs rasa-pro
    shell: bash
  
  - name: Check rasa-pro-grpc-ssl container logs
    run: |
      docker compose -f ${{ inputs.COMPOSE_FILE_PATH }} logs rasa-pro-grpc-ssl
    shell: bash
  
  - name: Check rasa-grpc-action-server container logs
    run: |
      docker compose -f ${{ inputs.COMPOSE_FILE_PATH }} logs rasa-grpc-action-server
    shell: bash
  
  - name: Check rasa-grpc-ssl-action-server container logs
    run: |
      docker compose -f ${{ inputs.COMPOSE_FILE_PATH }} logs rasa-grpc-ssl-action-server
    shell: bash