name: Debug custom actions integration test containers
description: Encapsulates steps for custom actions test debugging

inputs:
  COMPOSE_FILE_PATH:
    description: 'Custom action docker compose path'
    required: true
  ENV_FILE_PATH:
    description: 'Custom action environment file path'
    required: true
  RASA_DOCKER_REPOSITORY:
    description: 'Rasa repository path'
    required: true
  RASA_IMAGE_TAG:
    description: 'Rasa image tag'
    required: true

runs:
  using: 'composite'
  steps:
  - name: Check rasa-pro-grpc container logs
    run: |
      RASA_REPOSITORY=${{ inputs.RASA_DOCKER_REPOSITORY }} \
      RASA_IMAGE_TAG=${{ inputs.RASA_IMAGE_TAG }} \
      docker compose -f ${{ inputs.COMPOSE_FILE_PATH }} \
        --env-file=${{ inputs.ENV_FILE_PATH }} \
        logs rasa-pro-grpc
    shell: bash
  
  - name: Check rasa-pro-grpc-ssl container logs
    run: |
      RASA_REPOSITORY=${{ inputs.RASA_DOCKER_REPOSITORY }} \
      RASA_IMAGE_TAG=${{ inputs.RASA_IMAGE_TAG }} \
      docker compose -f ${{ inputs.COMPOSE_FILE_PATH }} \
      --env-file=${{ inputs.ENV_FILE_PATH }} \
      logs rasa-pro-grpc-ssl
    shell: bash
  
  - name: Check rasa-grpc-action-server container logs
    run: |
      RASA_REPOSITORY=${{ inputs.RASA_DOCKER_REPOSITORY }} \
      RASA_IMAGE_TAG=${{ inputs.RASA_IMAGE_TAG }} \
      docker compose -f ${{ inputs.COMPOSE_FILE_PATH }} \
      --env-file=${{ inputs.ENV_FILE_PATH }} \
      logs rasa-grpc-action-server
    shell: bash
  
  - name: Check rasa-grpc-ssl-action-server container logs
    run: |
      RASA_REPOSITORY=${{ inputs.RASA_DOCKER_REPOSITORY }} \
      RASA_IMAGE_TAG=${{ inputs.RASA_IMAGE_TAG }} \
      docker compose -f ${{ inputs.COMPOSE_FILE_PATH }} \
      --env-file=${{ inputs.ENV_FILE_PATH }} \
      logs rasa-grpc-ssl-action-server
    shell: bash

  - name: Check rasa-pro-http container logs
    run: |
      RASA_REPOSITORY=${{ inputs.RASA_DOCKER_REPOSITORY }} \
      RASA_IMAGE_TAG=${{ inputs.RASA_IMAGE_TAG }} \
      docker compose -f ${{ inputs.COMPOSE_FILE_PATH }} \
        --env-file=${{ inputs.ENV_FILE_PATH }} \
        logs rasa-pro-http
    shell: bash

  - name: Check rasa-pro-https container logs
    run: |
      RASA_REPOSITORY=${{ inputs.RASA_DOCKER_REPOSITORY }} \
      RASA_IMAGE_TAG=${{ inputs.RASA_IMAGE_TAG }} \
      docker compose -f ${{ inputs.COMPOSE_FILE_PATH }} \
      --env-file=${{ inputs.ENV_FILE_PATH }} \
      logs rasa-pro-https
    shell: bash

  - name: Check rasa-http-action-server container logs
    run: |
      RASA_REPOSITORY=${{ inputs.RASA_DOCKER_REPOSITORY }} \
      RASA_IMAGE_TAG=${{ inputs.RASA_IMAGE_TAG }} \
      docker compose -f ${{ inputs.COMPOSE_FILE_PATH }} \
      --env-file=${{ inputs.ENV_FILE_PATH }} \
      logs rasa-grpc-action-server
    shell: bash

  - name: Check rasa-https-action-server container logs
    run: |
      RASA_REPOSITORY=${{ inputs.RASA_DOCKER_REPOSITORY }} \
      RASA_IMAGE_TAG=${{ inputs.RASA_IMAGE_TAG }} \
      docker compose -f ${{ inputs.COMPOSE_FILE_PATH }} \
      --env-file=${{ inputs.ENV_FILE_PATH }} \
      logs rasa-https-action-server
    shell: bash