recipe: default.v1
language: en
pipeline:
- name: SingleStepLLMCommandGenerator
  llm:
    model: gpt-4
    timeout: 7
    temperature: 0.0
    top_p: 0.0

policies:
- name: FlowPolicy
- name: IntentlessPolicy
assistant_id: 20241206-153203-mild-column
