FROM python:3.6-slim as builder
# if this installation process changes, the enterprise container needs to be
# updated as well
WORKDIR /build
COPY . .
RUN python setup.py sdist bdist_wheel
RUN find dist -maxdepth 1 -mindepth 1 -name '*.tar.gz' -print0 | xargs -0 -I {} mv {} rasa.tar.gz

FROM python:3.6-slim

SHELL ["/bin/bash", "-c"]

RUN apt-get update -qq && \
  apt-get install -y --no-install-recommends \
  build-essential \
  wget \
  openssh-client \
  graphviz-dev \
  pkg-config \
  git-core \
  openssl \
  libssl-dev \
  libffi6 \
  libffi-dev \
  libpng-dev \
  libpq-dev \
  curl && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
  mkdir /install && \
  mkdir /app

WORKDIR /install

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY --from=builder /build/rasa.tar.gz .
RUN pip install ./rasa.tar.gz[spacy]

RUN python -m spacy download fr_core_news_sm \
    && python -m spacy link fr_core_news_sm fr

COPY alt_requirements/ ./alt_requirements
RUN pip install -r alt_requirements/requirements_botfront.txt

VOLUME ["/app"]
WORKDIR /app

EXPOSE 5005

ENTRYPOINT ["rasa"]

CMD ["--help"]
