# Create common base stage
FROM python:3.6-slim as base

WORKDIR /build

# Create virtualenv to isolate builds
RUN python -m venv /build

# Make sure we use the virtualenv
ENV PATH="/build/bin:$PATH"

# Stage to build and install everything
FROM base as builder

WORKDIR /src

# Install all required build libraries
RUN apt-get update -qq && \
  apt-get install -y --no-install-recommends \
  build-essential \
  wget \
  openssh-client \
  graphviz-dev \
  pkg-config \
  git-core \
  openssl \
  libssl-dev \
  libffi6 \
  libffi-dev \
  libpng-dev \
  libpq-dev \
  curl

# Install spacy model
RUN pip install https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-2.1.0/de_core_news_sm-2.1.0.tar.gz#egg=de_core_news_sm==2.1.0 --no-cache-dir > /dev/null \
    && python -m spacy link de_core_news_sm de

# Copy only what we really need
COPY README.md .
COPY setup.py .
COPY MANIFEST.in .
COPY alt_requirements/ ./alt_requirements
COPY requirements.txt .

# Install Rasa and its dependencies
RUN pip install --no-cache-dir -r alt_requirements/requirements_pretrained_embeddings_spacy.txt

# Install Rasa as package
COPY rasa ./rasa
RUN pip install .[sql,spacy]

# Runtime stage which uses the virtualenv which we built in the previous stage
FROM base AS runner

# Copy over default pipeline config
COPY sample_configs/config_pretrained_embeddings_spacy_de.yml /app/config.yml

# Copy virtualenv from previous stage
COPY --from=builder /build /build

WORKDIR /app

# Create a volume for temporary data
VOLUME /tmp

# Make sure the default group has the same permissions as the owner
RUN chgrp -R 0 . && chmod -R g=u .

# Don't run as root
USER 1001

EXPOSE 5005

HEALTHCHECK --start-period=10s \
  CMD curl -f http://localhost:5005 || exit 1

ENTRYPOINT ["rasa"]
CMD ["--help"]
