export * as inspectorShell from "./inspector-shell.actions";
export * as conversationLog from "./conversation-log.actions";
export * as inspectorCanvas from "./inspector-canvas.actions";
export * as eventDetails from "./event-details.actions";
export * as viewMenu from "./view-menu.actions";
export * as historyTimeline from "./history-timeline.actions";
export * as memoryPanel from "./memory-panel.actions";
export * as downloads from "./downloads.actions";
export * as voiceControls from "./voice-controls.actions";
