recipe: default.v1
language: en
pipeline:
  - name: SingleStepLLMCommandGenerator
    llm:
      model_name: gpt-4

policies:
  - name: FlowPolicy
#  - name: EnterpriseSearchPolicy
#  - name: RulePolicy
