x-environment: &environment
  RASA_PRO_LICENSE: ${RASA_PRO_LICENSE}
  OPENAI_API_KEY: ${OPENAI_API_KEY}

services:
  rasa-pro-assistant:
    image: ${RASA_REPOSITORY}:${RASA_IMAGE_TAG}
    volumes:
      - "./calm-demo-bot:/app"
    networks: [ 'rasa-pro-network' ]
    entrypoint: ""
    command: rasa run --debug
    ports:
      - "5005:5005"
    environment:
      <<: *environment
    user: ${USER_ID}
    healthcheck:
      test: curl localhost:5005 || exit 1
      interval: 10s
      retries: 10
      start_period: 15s
      timeout: 10s

  postgres:
    image: postgres:14
    networks: [ 'rasa-pro-network' ]
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: rasa
      POSTGRES_PASSWORD: rasa
      POSTGRES_DB: rasa
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rasa"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:

networks: { rasa-pro-network: { } }
