name: Pull rasa-private dev docker image from ECR
description: Encapsulates steps for pulling rasa-private dev docker image from ECR

permissions:
  id-token: write
  contents: read

inputs:
  IMAGE_TAG:
    description: 'Image tag'
    required: true
  AWS_REGION:
    description: 'AWS Region'
    required: true
  AWS_ARN_ROLE_TO_ASSUME:
    description: 'AWS role ARN'
    required: true
  REPOSITORY:
    description: 'ECR Repository'
    required: true
  
runs:
  using: 'composite'
  steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@8c3f20df09ac63af7b3ae3d7c91f105f857d8497 # v3.0.1
        with:
          role-to-assume: ${{ inputs.AWS_ARN_ROLE_TO_ASSUME }}
          aws-region: ${{ inputs.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
        with:
          mask-password: "true"

      - name: Pull dev rasa-private image from Amazon ECR
        id: check_image
        run: |
          docker pull ${{ inputs.REPOSITORY }}:${{ inputs.IMAGE_TAG }}
        shell: bash
        