name: Free up disk space on runner
description: Free up disk space on GHA runner

runs:
  using: composite
  steps:
    - name: Free up disk space
      run: |
        df -h
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        sudo apt clean
        docker image prune -a -f
        docker volume prune -f
        docker container prune -f
        df -h
      shell: bash
