import { v4 as uuid } from "uuid";

import {
  immutableJSONPatch,
  type JSONPatchDocument,
} from "immutable-json-patch";
import {
  type Utterance,
  type ConversationEvent,
  type InspectorEventType,
  type StackEvent,
  type UnionEventType,
  ConversationEventType,
  UtteranceType,
  type RawEvent,
  type EventMetadata,
  type UtteranceIntent,
  type MessageIntent,
  type BackendResponseData,
  type ResponseData,
  type QuickReply,
  type Button,
} from "../types";

export const eventTexts: { [key: string]: string } = {
  [ConversationEventType.FlowCancelled]: " cancelled",
  [ConversationEventType.FlowCompleted]: " completed",
  [ConversationEventType.FlowStarted]: " started",
  [ConversationEventType.FlowInterrupted]: " interrupted",
  [ConversationEventType.FlowResumed]: " resumed",
};

export const isInternalRasaSlot = (slotName: string) => {
  // Slots that we hide from the UI as they aren't user-facing and won't be
  // helpful for debugging
  return ["flow_hashes", "dialogue_stack"].includes(slotName);
};

export const isInternalRasaAction = (actionName: string) => {
  // Actions that we hide from the UI as they aren't user-facing and won't be
  // helpful for debugging
  return ["action_run_slot_rejections"].includes(actionName);
};

export const isInternalRasaEvent = (eventName: string) => {
  // Events that we hide from the UI as they aren't user-facing and won't be
  // helpful for debugging
  return ["session_started", "user_featurization"].includes(eventName);
};

export const isInternalRasaMessage = (message: string) => {
  // Messages that are internally generated by Rasa and not user-facing
  return ["/session_start", "/silence_timeout"].includes(message);
};

export const isInternalRasaFlow = (flowId: string) => {
  // These two flows use features that are not supported in the UI yet, so
  // even if they might be helpful, we can't show them.
  // - pattern_collect_information uses a loop
  // - pattern_user_silence uses a persisted slot
  return ["pattern_collect_information", "pattern_user_silence"].includes(
    flowId,
  );
};

interface StackFrame {
  flow_id: string;
  step_id: string;
}

export function isConversationEvent(
  event: InspectorEventType,
): event is ConversationEvent {
  return event.__typename === "ConversationEvent";
}

function updateStackWithEvent(
  stack: StackFrame[],
  event: StackEvent,
): StackFrame[] {
  if (event.update) {
    const stackUpdate = JSON.parse(event.update) as JSONPatchDocument;
    return immutableJSONPatch(stack, stackUpdate);
  }
  return stack;
}

function hasFlowAtTheTopOfStack(stack: StackFrame[]): boolean {
  return stack.length > 0 && stack[stack.length - 1].flow_id !== undefined;
}

export const flowStepTrail = (
  events: InspectorEventType[],
): Record<string, string[]> => {
  let stack: StackFrame[] = [];
  // mapping from flow id to the steps that were active in that flow, including loops
  let activeSteps: { [key: string]: string[] } = {};
  for (const event of events) {
    if (
      isConversationEvent(event) &&
      event.conversationEventType === ConversationEventType.Restart
    ) {
      stack = [];
      activeSteps = {};
    } else if (isStackEvent(event)) {
      stack = updateStackWithEvent(stack, event);
      if (!hasFlowAtTheTopOfStack(stack)) {
        continue;
      }
      const topFrame = stack[stack.length - 1];
      if (!activeSteps[topFrame.flow_id] || topFrame.step_id === "START") {
        activeSteps[topFrame.flow_id] = [];
      }
      activeSteps[topFrame.flow_id].push(topFrame.step_id);
    }
  }
  return activeSteps;
};

export const getSlotRelatedEvents = (
  events: UnionEventType[],
): ConversationEvent[] => {
  return events.filter((event) => {
    if (!isConversationEvent(event)) {
      return false;
    }

    if (event.conversationEventType === ConversationEventType.Slot) {
      return true;
    }

    if (
      event.conversationEventType === ConversationEventType.FlowStarted ||
      event.conversationEventType === ConversationEventType.FlowCompleted ||
      event.conversationEventType === ConversationEventType.FlowCancelled
    ) {
      if (event.flowId?.startsWith("pattern_")) {
        return false;
      }
      return true;
    }

    if (event.conversationEventType === ConversationEventType.SessionStarted) {
      return true;
    }

    return false;
  }) as ConversationEvent[];
};

export function isUtterance(event: UnionEventType): event is Utterance {
  return (
    (event as Utterance).type === UtteranceType.Bot ||
    (event as Utterance).type === UtteranceType.User
  );
}

export function isStackEvent(event: InspectorEventType): event is StackEvent {
  return event.__typename === "StackEvent";
}

function generateResponseData(response: BackendResponseData): ResponseData {
  const result: ResponseData = {
    buttons: [],
    quickReplies: [],
  };

  if (response.text) {
    const linkRegex = new RegExp(/\[(.*?)\]\s*\((.*?)\)/);
    const matches = linkRegex.exec(response.text);
    if (matches) {
      result.attachment = matches[2];
    }
  }

  if (response.attachment) {
    if (response.attachment.type === "image") {
      result.image = response.attachment.payload.src;
    }
    if (response.attachment.type === "link") {
      result.attachment = response.attachment.payload.url;
    }
    if (response.attachment.type === "template") {
      result.elements = response.attachment.payload.elements;
    }
  }

  if (response.quick_replies) {
    result.quickReplies = response.quick_replies.map(
      (quickReply: QuickReply & { image_url?: string }) => ({
        title: quickReply.title,
        payload: quickReply.payload,
        imageUrl: quickReply.image_url,
      }),
    );
  }

  if (response.buttons) {
    result.quickReplies = response.buttons.map(
      (button: Button & { image_url?: string }) => ({
        title: button.title,
        payload: button.payload,
        imageUrl: button.image_url,
      }),
    );
  }

  if (response.elements) {
    result.elements = response.elements;
  }

  result.custom = checkForCustomElements(response);

  return result;
}

function checkForCustomElements(
  response: Record<string, unknown>,
): Record<string, unknown> | undefined {
  const keys = [
    "text",
    "attachment",
    "quick_replies",
    "buttons",
    "elements",
    "image",
  ];
  const customElements: Record<string, unknown> = {};

  for (const key in response) {
    if (
      response.hasOwnProperty(key) &&
      !keys.includes(key) &&
      response[key] !== null
    ) {
      customElements[key] = response[key];
    }
  }

  if (Object.keys(customElements).length > 0) {
    return customElements;
  }

  return undefined;
}

export function mapRawEventsToConversationEvents(
  events: RawEvent[],
): UnionEventType[] {
  const mappedEvents = events.map((event) => {
    if (!event.metadata) {
      event.metadata = {} as EventMetadata;
    }

    // this is a fix, since some events store the flow id under a differnet key...
    // e.g. bot uttered, set slot, action
    event.metadata.flow_id =
      event.metadata.active_flow || event.metadata.flow_id;

    const parsedTimestamp = new Date(event.timestamp * 1000).toISOString();

    switch (event.event) {
      case "user" as const: {
        const intents: UtteranceIntent[] =
          event.parse_data?.intent_ranking?.map((intent: MessageIntent) => ({
            id: uuid(),
            name: intent.name,
            confidence: intent.confidence,
          })) || [];

        return {
          id: uuid(),
          conversationId: event.conversation_id,
          machineLearningModelId: "",
          entities: [],
          intents,
          text: event.text,
          tokens: [],
          timestamp: parsedTimestamp,
          type: UtteranceType.User,
          __typename: "Utterance",
          rephrase: false,
          rephrasePrompt: null,
          commands: event.parse_data?.commands,
          metadata: {
            ...event.metadata,
            parseData: event.parse_data,
            rawEvent: event,
          },
        };
      }
      case "bot" as const:
        return {
          id: uuid(),
          conversationId: event.conversation_id,
          machineLearningModelId: "",
          entities: [],
          intents: [],
          text: event.text || "",
          responseData: generateResponseData({
            ...event.data,
            text: event.text,
          }),
          tokens: [],
          timestamp: parsedTimestamp,
          type: UtteranceType.Bot,
          commands: null,
          rephrase: event.metadata?.metadata?.rephrase || false,
          rephrasePrompt: event.metadata?.metadata?.rephrasePrompt || null,
          metadata: {
            ...event.metadata,
            rawEvent: event,
          },
          __typename: "Utterance",
        };
      case "stack" as const:
        return {
          id: uuid(),
          metadata: {
            ...event.metadata,
            rawEvent: event,
          },
          update: event.update || "",
          timestamp: parsedTimestamp,
          __typename: "StackEvent",
        };
      case "action":
        return {
          id: uuid(),
          actionText: event.name,
          conversationEventType: event.event.toUpperCase(),
          flowId: event.flow_id || event.metadata?.active_flow,
          metadata: {
            ...event.metadata,
            rawEvent: event,
          },
          name: event.name,
          slotValue: undefined,
          stepId: event.step_id || event.metadata?.step_id,
          timestamp: parsedTimestamp,
          __typename: "ConversationEvent",
        };
      case "slot" as const:
        return {
          id: uuid(),
          actionText: undefined,
          conversationEventType: event.event.toUpperCase(),
          flowId: event.flow_id || event.metadata?.active_flow,
          metadata: {
            ...event.metadata,
            rawEvent: event,
          },
          name: event.name,
          slotValue: event.value,
          stepId: event.step_id || event.metadata?.step_id,
          timestamp: parsedTimestamp,
          __typename: "ConversationEvent",
        };
      default:
        return {
          id: uuid(),
          actionText: undefined,
          conversationEventType: (event.event as string).toUpperCase(),
          flowId: event.flow_id || event.metadata?.active_flow,
          metadata: {
            ...event.metadata,
            rawEvent: event,
          },
          name: event.name,
          slotValue: undefined,
          stepId: event.step_id || event.metadata?.step_id,
          timestamp: parsedTimestamp,
          __typename: "ConversationEvent",
        };
    }
  });

  // TODO: this is a hacky workaround to add the flow and step info to the metadata
  //  since it is missing from the user uttered events
  //  if the info is missing from an event, it will be the same as the previous event
  const previousFlowState: { flow_id?: string; step_id?: string } = {
    flow_id: undefined,
    step_id: undefined,
  };

  for (const event of mappedEvents) {
    if (!event.metadata?.flow_id) {
      event.metadata.flow_id = previousFlowState.flow_id;
      event.metadata.step_id = previousFlowState.step_id;
      continue;
    }
    previousFlowState.flow_id = event.metadata.flow_id;
    previousFlowState.step_id = event.metadata.step_id;
  }

  return mappedEvents as UnionEventType[];
}

export const formatDateToLocale = (
  date: Date,
  locale?: Intl.LocalesArgument,
) => {
  const dateFormat: Intl.DateTimeFormatOptions = {
    timeZoneName: "short",
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "numeric",
    second: "numeric",
  };

  return date.toLocaleDateString(locale, dateFormat);
};

export const formatDateTime = (
  timestamp: Date | string | number,
  locale: Intl.LocalesArgument = "en-US",
) => {
  try {
    let date: Date;

    if (timestamp instanceof Date) {
      date = timestamp;
    } else if (typeof timestamp === "string" || typeof timestamp === "number") {
      const unixTimestamp =
        (typeof timestamp === "string"
          ? Number.parseFloat(timestamp)
          : timestamp) * 1000;
      date = new Date(unixTimestamp);
    } else {
      console.error("Invalid timestamp type:", typeof timestamp, timestamp);
      return "Invalid date";
    }

    // Check if the date is valid
    if (Number.isNaN(date.getTime())) {
      console.error("Invalid date:", timestamp);
      return "Invalid date";
    }

    return date.toLocaleString(locale, {
      month: "short",
      day: "2-digit",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit",
      second: "2-digit",
      hour12: false,
      timeZoneName: "short",
    });
  } catch (error) {
    console.error("Error formatting timestamp:", timestamp, error);
    return "Invalid date";
  }
};

/**
 * Converts a Date object to Unix timestamp string (seconds with fractional milliseconds)
 * @param date - The Date object to convert
 * @returns Unix timestamp as string (e.g., "1759832715.699")
 */
export const dateToUnixTimestamp = (date: Date): string => {
  // Get milliseconds since epoch and convert to seconds with fractional part
  const unixTimestamp = date.getTime() / 1000;
  return unixTimestamp.toString();
};
