name: eks-headlamp
description: A user-friendly Kubernetes UI focused on extensibility
runtime:
  name: python
  options:
    toolchain: pip
    virtualenv: venv
config:
  pulumi:tags:
    value:
      pulumi:template: aws-python
