name: Lint action
description: Lints GitHub Action

inputs:
  workflow_path:
    description: Name of the GitHub-Action/Workflow to be linted
    required: true  

runs:
  using: composite
  steps:
    - name: actionlint
      uses: raven-actions/actionlint@e01d1ea33dd6a5ed517d95b4c0c357560ac6f518 #v2.1.1
      with:
        files: ${{ inputs.workflow_path }}
