recipe: default.v1
assistant_id: moist-swiss
language: en
pipeline:
- name: CompactLLMCommandGenerator
  llm:
    provider: openai
    model: gpt-4o-2024-11-20
    timeout: 7

policies:
- name: FlowPolicy
- name: IntentlessPolicy
