config:
  aws:region: eu-west-1
  pulumi:template: https://github.com/rasahq/pulumi-templates/tree/head/aws-eks-cluster
  eks-cluster:albControllerChartVersion: 1.7.1
  eks-cluster:clusterDiskSize: "100"
  eks-cluster:clusterName: rasa-pro-ci-cluster
  eks-cluster:headlampHelmVersion: 0.32.1
  eks-cluster:maxClusterSize: "1"
  eks-cluster:minClusterSize: "1"
  eks-cluster:nodegroupInstanceType: m5.xlarge
environment:
  - atom/atom-ci