name: eks-cluster
description: Pulumi stack for deploying Rasa Pro infrastructure and running integration tests on EKS cluster on CI Playground
runtime: yaml
config:
  clusterName:
    type: string
  minClusterSize:
    type: integer
    default: 1
  maxClusterSize:
    type: integer
    default: 1
  clusterDiskSize:
    type: integer
    default: 100
  nodegroupInstanceType:
    type: string
    default: t3.xlarge
  albControllerChartVersion:
    type: string
    default: "3.1.0"
  headlampHelmVersion:
    type: string
    default: "0.42.0"
  pulumi:tags:
    value:
      pulumi:template: https://github.com/RasaHQ/pulumi-templates/tree/main/infrastructure/aws-eks-cluster
packages:
  rasa-aws: github.com/RasaHQ/pulumi-components/rasa-aws@v3.1.0-rasa-aws
  rasa-apps: github.com/RasaHQ/pulumi-components/rasa-apps@v1.5.0-rasa-apps
  rasa-cloudflare: github.com/RasaHQ/pulumi-components/rasa-cloudflare@v2.0.0-rasa-cloudflare
resources:
  cluster:
    type: rasa-aws:EksCluster
    properties:
      name: ${clusterName}
      vpcAvailabilityZones: 2
      vpcSingleNatGateway: true
      nodegroupInstanceType: ${nodegroupInstanceType}
      nodegroupMinSize: ${minClusterSize}
      nodegroupMaxSize: ${maxClusterSize}
      nodegroupDiskSize: ${clusterDiskSize}
      nodegroupAmiType: AL2023_x86_64_STANDARD
      enableEbsDriver: true
      enableAlbController: false
      enableExternalDns: false
      enableAutoscaler: false
  k8sProvider:
    type: pulumi:providers:kubernetes
    properties:
      kubeconfig: ${cluster.kubeConfig}
  albController:
    type: rasa-aws:AlbController
    properties:
      clusterName: ${cluster.clusterName}
      clusterOidcProviderUrl: ${cluster.oidcProviderUrl}
      clusterOidcProviderArn: ${cluster.oidcProviderArn}
      vpcId: ${cluster.vpcId}
      awsRegion: ${aws:region}
      controllerChartVersion: ${albControllerChartVersion}
      controllerChartValues: {}
    options:
      provider: ${k8sProvider}
      dependsOn:
        - ${cluster}
  headlamp:
    type: rasa-apps:Headlamp
    properties:
      headlampHelmRepo: https://kubernetes-sigs.github.io/headlamp/
      headlampHelmVersion: ${headlampHelmVersion}
      namespace: headlamp
      helmValues: ${headlampHelmValues}
    options:
      provider: ${k8sProvider}
      dependsOn:
        - ${albController}
  headlampDns:
    type: rasa-cloudflare:IngressDnsRecord
    properties:
      kubernetesNamespace: headlamp
      kubernetesIngress: headlamp
      cloudflareZoneId: ${cloudflareZoneId}
      cloudflareHostname: pro-ci-headlamp.rasa-dev.io
    options:
      providers:
        - ${k8sProvider}
      dependsOn:
        - ${headlamp}
outputs:
  clusterName: ${cluster.clusterName}
  kubeConfig: ${cluster.kubeConfig}
  headlampUrl: https://pro-ci-headlamp.rasa-dev.io
  vpc_id: ${cluster.vpcId}
  private_subnets: ${cluster.vpcPrivateSubnetIds}
  oidcProviderArn: ${cluster.oidcProviderArn}
  oidcProviderUrl: ${cluster.oidcProviderUrl}
variables:
  headlampHelmValues:
    fullnameOverride: headlamp
    config:
      inCluster: true
      baseURL: ""
    service:
      type: ClusterIP
      port: 80
    ingress:
      enabled: true
      ingressClassName: alb
      annotations:
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
        alb.ingress.kubernetes.io/backend-protocol: 'HTTP'
        alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-1:329710836760:certificate/a9206eb9-c1ba-4f77-93f2-683440788965
        alb.ingress.kubernetes.io/group.name: ${pulumi.project}-${pulumi.stack}-alb-group
      hosts:
        - host: pro-ci-headlamp.rasa-dev.io
          paths:
            - path: /
              type: Prefix
      tls:
        - secretName: headlamp-tls
          hosts:
            - pro-ci-headlamp.rasa-dev.io
    serviceAccount:
      create: true
      name: headlamp-admin
    clusterRoleBinding:
      create: true
      clusterRoleName: cluster-admin