const { readFileSync, writeFileSync } = require('fs');
const { execSync } = require('child_process');

const VERSION_PATTERN = new RegExp(/^__version__ = "(.+)"$/);
const VARIABLES_FILE_PATH = './src/variables.js';
const JSON_SPACE_INDENT = 4;

const getRasaVersion = () => {
    const version = readFileSync('../rasa/version.py')
        .toString()
        .split('\n')
        .filter((line) => VERSION_PATTERN.test(line))
        // cleanup the line
        .map((line) => line.replace(VERSION_PATTERN, '$1'))
        // cleanup the version
        .map((line) => line.split('.').slice(0, 3).join('.'))[0];
    if (!version) {
        // error
    }
    return version;
};

const getRasaSdkVersion = () => {
    return execSync(
        'poetry run python -c "from rasa_sdk import __version__ as rasa_sdk_version; print(rasa_sdk_version)"',
    )
        .toString()
        .trim();
};

const writeVariablesFile = () => {
    const variables = JSON.stringify(
        {
            release: getRasaVersion(),
            rasa_sdk_version: getRasaSdkVersion(),
        },
        null,
        JSON_SPACE_INDENT,
    );
    const fileContent = `// this file is automatically generated, please do not update it manually\n\nexport default ${variables}`;
    writeFileSync(VARIABLES_FILE_PATH, fileContent);
};

console.info(`Computing docs variables and writing to ${VARIABLES_FILE_PATH}`);
writeVariablesFile();
