module.exports = {
  someSidebar: {
    "User Guide": [
      "index",
      "user-guide/installation",
      "user-guide/rasa-tutorial",
      "user-guide/building-assistants",
      "user-guide/command-line-interface",
      "user-guide/architecture",
      "user-guide/messaging-and-voice-channels",
      "user-guide/testing-your-assistant",
      "user-guide/setting-up-ci-cd",
      "user-guide/validate-files",
      "user-guide/configuring-http-api",
      "user-guide/how-to-deploy",
      "user-guide/cloud-storage",
    ],
    "NLU": [
      "nlu/about",
      "nlu/using-nlu-only",
      "nlu/training-data-format",
      "nlu/language-support",
      "nlu/choosing-a-pipeline",
      "nlu/components",
      "nlu/entity-extraction",
    ],
    "Core": [
      "core/about",
      "core/stories",
      "core/domains",
      "core/responses",
      "core/actions",
      "core/reminders-and-external-events",
      "core/policies",
      "core/slots",
      "core/forms",
      "core/retrieval-actions",
      "core/interactive-learning",
      "core/fallback-actions",
      "core/knowledge-bases",
    ],
    "Conversation Design": [
      "dialogue-elements/dialogue-elements",
      "dialogue-elements/small-talk",
      "dialogue-elements/completing-tasks",
      "dialogue-elements/guiding-users",
    ],
    "API Reference": [
      "api/action-server",
      "api/http-api",
      "api/jupyter-notebooks",
      "api/agent",
      "api/custom-nlu-components",
      "api/rasa-sdk",
      "api/events",
      "api/tracker",
      "api/tracker-stores",
      "api/event-brokers",
      "api/lock-stores",
      "api/training-data-importers",
      "api/core-featurization",
      "api/tensorflow_usage",
      "migration-guide",
      "changelog",
    ],
    "Migrate from (beta)": [
      "migrate-from/google-dialogflow-to-rasa",
      "migrate-from/facebook-wit-ai-to-rasa",
      "migrate-from/microsoft-luis-to-rasa",
      "migrate-from/ibm-watson-to-rasa",
    ],
    "Reference": [
      "glossary"
    ]
  },
};
