name: Debug tracker store test containers
description: Encapsulates steps for tracker store test debugging

inputs:
  COMPOSE_FILE_PATH:
    description: 'tracker store tests docker compose path'
    required: true
  CONTAINER_NAME:
    description: 'Container name to check'
    required: true

runs:
  using: 'composite'
  steps:
  - name: List containers
    run: sudo docker ps -a
    shell: bash

  - name: Check container logs
    env:
      COMPOSE_FILE_PATH: ${{ inputs.COMPOSE_FILE_PATH }}
      CONTAINER_NAME: ${{ inputs.CONTAINER_NAME }}
    run: |
      docker compose -f "$COMPOSE_FILE_PATH" logs "$CONTAINER_NAME"
    shell: bash
