
Have questions or feedback?
---------------------------
   
We have a very active support community on `Rasa Community Forum <https://forum.rasa.com>`_ 
that is happy to help you with your questions. If you have any feedback for us or a specific 
suggestion for improving the docs, feel free to share it by creating an issue on Rasa NLU 
`GitHub repository <https://github.com/RasaHQ/rasa_nlu>`_. 