name: Force Stop Deployment
description: "Stop current deployment"
inputs:
  STACK_NAME:
    description: "Stack name of the current deployment"
    required: true
  BASE_STACK:
    description: "Stack name of the base deployment"
    required: true
  PULUMI_ACCESS_TOKEN:
    description: "Pulumi access token"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install kubectl
      uses: azure/setup-kubectl@v4.0.0

    - name: Force stop current deployment
      shell: bash
      run: |
        # Cancel current Pulumi deployment
        cd infrastructure/eks-helm
        pulumi login
        pulumi stack select rasa/${BASE_STACK}/${STACK_NAME}
        pulumi cancel --yes
      env:
        PULUMI_ACCESS_TOKEN: ${{ inputs.PULUMI_ACCESS_TOKEN }}
        BASE_STACK: ${{ inputs.BASE_STACK }}
        STACK_NAME: ${{ inputs.STACK_NAME }}
