DOCS_BASE_URL = "https://rasa.com/docs/rasa"
DOCS_URL_TRAINING_DATA_NLU = DOCS_BASE_URL + "/nlu/training-data-format/"
INTENT_MESSAGE_PREFIX = "/"
PACKAGE_NAME = "rasa"
SCHEMA_UTILS_FILE = "shared/utils/schemas.yml"
SCHEMA_EXTENSIONS_FILE = "shared/utils/pykwalify_extensions.py"
LATEST_TRAINING_DATA_FORMAT_VERSION = "2.0"
