name: rasa-pro-eks-base
description: Base infrastructure for deploying Rasa Pro helm charts on each PR
runtime:
  name: python
  options:
    toolchain: pip
    virtualenv: venv
config:
  pulumi:tags:
    value:
      pulumi:template: aws-python
