x-license: &license
  RASA_PRO_LICENSE: ${RASA_PRO_LICENSE}
  OPENAI_API_KEY: ${OPENAI_API_KEY}

configs:
  endpoints-http.yml:
    content: |
      action_endpoint:
        url: "http://rasa-http-action-server:5055/webhook"
  endpoints-https.yml:
    content: |
      action_endpoint:
        url: "https://rasa-https-action-server:5055/webhook"
        cafile: "/certs/ca.pem"
  endpoints-grpc.yml:
    content: |
      action_endpoint:
        url: "grpc://rasa-grpc-action-server:5055"
  endpoints-grpc-tls.yml:
    content: |
      action_endpoint:
        url: "grpc://rasa-grpc-tls-action-server:5055"
        cafile: "/certs/ca.pem"
  action-server-endpoints.yml:
    content: |
        empty: "empty"

services:
  rasa-pro-grpc:
    image: ${RASA_REPOSITORY}:${RASA_IMAGE_TAG}
    container_name: rasa-pro-grpc
    volumes:
      - "${BOT_PATH}:/app"
    configs:
      - source: endpoints-grpc.yml
        target: /endpoints-grpc.yml
    entrypoint: ""
    command: rasa run -p ${RASA_PORT} --enable-api --endpoints /endpoints-grpc.yml
    networks: [ 'rasa-pro-network' ]
    ports:
      - "${RASA_GRPC_PORT}:${RASA_PORT}"
    environment:
      <<: *license
    healthcheck:
      test: curl localhost:${RASA_PORT} || exit 1
      interval: 10s
      retries: 10
      start_period: 15s
      timeout: 10s
    user: ${USER_ID}
    depends_on:
      rasa-grpc-action-server-healthcheck:
        condition: service_healthy

  rasa-grpc-action-server:
    image: ${RASA_SDK_REPOSITORY}:${RASA_SDK_IMAGE_TAG}
    container_name: rasa-grpc-action-server
    volumes:
      - "${BOT_PATH}/actions:/app/actions"
    configs:
      - source: action-server-endpoints.yml
        target: /app/endpoints.yml
    networks: [ 'rasa-pro-network' ]
    entrypoint: "python -m rasa_sdk"
    command: --actions actions -p 5055 --grpc
    environment:
      <<: *license
    user: ${USER_ID}

# We use a trick with sleep command to make the container keep running
# while it keeps checking the health of the action server
  rasa-grpc-action-server-healthcheck:
    image: public.ecr.aws/f7b7r5o7/tools/grpc_health_probe:latest
    container_name: rasa-grpc-action-server-healthcheck
    # This is a trick to make the container keep running
    entrypoint: ["bash", "-c"]
    command: ["sleep 60"]
    networks: [ 'rasa-pro-network' ]
    depends_on:
      - rasa-grpc-action-server
    # This will check the health of the action server
    healthcheck:
      test: ["CMD-SHELL", "grpc_health_probe -addr=rasa-grpc-action-server:5055 -rpc-timeout 15s -connect-timeout 2s -gzip"]
      interval: 5s
      retries: 10
      timeout: 10s


  rasa-pro-grpc-tls:
    image: ${RASA_REPOSITORY}:${RASA_IMAGE_TAG}
    container_name: rasa-pro-grpc-tls
    volumes:
      - "${BOT_PATH}:/app"
      - "./certs/ca.pem:/certs/ca.pem"
    configs:
      - source: endpoints-grpc-tls.yml
        target: /endpoints-grpc-tls.yml
    entrypoint: ""
    command: rasa run -p ${RASA_PORT} --enable-api --endpoints /endpoints-grpc-tls.yml
    networks: [ 'rasa-pro-network' ]
    ports:
      - "${RASA_GRPC_TLS_PORT}:${RASA_PORT}"
    environment:
      <<: *license
    healthcheck:
      test: curl localhost:${RASA_PORT} || exit 1
      interval: 10s
      retries: 10
      start_period: 15s
      timeout: 10s
    user: ${USER_ID}
    depends_on:
      rasa-grpc-tls-action-server-healthcheck:
        condition: service_healthy

  rasa-grpc-tls-action-server:
    image: ${RASA_SDK_REPOSITORY}:${RASA_SDK_IMAGE_TAG}
    container_name: rasa-grpc-tls-action-server
    volumes:
      - "./certs/server.pem:/certs/server.pem"
      - "./certs/server-key.pem:/certs/server-key.pem"
      - "${BOT_PATH}/actions:/app/actions"
    configs:
      - source: action-server-endpoints.yml
        target: /app/endpoints.yml
    networks: [ 'rasa-pro-network' ]
    entrypoint: "python -m rasa_sdk"
    command: --actions actions -p 5055 --grpc --ssl-certificate /certs/server.pem --ssl-keyfile /certs/server-key.pem
    environment:
      <<: *license
    user: ${USER_ID}


# We use a trick with sleep command to make the container keep running
# while it keeps checking the health of the action server
  rasa-grpc-tls-action-server-healthcheck:
    image: public.ecr.aws/f7b7r5o7/tools/grpc_health_probe:latest
    container_name: rasa-grpc-tls-action-server-healthcheck
    # This is a trick to make the container keep running
    entrypoint: ["bash", "-c"]
    command: ["sleep 60"]
    networks: [ 'rasa-pro-network' ]
    depends_on:
      - rasa-grpc-tls-action-server
    # This will check the health of the action server
    healthcheck:
      test: ["CMD-SHELL", "grpc_health_probe -addr=rasa-grpc-tls-action-server:5055 -rpc-timeout 15s -connect-timeout 2s -gzip -tls -tls-no-verify"]
      interval: 5s
      retries: 10
      timeout: 10s


  rasa-pro-http:
    image: ${RASA_REPOSITORY}:${RASA_IMAGE_TAG}
    volumes:
      - "${BOT_PATH}:/app"
    configs:
      - source: endpoints-http.yml
        target: /endpoints-http.yml
    entrypoint: ""
    command: rasa run -p ${RASA_PORT} --enable-api --endpoints /endpoints-http.yml
    networks: [ 'rasa-pro-network' ]
    ports:
      - "${RASA_HTTP_PORT}:${RASA_PORT}"
    environment:
      <<: *license
    healthcheck:
      test: curl localhost:${RASA_PORT} || exit 1
      interval: 10s
      retries: 10
      start_period: 15s
      timeout: 10s
    user: ${USER_ID}
    depends_on:
      rasa-http-action-server-healthcheck:
        condition: service_healthy

  rasa-http-action-server:
    image: ${RASA_SDK_REPOSITORY}:${RASA_SDK_IMAGE_TAG}
    container_name: rasa-http-action-server
    volumes:
      - "${BOT_PATH}/actions:/app/actions"
    configs:
      - source: action-server-endpoints.yml
        target: /app/endpoints.yml
    networks: [ 'rasa-pro-network' ]
    entrypoint: "python -m rasa_sdk"
    command: --actions actions -p 5055
    environment:
      <<: *license
    user: ${USER_ID}

# We use a trick with sleep command to make the container keep running
# while it keeps checking the health of the action server
  rasa-http-action-server-healthcheck:
    image: curlimages/curl:8.12.1
    container_name: rasa-http-action-server-healthcheck
    entrypoint: ["sh", "-c"]
    command: ["sleep 60"]
    networks: [ 'rasa-pro-network' ]
    depends_on:
      - rasa-http-action-server
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://rasa-http-action-server:5055/health"]
      interval: 5s
      retries: 10
      timeout: 10s


  rasa-pro-https:
    image: ${RASA_REPOSITORY}:${RASA_IMAGE_TAG}
    volumes:
      - "${BOT_PATH}:/app"
      - "./certs/ca.pem:/certs/ca.pem"
    configs:
      - source: endpoints-https.yml
        target: /endpoints-https.yml
    entrypoint: ""
    command: rasa run -p ${RASA_PORT} --enable-api --endpoints /endpoints-https.yml
    networks: [ 'rasa-pro-network' ]
    ports:
      - "${RASA_HTTPS_PORT}:${RASA_PORT}"
    environment:
      <<: *license
    healthcheck:
      test: curl localhost:${RASA_PORT} || exit 1
      interval: 10s
      retries: 10
      start_period: 15s
      timeout: 10s
    user: ${USER_ID}
    depends_on:
      rasa-https-action-server-healthcheck:
        condition: service_healthy

  rasa-https-action-server:
    image: ${RASA_SDK_REPOSITORY}:${RASA_SDK_IMAGE_TAG}
    container_name: rasa-https-action-server
    volumes:
      - "./certs/server.pem:/certs/server.pem"
      - "./certs/server-key.pem:/certs/server-key.pem"
      - "${BOT_PATH}/actions:/app/actions"
    configs:
      - source: action-server-endpoints.yml
        target: /app/endpoints.yml
    networks: [ 'rasa-pro-network' ]
    entrypoint: "python -m rasa_sdk"
    command: --actions actions -p 5055 --ssl-certificate /certs/server.pem --ssl-keyfile /certs/server-key.pem
    environment:
      <<: *license
    user: ${USER_ID}

# We use a trick with sleep command to make the container keep running
# while it keeps checking the health of the action server
  rasa-https-action-server-healthcheck:
    image: curlimages/curl:8.12.1
    container_name: rasa-https-action-server-healthcheck
    volumes:
      - "./certs/ca.pem:/certs/ca.pem"
    entrypoint: ["sh", "-c"]
    command: ["sleep 60"]
    networks: [ 'rasa-pro-network' ]
    depends_on:
      - rasa-https-action-server
    healthcheck:
      test: ["CMD", "curl", "-skf", "https://rasa-https-action-server:5055/health"]
      interval: 5s
      retries: 10
      timeout: 10s

networks: { rasa-pro-network: { name: rasa-pro-network } }
