name: Capture Rasa Pro installation time

on:
  pull_request:

jobs:
  check_poetry_lock:
    name: Detect changes in poetry.lock
    runs-on: ubuntu-24.04
    outputs:
      lock_file: ${{ steps.filter.outputs.lock_file }}
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - id: filter
        name: Check for changes in poetry.lock
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50  #v2.11.1
        with:
          filters: .github/change_filters.yml

  trigger_installation_workflow:
    needs: check_poetry_lock
    name: Trigger installation workflow
    runs-on: ubuntu-24.04
    if: ${{ needs.check_poetry_lock.outputs.lock_file == 'true' }}
    steps:
      - name: Trigger installation workflow
        uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0  #v3.0.0
        with:
          event-type: trigger-installation-performance
          client-payload: '{"branch": "${{ github.head_ref }}", "pr_number": "${{ github.event.pull_request.number }}"}'
          token: ${{ secrets.GITHUB_TOKEN }}
