name: Capture Rasa Pro installation time

on:
  pull_request:

jobs:
  check_poetry_lock:
    name: Detect changes in poetry.lock
    runs-on: ubuntu-22.04
    outputs:
      lock_file: ${{ steps.filter.outputs.lock_file }}
    steps:
      - name: Check out code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - id: filter
        name: Check for changes in poetry.lock
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50  #v2.11.1
        with:
          filters: .github/change_filters.yml

  trigger_installation_workflow:
    needs: check_poetry_lock
    name: Trigger installation workflow
    runs-on: ubuntu-22.04
    if: ${{ needs.check_poetry_lock.outputs.lock_file == 'true' }}
    steps:
      - name: Trigger installation workflow
        uses: peter-evans/repository-dispatch@bf47d102fdb849e755b0b0023ea3e81a44b6f570  #v2.1.2
        with:
          event-type: trigger-installation-performance
          client-payload: '{"branch": "${{ github.head_ref }}", "pr_number": "${{ github.event.pull_request.number }}"}'
          token: ${{ secrets.GITHUB_TOKEN }}
