name: Continuous Integration

on:
  workflow_call:
    inputs:
      # CI only runs tests for the lowest supported Python version
      python-versions:
        type: string
        default: '["3.10"]'
        required: false
        description: "Python versions to run the tests on."
      # Code Quality checks are enabled by default
      run_code_quality:
        type: string
        required: false
        default: 'true'
        description: "Whether to run the Code Quality checks."
      # Only run partial workflow steps
      full_ci_mode:
        type: string
        required: false
        default: 'true'
        description: "Whether to run all the CI checks."

concurrency:
  group: continous-integration-${{ github.ref }} # branch or tag name
  cancel-in-progress: true

# SECRETS
# - RASA_TELEMETRY_WRITE_KEY: key to write to segment. Used to report telemetry.
#                                 The key will be added to the distributions
#                      created at https://sentry.io/settings/account/api/auth-tokens/
# - RASA_PRO_LICENSE: license key for Rasa Pro. Used to run tests for Rasa Pro.
# - INTEGRATION_TESTS_STUDIO_LICENSE: license key for Studio. Used in integration tests. Expires in 2034.
# - INTEGRATION_TESTS_PRO_LICENSE: license key for Pro. Used in integration tests. Expires in 2034.

env:
  AWS_REGION: eu-west-1
  RASA_PRO_DEV_REPOSITORY: 329710836760.dkr.ecr.eu-west-1.amazonaws.com/rasa/rasa-private-dev
  RASA_SDK_DEV_REPOSITORY: 329710836760.dkr.ecr.eu-west-1.amazonaws.com/rasa/rasa-sdk-dev
  RASA_PRO_HELM_REPO: oci://europe-west3-docker.pkg.dev/rasa-releases/helm-charts/rasa
  RASA_PRO_HELM_VERSION: 1.2.0
  DEFAULT_PYTHON_VERSION: "3.10"
  NODE_VERSION_INSPECTOR_BUILD: 20
  SONAR_ORGANIZATION: rasahq
  SONAR_PROJECT_KEY: RasaHQ_rasa-private
  TEMPLATES: "telco finance basic"
  POSTGRES_HOST: rasa-pro-integration-tests-db.cvgblmmqghrx.eu-west-1.rds.amazonaws.com
  POSTGRES_PORT: '5432'
  POSTGRES_USER: integration_tests_user
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD_AWS }}
  POSTGRES_DB: integrationtestsdb

permissions:
  checks: write
  id-token: write
  pull-requests: write
  contents: read
  issues: read

jobs:
  check-poetry-lock-is-up-to-date:
    name: check poetry lock is up to date
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Prepare the job for integration tests
        uses: ./.github/actions/test-prerequisites
        with:
          PYTHON_VERSION: ${{ env.DEFAULT_PYTHON_VERSION }}
          POETRY_CACHE_VERSION: ${{ secrets.POETRY_CACHE_VERSION }}

      - name: Check poetry lock
        run: |
          poetry check
          if grep 'Error: pyproject.toml changed significantly since poetry.lock was last generated' .output; then exit 1; fi

  check-for-merge-conflicts:
    name: Check for merge conflicts
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Merge Conflict finder
        run: |
          ./scripts/conflict-finder.sh
        shell: bash

  quality:
    name: Code Quality
    runs-on: ubuntu-24.04
    if: ${{ inputs.run_code_quality != 'false' }}

    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Free up disk-space
        uses: RasaHQ/rasa-private/.github/actions/free-disk-space@fe77d93db58f0412e2162fdaa34e2ed596f8536b

      - name: Prepare the job
        uses: ./.github/actions/test-prerequisites
        with:
          PYTHON_VERSION: ${{ env.DEFAULT_PYTHON_VERSION }}
          POETRY_CACHE_VERSION: ${{ secrets.POETRY_CACHE_VERSION }}

      - name: Install Dependencies 📦
        # Poetry intermittently fails to install dependency if it is not PEP 517 compliant
        # This is a workaround for that issue
        run: |
          sudo apt-get -y install libpq-dev
          make install-full

      - name: Checkout target branch to be able to diff on PR
        if: github.event_name == 'pull_request'
        run: |
          git fetch origin ${{ github.base_ref }}
          echo "DOCSTRING_DIFF_BRANCH=origin/${{ github.base_ref }}" >> $GITHUB_ENV

      - name: Checkout target branch to be able to diff on merge queue
        if: github.event_name == 'merge_group'
        run: |
          git fetch origin ${{ github.event.merge_group.base_sha }}
          echo "DOCSTRING_DIFF_BRANCH=${{ github.event.merge_group.base_sha }}" >> $GITHUB_ENV

      - name: Fetch current branch
        run: |
          # Fetch entire history for current branch so that `make lint-docstrings`
          # can calculate the proper diff between the branches
          git fetch --unshallow origin "${{ github.ref }}"

      - name: Add github workflow problem matchers
        run: |
          echo "::add-matcher::.github/matchers/flake8-error-matcher.json"

      - name: Lint Code 🎎
        run: |
          # If it's not a pull request, $DOCSTRING_DIFF_BRANCH is unset.
          # This will result in an empty diff, which effictively means that
          # make lint-docstrings will be skipped for other events than `pull_request`
          make lint BRANCH=$DOCSTRING_DIFF_BRANCH

      - name: Check Types 📚
        run: make types

      - name: Lint Changelog Filenames 📝
        if: github.event_name == 'pull_request' || github.event_name == 'merge_group'
        run: make lint-changelog

  train-templates-dev:
    name: Train Project Templates for Dev
    runs-on: ubuntu-24.04
    if: ${{ inputs.full_ci_mode != 'false' }}
    outputs:
      tag_version: ${{ steps.set-tag.outputs.tag_version }}
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set image tag
        id: set-tag
        uses: ./.github/actions/set-tag-version

      - name: Train templates
        uses: ./.github/actions/train-templates
        with:
          tag_version: ${{ steps.set-tag.outputs.tag_version }}
          templates: ${{ env.TEMPLATES }}
          rasa_pro_license: ${{ secrets.RASA_PRO_LICENSE }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}

  rasa-init-sanity-check:
    runs-on: ubuntu-24.04
    if: ${{ inputs.full_ci_mode != 'false' }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
        template:
          - default
          - tutorial
          - basic
          - finance
          - telco
        install-group:
          - default
          - nlu
          - channels
          - full
        install-method:
          - poetry
          - pip
          - uv
        exclude:
          - python-version: "3.9"
            template: tutorial
          - python-version: "3.9"
            template: basic
          - python-version: "3.9"
            template: finance
          - python-version: "3.9"
            template: telco
          - python-version: "3.9"
            install-method: pip
          - python-version: "3.9"
            install-method: uv
    name: rasa init Py${{ matrix.python-version }} ${{ matrix.install-group }}-group (with ${{ matrix.install-method }} install) ${{ matrix.template }}-template
    env:
      RASA_INIT_TEST_DIRECTORY: test-rasa-init
    steps:
        - name: Check out code
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        - name: Free up disk-space
          if: ${{ matrix.install-group == 'full' || matrix.install-group == 'nlu' }}
          uses: RasaHQ/rasa-private/.github/actions/free-disk-space@fe77d93db58f0412e2162fdaa34e2ed596f8536b
        - name: Setup Python ${{ matrix.python-version }} and install rasa-pro (via ${{ matrix.install-method }}) with default installation
          if: ${{ matrix.python-version != '3.9' && matrix.install-group == 'default' }}
          uses: ./.github/actions/setup-python-env
          with:
            PYTHON_VERSION: ${{ matrix.python-version }}
            MATRIX_JOB: ${{ matrix.install-group }}-${{ matrix.install-method }}-${{ matrix.template }}
            RASA_DEFAULT_INSTALLATION_ONLY: "true"
            DEPENDENCIES_AND_PACKAGE_MANAGEMENT_TOOL: ${{ matrix.install-method }}
        - name: Setup Python ${{ matrix.python-version }} and install rasa-pro (via ${{ matrix.install-method }}) with ${{ matrix.install-group }} group
          if: ${{ matrix.python-version != '3.9' && matrix.install-group != 'default'  }}
          uses: ./.github/actions/setup-python-env
          with:
            PYTHON_VERSION: ${{ matrix.python-version }}
            MATRIX_JOB: ${{ matrix.install-group }}-${{ matrix.install-method }}-${{ matrix.template }}
            OPTIONAL_GROUP_TO_INSTALL: ${{ matrix.install-group }}
            RASA_DEFAULT_INSTALLATION_ONLY: "false"
            DEPENDENCIES_AND_PACKAGE_MANAGEMENT_TOOL: ${{ matrix.install-method }}
        - name: Set up Python 3.9
          if: ${{ matrix.python-version == '3.9' }}
          uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
          with:
            python-version: ${{ matrix.python-version }}
        - name: Read Poetry Version 🔢
          if: ${{ matrix.python-version == '3.9' }}
          run: |
            echo "POETRY_VERSION=$(scripts/poetry-version.sh)" >> $GITHUB_ENV
        - name: Install Poetry ${{ env.POETRY_VERSION }}
          if: ${{ matrix.python-version == '3.9' }}
          uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a # v1.4.1
          with:
            version: ${{ env.POETRY_VERSION }}
            virtualenvs-create: true
            virtualenvs-in-project: true
            installer-parallel: true
        - name: Check error warning on Rasa install if using Python 3.9
          if: ${{ matrix.python-version == '3.9' }}
          run: |
            make install > error-log 2>&1 || true
            cat error-log
            grep 'Current Python version (3.9.23) is not allowed by the project (>=3.10.0,<3.14)' error-log
        - name: Make empty directory for `rasa init`
          run: mkdir "${RASA_INIT_TEST_DIRECTORY}"
        - name: Sanity check of `rasa init`
          if: ${{ matrix.python-version != '3.9' }}
          working-directory: ${{ env.RASA_INIT_TEST_DIRECTORY }}
          env:
            LLM_API_HEALTH_CHECK: true
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
            RASA_PRO_LICENSE: ${{ secrets.RASA_PRO_LICENSE }}
            TEMPLATE: ${{ matrix.template }}
          run: rasa init --template "${TEMPLATE}" --no-prompt --debug

  rasa-private-dev-docker-image:
    name: rasa-private dev docker image
    runs-on: ubuntu-24.04
    if: ${{ inputs.full_ci_mode != 'false' }}
    needs: [train-templates-dev]
    outputs:
      rasa_image_tag: ${{ steps.set-tag.outputs.rasa_image_tag }}
      stack_name: ${{ steps.set-tag.outputs.stack_name }}
    env:
      PLATFORM: linux/amd64

    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Read Poetry Version 🔢
        run: |
          echo "POETRY_VERSION=$(scripts/poetry-version.sh)" >> $GITHUB_ENV
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 #v4.1.0
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 #v2.0.1

      - name: Set image tag
        id: set-tag
        run: |
          TAG_VERSION="${{ needs.train-templates-dev.outputs.tag_version }}"
          echo "RASA_IMAGE_TAG=${TAG_VERSION}" >> $GITHUB_ENV
          echo "rasa_image_tag=${TAG_VERSION}" >> $GITHUB_OUTPUT
          if [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
            echo "stack_name=pr-${{ github.event.number }}" >> $GITHUB_OUTPUT
          else
            echo "stack_name=$(echo "${GITHUB_REF##*/}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
          fi

      - name: Prepare template caches
        uses: ./.github/actions/prepare-template-caches
        with:
          tag_version: ${{ needs.train-templates-dev.outputs.tag_version }}
          templates: ${{ env.TEMPLATES }}

      - name: Build Rasa Private Dev Docker Image
        run: |
          POETRY_VERSION=$POETRY_VERSION \
          PLATFORM=${{ env.PLATFORM }} \
          RASA_REPOSITORY=${{ env.RASA_PRO_DEV_REPOSITORY }} \
          RASA_IMAGE_TAG=${{ env.RASA_IMAGE_TAG }} \
          make build-docker

      - name: Tag, and push image to Amazon ECR
        run: |
          docker push ${{ env.RASA_PRO_DEV_REPOSITORY }}:${{ env.RASA_IMAGE_TAG }}

      # Leverage GitHub Actions artifact upload/download to share Docker images between jobs,
      # reducing dependency on ECR and minimizing AWS costs
      - name: Save docker image
        run: docker save ${{ env.RASA_PRO_DEV_REPOSITORY }}:${{ env.RASA_IMAGE_TAG }} | gzip > image-${{ env.RASA_IMAGE_TAG }}.tar.gz

      - name: Upload image as artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: docker-image-${{ env.RASA_IMAGE_TAG }}.tar.gz
          path: image-${{ env.RASA_IMAGE_TAG }}.tar.gz
          retention-days: 5

  # This job is stable but still a work in progress.
  # It is not a blocker for merging and will eventually be moved to a separate workflow.
  # Skip this job from merge queue, Backport PRs and Dependabot PRs
  rasa-private-dev-train-the-model:
    name: Train the model and upload to S3
    if: github.event_name != 'merge_group' && !startsWith(github.event.pull_request.title, 'Backport') && github.actor != 'dependabot[bot]' &&  inputs.full_ci_mode != 'false'
    needs: rasa-private-dev-docker-image
    runs-on: ubuntu-24.04

    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Download image artifact
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e #v4.2.1
        with:
          name: docker-image-${{ needs.rasa-private-dev-docker-image.outputs.rasa_image_tag }}.tar.gz

      - name: Load Docker image
        run: |
          gunzip -c image-${{ needs.rasa-private-dev-docker-image.outputs.rasa_image_tag }}.tar.gz | docker load

      - name: Rasa Train
        run: |
          make train-rds-tracker-bot
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          RASA_PRO_LICENSE: ${{ secrets.RASA_PRO_LICENSE }}
          RASA_REPOSITORY: ${{ env.RASA_PRO_DEV_REPOSITORY }}
          RASA_IMAGE_TAG: ${{ needs.rasa-private-dev-docker-image.outputs.rasa_image_tag }}
          MODEL_NAME: model-${{ needs.rasa-private-dev-docker-image.outputs.rasa_image_tag }}.tar.gz
          DB_HOST: ${{ env.POSTGRES_HOST }} # required if tracker-store-type is sql
          DB_PORT: ${{ env.POSTGRES_PORT }} # required if tracker-store-type is sql
          DB_USER: ${{ env.POSTGRES_USER }} # required if tracker-store-type is sql
          DB_PASS: ${{ env.POSTGRES_PASSWORD }} # required if tracker-store-type is sql
          DB_NAME: ${{ env.POSTGRES_DB }} # required if tracker-store-type is sql


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 #v4.1.0
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload the model to S3
        run: |
          aws s3 cp $MODEL_FILE_PATH s3://rasa-pro-ci-trained-models/ \
          --region eu-west-1 \
          --endpoint-url https://s3.eu-west-1.amazonaws.com
        env:
          MODEL_FILE_PATH: tests_deployment/integration_tests_tracker_stores/sql_tracker_store/calm-demo-bot/models/model-${{ needs.rasa-private-dev-docker-image.outputs.rasa_image_tag }}.tar.gz

  # This job is stable but still a work in progress.
  # It is not a blocker for merging and will eventually be moved to a separate workflow.
  # Skip this job from merge queue, Backport PRs and Dependabot PRs
  deploy-rasa-private-helm-chart:
    name: Deploy rasa private helm chart
    if: github.event_name != 'merge_group' && !startsWith(github.event.pull_request.title, 'Backport') && github.actor != 'dependabot[bot]' &&  inputs.full_ci_mode != 'false'
    runs-on: ubuntu-24.04
    needs: [rasa-private-dev-docker-image, rasa-private-dev-train-the-model]

    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python 3.10 🐍
        id: setup-python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: ${{ env.DEFAULT_PYTHON_VERSION }}

      - name: Deploy Rasa Pro Dev Helm Chart
        uses: ./.github/actions/setup-build-for-helm-deploy
        with:
          python-version: ${{ env.DEFAULT_PYTHON_VERSION }}
          aws-region: ${{ env.AWS_REGION }}
          aws-assume-role-session-token: ${{ secrets.AWS_ASSUME_ROLE_SESSION_TOKEN }}
          rasa-pro-helm-repo: ${{ env.RASA_PRO_HELM_REPO }}
          rasa-pro-helm-version: ${{ env.RASA_PRO_HELM_VERSION }}
          rasa-pro-version: ${{ needs.rasa-private-dev-docker-image.outputs.rasa_image_tag }}
          rasa-pro-dev-repository: ${{ env.RASA_PRO_DEV_REPOSITORY }}
          helm-deploy-rasa-pro-license: ${{ secrets.HELM_DEPLOY_RASA_PRO_LICENSE }}
          helm-deploy-openai-api-key: ${{ secrets.HELM_DEPLOY_OPENAI_API_KEY }}
          helm-deploy-certificate-arn: ${{ secrets.HELM_DEPLOY_CERTIFICATE_ARN }}
          helm-deploy-hosted-zone-id: ${{ secrets.HELM_DEPLOY_HOSTED_ZONE_ID }}
          helm-deploy-pulumi-access-token: ${{ secrets.HELM_DEPLOY_PULUMI_ACCESS_TOKEN }}
          model-file-name: model-${{ needs.rasa-private-dev-docker-image.outputs.rasa_image_tag }}.tar.gz
          aws-model-s3-bucket: rasa-pro-ci-trained-models
          aws-model-s3-endpoint-url: https://s3.eu-west-1.amazonaws.com
          aws-model-s3-access-key-id: ${{ secrets.AWS_MODEL_S3_ACCESS_KEY_ID }}
          aws-model-s3-secret-access-key: ${{ secrets.AWS_MODEL_S3_SECRET_ACCESS_KEY }}
          stack-name: ${{ needs.rasa-private-dev-docker-image.outputs.stack_name }}
          # Use the image tag as project name and PR name to distinguish deployments
          project-name: rasa-pro-${{ needs.rasa-private-dev-docker-image.outputs.stack_name }}
          pr-name: ${{ needs.rasa-private-dev-docker-image.outputs.stack_name }}
          domain-name: rasapro.rasa-dev.io
          postgres-host: ${{ env.POSTGRES_HOST }} # required if tracker-store-type is sql
          postgres-port: ${{ env.POSTGRES_PORT }} # required if tracker-store-type is sql
          postgres-user: ${{ env.POSTGRES_USER }} # required if tracker-store-type is sql
          postgres-password: ${{ env.POSTGRES_PASSWORD }} # required if tracker-store-type is sql
          postgres-db: ${{ env.POSTGRES_DB }} # required if tracker-store-type is sql


  # This job is being moved here from the pr-cleanup.yml workflow, to reduce AWS costs and save resources.
  # Skip this job from merge queue, Backport PRs and Dependabot PRs
  pulumi-destroy:
    if: always() && github.event_name != 'merge_group' && !startsWith(github.event.pull_request.title, 'Backport') && github.actor != 'dependabot[bot]' &&  inputs.full_ci_mode != 'false'
    name: Destroy pulumi resources
    needs: deploy-rasa-private-helm-chart
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set stack name
        run: |
          if [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
            echo "STACK_NAME=pr-${{ github.event.number }}" >> $GITHUB_ENV
          else
            echo "STACK_NAME=$(echo "${GITHUB_REF##*/}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@8c3f20df09ac63af7b3ae3d7c91f105f857d8497 # v3.0.1
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up kubeconfig
        run: |
          aws eks update-kubeconfig --name rasa-pro-cluster --region ${{ env.AWS_REGION }}

      - uses: pulumi/actions@ae8c5623fbcf1b4781618a60e69d423f9a6b9c92 #v5.1.1
      - name: Destroy resources and remove the stack
        run: |
          pulumi destroy -s rasa/rasa-pro-eks-helm/${{ env.STACK_NAME }} --yes
          pulumi stack rm rasa/rasa-pro-eks-helm/${{ env.STACK_NAME }} --yes
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.HELM_DEPLOY_PULUMI_ACCESS_TOKEN }}

  check_inspector_build:
    name: Check Inspector Build
    runs-on: ubuntu-24.04
    if: ${{ inputs.full_ci_mode != 'false' }}
    defaults:
      run:
        shell: bash
        working-directory: rasa/core/channels/inspector

    steps:
    - name: Check out code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 #v4.4.0
      with:
        node-version: ${{ env.NODE_VERSION_INSPECTOR_BUILD }}

    - name: Cache node modules
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      id: yarn-cache
      with:
        path: "**/inspector/node_modules"
        key: ${{ runner.os }}-modules-${{ hashFiles('**/inspector/yarn.lock') }}

    - name: Install dependencies
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: |
        yarn install --frozen-lockfile

    - name: Build Inspector
      run: |
        yarn build

    - name: Store build output
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
      with:
        name: inspector-build
        path: rasa/core/channels/inspector/dist

    - name: Compare build output
      run: |
        if git diff --quiet -- dist; then
          echo "No changes in the Inspector build output."
        else
          echo "Detected changes in the Inspector build output. Please build the Inspector and commit the contents of rasa/core/channels/inspector/dist/ ."
          exit 1
        fi

  tracing-integration-test:
    name: Tracing Integration Tests
    if: ${{ inputs.full_ci_mode != 'false' }}
    needs: rasa-private-dev-docker-image
    runs-on: ubuntu-24.04-4core
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Prepare the job for integration tests
        uses: ./.github/actions/test-prerequisites
        with:
            PYTHON_VERSION: ${{ env.DEFAULT_PYTHON_VERSION }}
            POETRY_CACHE_VERSION: ${{ secrets.POETRY_CACHE_VERSION }}

      - name: Download image artifact
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e #v4.2.1
        with:
          name: docker-image-${{ needs.rasa-private-dev-docker-image.outputs.rasa_image_tag }}.tar.gz

      - name: Load Docker image
        run: |
          gunzip -c image-${{ needs.rasa-private-dev-docker-image.outputs.rasa_image_tag }}.tar.gz | docker load

      - name: Pull rasa-sdk dev image
        uses: ./.github/actions/pull-from-ecr
        with:
          AWS_REGION: ${{ env.AWS_REGION }}
          AWS_ARN_ROLE_TO_ASSUME: ${{ secrets.AWS_ASSUME_ROLE_SESSION_TOKEN }}
          IMAGE_TAG: latest
          REPOSITORY: ${{ env.RASA_SDK_DEV_REPOSITORY }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 #v4.1.0
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Tracing integration testing - Run docker containers
        env:
          RASA_REPOSITORY: ${{ env.RASA_PRO_DEV_REPOSITORY }}
          RASA_IMAGE_TAG: ${{ needs.rasa-private-dev-docker-image.outputs.rasa_image_tag }}
          RASA_PRO_LICENSE: ${{ secrets.RASA_PRO_LICENSE }}
          RASA_SDK_REPOSITORY: ${{ env.RASA_SDK_DEV_REPOSITORY }}
        run: |
          make run-tracing-integration-containers

      - name: Tracing integration testing - Test Code with Services 🩺
        env:
          PYTHONIOENCODING: "utf-8"
          RASA_TELEMETRY_WRITE_KEY: ${{ secrets.SEGMENT_WRITE_DEV_KEY }}
        run: |
          make test-tracing-integration

      - name: Show container logs
        if: always()
        uses: ./.github/actions/debug-tracing-tests
        with:
          COMPOSE_FILE_PATH: tests_deployment/integration_tests_tracing_deployment/docker-compose.yml

      - name: Tracing integration testing - Stop docker containers
        if: always()
        run: |
          make stop-tracing-integration-containers

      - name: Save Test Results
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: Tracing Integration Test Results
          path: integration-results-tracing.xml

  metric-integration-test:
    name: Metric Integration Tests
    if: ${{ inputs.full_ci_mode != 'false' }}
    needs: rasa-private-dev-docker-image
    runs-on: ubuntu-24.04-4core
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Prepare the job for integration tests
        uses: ./.github/actions/test-prerequisites
        with:
            PYTHON_VERSION: ${{ env.DEFAULT_PYTHON_VERSION }}
            POETRY_CACHE_VERSION: ${{ secrets.POETRY_CACHE_VERSION }}

      - name: Download image artifact
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e #v4.2.1
        with:
          name: docker-image-${{ needs.rasa-private-dev-docker-image.outputs.rasa_image_tag }}.tar.gz

      - name: Load Docker image
        run: |
          gunzip -c image-${{ needs.rasa-private-dev-docker-image.outputs.rasa_image_tag }}.tar.gz | docker load

      - name: Metric Integration Testing - Run docker containers
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          RASA_REPOSITORY: ${{ env.RASA_PRO_DEV_REPOSITORY }}
          RASA_IMAGE_TAG: ${{ needs.rasa-private-dev-docker-image.outputs.rasa_image_tag }}
          RASA_PRO_LICENSE: ${{ secrets.RASA_PRO_LICENSE }}
          RASA_SDK_REPOSITORY: rasa/rasa-sdk
          RASA_SDK_IMAGE_TAG: latest
        run: |
          make run-metrics-integration-containers

      - name: Metric Integration Testing -  Test Code with Services 🩺
        env:
          PYTHONIOENCODING: "utf-8"
          RASA_TELEMETRY_WRITE_KEY: ${{ secrets.SEGMENT_WRITE_DEV_KEY }}
        run: |
          make test-metrics-integration

      - name: Show container logs
        if: always()
        uses: ./.github/actions/debug-metric-tests
        with:
          COMPOSE_FILE_PATH: tests_deployment/integration_tests_metrics_setup/docker-compose.yml

      - name: Metric Integration Testing - Stop docker containers
        run: |
          make stop-metrics-integration-containers

      - name: Save Test Results
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: Metric Integration Test Results
          path: integration-results-metric.xml

  custom-action-integration-tests:
    name: Custom Action Integration Tests With NLU bot and CALM bot
    if: ${{ inputs.full_ci_mode != 'false' }}
    needs: rasa-private-dev-docker-image
    runs-on: ubuntu-24.04-4core
    env:
      RASA_SDK_IMAGE_TAG: latest

    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Read Poetry Version 🔢
        run: |
          echo "POETRY_VERSION=$(scripts/poetry-version.sh)" >> $GITHUB_ENV
        shell: bash

      - name: Prepare the job for integration tests
        uses: ./.github/actions/test-prerequisites
        with:
            PYTHON_VERSION: ${{ env.DEFAULT_PYTHON_VERSION }}
            POETRY_CACHE_VERSION: ${{ secrets.POETRY_CACHE_VERSION }}

      - name: Docker version
        run: docker --version && docker compose version

      - name: Download image artifact
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e #v4.2.1
        with:
          name: docker-image-${{ needs.rasa-private-dev-docker-image.outputs.rasa_image_tag }}.tar.gz

      - name: Load Docker image
        run: |
          gunzip -c image-${{ needs.rasa-private-dev-docker-image.outputs.rasa_image_tag }}.tar.gz | docker load

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 #v4.1.0
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 #v2.0.1

      - name: Custom Actions Integration Testing NLU - Train docker containers
        run: |
          make train-action-server-nlu-bot
        env:
          RASA_PRO_LICENSE: ${{ secrets.RASA_PRO_LICENSE }}
          RASA_REPOSITORY: ${{ env.RASA_PRO_DEV_REPOSITORY }}
          RASA_IMAGE_TAG: ${{ needs.rasa-private-dev-docker-image.outputs.rasa_image_tag }}
          RASA_SDK_REPOSITORY: ${{ env.RASA_SDK_DEV_REPOSITORY }}
          RASA_SDK_IMAGE_TAG: ${{ env.RASA_SDK_IMAGE_TAG }}

      - name: Custom Actions Integration Testing NLU - Run docker containers
        run: |
          make run-action-server-nlu-containers
        env:
          RASA_PRO_LICENSE: ${{ secrets.RASA_PRO_LICENSE }}
          RASA_REPOSITORY: ${{ env.RASA_PRO_DEV_REPOSITORY }}
          RASA_IMAGE_TAG: ${{ needs.rasa-private-dev-docker-image.outputs.rasa_image_tag }}
          RASA_SDK_REPOSITORY: ${{ env.RASA_SDK_DEV_REPOSITORY }}
          RASA_SDK_IMAGE_TAG: ${{ env.RASA_SDK_IMAGE_TAG }}

      - name: Custom Actions Testing NLU - Test Code with Services 🩺
        run: |
          make test-custom-action-integration-with-nlu-bot
        env:
          PYTHONIOENCODING: "utf-8"
          RASA_TELEMETRY_WRITE_KEY: ${{ secrets.SEGMENT_WRITE_DEV_KEY }}

      - name: Show container logs NLU
        if: always()
        uses: ./.github/actions/debug-custom-action-tests
        with:
          COMPOSE_FILE_PATH: tests_deployment/integration_tests_custom_action_server/docker-compose.yml
          ENV_FILE_PATH: tests_deployment/integration_tests_custom_action_server/env-file
          RASA_REPOSITORY: ${{ env.RASA_PRO_DEV_REPOSITORY }}
          RASA_IMAGE_TAG: ${{ needs.rasa-private-dev-docker-image.outputs.rasa_image_tag }}
          RASA_SDK_REPOSITORY: ${{ env.RASA_SDK_DEV_REPOSITORY }}
          RASA_SDK_IMAGE_TAG: ${{ env.RASA_SDK_IMAGE_TAG }}
          BOT_PATH: "./tests_deployment/integration_tests_custom_action_server/simple_nlu_bot"

      - name: Custom Action Integration Testing NLU - Stop docker containers
        if: always()
        run: |
          make stop-action-server-nlu-containers

      - name: Save Test Results NLU bot
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: Custom Action Integration Test Results For NLU bot
          path:
           integration-results-custom-actions-with-nlu-bot-results.xml

      - name: Custom Actions Integration Testing CALM - Train docker containers
        run: |
          make train-action-server-calm-bot
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          RASA_PRO_LICENSE: ${{ secrets.RASA_PRO_LICENSE }}
          RASA_REPOSITORY: ${{ env.RASA_PRO_DEV_REPOSITORY }}
          RASA_IMAGE_TAG: ${{ needs.rasa-private-dev-docker-image.outputs.rasa_image_tag }}
          RASA_SDK_REPOSITORY: ${{ env.RASA_SDK_DEV_REPOSITORY }}
          RASA_SDK_IMAGE_TAG: ${{ env.RASA_SDK_IMAGE_TAG }}

      - name: Custom Actions Integration Testing CALM - Run docker containers
        run: |
          make run-action-server-calm-containers
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          RASA_PRO_LICENSE: ${{ secrets.RASA_PRO_LICENSE }}
          RASA_REPOSITORY: ${{ env.RASA_PRO_DEV_REPOSITORY }}
          RASA_IMAGE_TAG: ${{ needs.rasa-private-dev-docker-image.outputs.rasa_image_tag }}
          RASA_SDK_REPOSITORY: ${{ env.RASA_SDK_DEV_REPOSITORY }}
          RASA_SDK_IMAGE_TAG: ${{ env.RASA_SDK_IMAGE_TAG }}

      - name: Custom Actions Testing CALM -  Test Code with Services 🩺
        run: |
          make test-custom-action-integration-with-calm-bot
        env:
          PYTHONIOENCODING: "utf-8"
          RASA_TELEMETRY_WRITE_KEY: ${{ secrets.SEGMENT_WRITE_DEV_KEY }}

      - name: Show container logs CALM
        if: always()
        uses: ./.github/actions/debug-custom-action-tests
        with:
          COMPOSE_FILE_PATH: tests_deployment/integration_tests_custom_action_server/docker-compose.yml
          ENV_FILE_PATH: tests_deployment/integration_tests_custom_action_server/env-file
          RASA_REPOSITORY: ${{ env.RASA_PRO_DEV_REPOSITORY }}
          RASA_IMAGE_TAG: ${{ needs.rasa-private-dev-docker-image.outputs.rasa_image_tag }}
          RASA_SDK_REPOSITORY: ${{ env.RASA_SDK_DEV_REPOSITORY }}
          RASA_SDK_IMAGE_TAG: ${{ env.RASA_SDK_IMAGE_TAG }}
          BOT_PATH: "./tests_deployment/integration_tests_custom_action_server/simple_calm_bot"

      - name: Custom Action Integration Testing CALM - Stop docker containers
        if: always()
        run: |
          make stop-action-server-calm-containers

      - name: Save Test Results CALM bot
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: Custom Action Integration Test Results For CALM bot
          path:
           integration-results-custom-actions-with-calm-bot-results.xml

  enterprise-search-integration-tests:
    name: Run Enterprise Search Integration Tests
    if: ${{ inputs.full_ci_mode != 'false' }}
    needs: rasa-private-dev-docker-image
    runs-on: ubuntu-24.04-4core
    env:
      RASA_SDK_IMAGE_TAG: latest
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python 3.10 🐍
        id: setup-python
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
        with:
          python-version: '3.10'

      - name: Read Poetry Version 🔢
        run: |
          echo "POETRY_VERSION=$(scripts/poetry-version.sh)" >> $GITHUB_ENV
        shell: bash

      # Install & configure poetry
      - name: Install Poetry ${{ env.POETRY_VERSION }}
        uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a # v1.4.1
        with:
          version: ${{ env.POETRY_VERSION }}
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install Dependencies (Linux) 📦
        # without this step the additional dependency installations with pip install
        # in the `Install additional dependencies for Docs ingestion` step fails
        shell: bash
        run: |
          make install

      - name: Download image artifact
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e #v4.2.1
        with:
          name: docker-image-${{ needs.rasa-private-dev-docker-image.outputs.rasa_image_tag }}.tar.gz

      - name: Load Docker image
        run: |
          gunzip -c image-${{ needs.rasa-private-dev-docker-image.outputs.rasa_image_tag }}.tar.gz | docker load

      - name: Enterprise Search Integration Testing - Train bot Faiss
        run: |
          make train-rasa-calm-bot
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          RASA_PRO_LICENSE: ${{ secrets.RASA_PRO_LICENSE }}
          RASA_REPOSITORY: ${{ env.RASA_PRO_DEV_REPOSITORY }}
          RASA_IMAGE_TAG: ${{ needs.rasa-private-dev-docker-image.outputs.rasa_image_tag }}
          CONFIG: "config-faiss.yml"
          ENDPOINTS: "endpoints-faiss.yml"
          MODEL_NAME: "model-faiss"

      - name: Enterprise Search Integration Testing - Train bot Milvus
        run: |
          make train-rasa-calm-bot
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          RASA_PRO_LICENSE: ${{ secrets.RASA_PRO_LICENSE }}
          RASA_REPOSITORY: ${{ env.RASA_PRO_DEV_REPOSITORY }}
          RASA_IMAGE_TAG: ${{ needs.rasa-private-dev-docker-image.outputs.rasa_image_tag }}
          CONFIG: "config-milvus.yml"
          ENDPOINTS: "endpoints-milvus.yml"
          MODEL_NAME: "model-milvus"

      - name: Enterprise Search Integration Testing - Train bot for Qdrant
        run: |
          make train-rasa-calm-bot
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          RASA_PRO_LICENSE: ${{ secrets.RASA_PRO_LICENSE }}
          RASA_REPOSITORY: ${{ env.RASA_PRO_DEV_REPOSITORY }}
          RASA_IMAGE_TAG: ${{ needs.rasa-private-dev-docker-image.outputs.rasa_image_tag }}
          CONFIG: "config-qdrant.yml"
          ENDPOINTS: "endpoints-qdrant.yml"
          MODEL_NAME: "model-qdrant"

      - name: Enterprise Search Integration Testing - Run docker containers
        run: |
          make run-rasa-calm-demo-test-containers
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          RASA_PRO_LICENSE: ${{ secrets.RASA_PRO_LICENSE }}
          RASA_REPOSITORY: ${{ env.RASA_PRO_DEV_REPOSITORY }}
          RASA_IMAGE_TAG: ${{ needs.rasa-private-dev-docker-image.outputs.rasa_image_tag }}
          CONFIG: "config-qdrant.yml"
          ENDPOINTS: "endpoints-qdrant.yml"
          DOCKER_COMPOSE: "docker-compose.yml"

      - name: Install additional dependencies for Docs ingestion
        run: |
          pip install unstructured==0.12.2 langchain==0.0.329 qdrant-client==1.9.1 pymilvus==2.3.5 openai==0.28.1 tiktoken==0.4.0

      - name: Run vector store setup for Qdrant
        run: |
          python tests_deployment/integration_tests_enterprise_search/ingest.py -c tests_deployment/integration_tests_enterprise_search/qdrant_config.yaml
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Run vector store setup for Milvus
        run: |
          python tests_deployment/integration_tests_enterprise_search/ingest.py -c tests_deployment/integration_tests_enterprise_search/milvus_config.yaml
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Enterprise Search Integration Testing -  Test Code with Services 🩺
        run: |
          make test-enterprise-search-integration-with-calm-bot
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PYTHONIOENCODING: "utf-8"
          RASA_TELEMETRY_WRITE_KEY: ${{ secrets.SEGMENT_WRITE_DEV_KEY }}
          TEST_NAME: "test_search_with_vector_stores.py"

      - name: Show container logs
        if: always()
        uses: ./.github/actions/debug-enterprise-search-tests
        with:
          COMPOSE_FILE_PATH: tests_deployment/integration_tests_enterprise_search/docker-compose.yml

      - name: Enterprise Search Integration Testing - Stop docker containers
        if: always()
        run: |
          make stop-rasa-calm-demo-bot-test-containers
        env:
          DOCKER_COMPOSE: "docker-compose.yml"

      - name: Save Test Results
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: Enterprise Search Integration Test Results
          path: integration-results-enterprise-search.xml

  sequential-integration-test:
      name: Run Sequential Integration Tests
      runs-on: ubuntu-24.04
      if: ${{ inputs.full_ci_mode != 'false' }}
      timeout-minutes: 60
      env:
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres

      services:
        postgres:
          image: postgres:13
          # Set health checks to wait until postgres has started
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
          env:
            # postgres image requires password to be set
            POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          ports:
            # FIXME: cannot use ${{ env.POSTGRES_PORT }} here
            # mapping container ports to the host
            - 5432:5432
      steps:
        - name: Check out code
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

        - name: Prepare the job for integration tests
          uses: ./.github/actions/test-prerequisites
          with:
              PYTHON_VERSION: ${{ env.DEFAULT_PYTHON_VERSION }}
              POETRY_CACHE_VERSION: ${{ secrets.POETRY_CACHE_VERSION }}

        - name: Install Dependencies (Linux) 📦
          run: |
            make install
          shell: bash

        # these integration tests need to be run in a sequential fashion,
        # due to environment constraints, so we're running them in a single process.
        - name: Test Code with Services 🩺 (sequential)
          env:
            JOBS: 1
            INTEGRATION_TEST_PYTEST_MARKERS: "sequential"
            PYTHONIOENCODING: "utf-8"
          run: |
            make test-integration

        - name: Prepare test results
          if: always()
          run: mv report_integration.xml integration-results-sequential.xml

        - name: Save Test Results
          if: always()
          uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
          with:
            name: Sequential Integration Test Results
            path: integration-results-sequential.xml

  non-sequential-integration-test:
    name: Run Non-Sequential Integration Tests
    runs-on: ubuntu-24.04-8core
    if: ${{ inputs.full_ci_mode != 'false' }}
    timeout-minutes: 60
    env:
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Prepare the job for integration tests
        uses: ./.github/actions/test-prerequisites
        with:
            PYTHON_VERSION: ${{ env.DEFAULT_PYTHON_VERSION }}
            POETRY_CACHE_VERSION: ${{ secrets.POETRY_CACHE_VERSION }}

      - name: Install Dependencies (Linux) 📦
        run: |
          make install-nlu
        shell: bash

      - name: Run container for non-sequential integration testing
        run: |
          make run-non-sequential-container

      - name: Test Code with Services 🩺
        env:
          JOBS: 6
          INTEGRATION_TEST_PYTEST_MARKERS: '"(not sequential) and (not broker) and (not concurrent_lock_store)"'
          PYTHONIOENCODING: "utf-8"
          INTEGRATION_TESTS_STUDIO_LICENSE: ${{ secrets.INTEGRATION_TESTS_STUDIO_LICENSE }}
          INTEGRATION_TESTS_PRO_LICENSE: ${{ secrets.INTEGRATION_TESTS_PRO_LICENSE }}
          INTEGRATION_TESTS_PRO_LICENSE_ALL_FEATURES: ${{ secrets.INTEGRATION_TESTS_PRO_LICENSE_ALL_FEATURES }}
          RASA_PRO_LICENSE: ${{ secrets.RASA_PRO_LICENSE }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          make prepare-tests-ubuntu
          make prepare-spacy
          make test-integration

      - name: Prepare test results
        if: always()
        run: mv report_integration.xml integration-results-non-sequential.xml

      - name: Save Test Results
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: Non-Sequential Integration Test Results
          path: integration-results-non-sequential.xml

      - name: Show container logs for non-sequential integration testing
        run: |
          make show-non-sequential-container-logs

      - name: Stop container for non-sequential integration testing
        run: |
          make stop-non-sequential-container

  mongo-tracker-store-integration-test:
    name: Run Mongo Tracker Store Integration Tests
    runs-on: ubuntu-24.04-8core
    if: ${{ inputs.full_ci_mode != 'false' }}
    timeout-minutes: 60
    env:
      DB_PORT: 27017
      DB_ROOT_USER: root
      DB_ROOT_PASSWORD: rootpass
      DB_USER: user
      DB_PASSWORD: userpass
      DB_NAME: rasa

    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Prepare the job for integration tests
        uses: ./.github/actions/test-prerequisites
        with:
          PYTHON_VERSION: ${{ env.DEFAULT_PYTHON_VERSION }}
          POETRY_CACHE_VERSION: ${{ secrets.POETRY_CACHE_VERSION }}

      - name: Install Dependencies (Linux) 📦
        run: |
          make install
        shell: bash

      - name: Run containers for tracker store integration testing
        run: |
          make run-mongodb-container

      - name: Test Code with Services 🩺
        env:
          JOBS: 6
          PYTHONIOENCODING: "utf-8"
          INTEGRATION_TESTS_STUDIO_LICENSE: ${{ secrets.INTEGRATION_TESTS_STUDIO_LICENSE }}
          INTEGRATION_TESTS_PRO_LICENSE: ${{ secrets.INTEGRATION_TESTS_PRO_LICENSE }}
          INTEGRATION_TESTS_PRO_LICENSE_ALL_FEATURES: ${{ secrets.INTEGRATION_TESTS_PRO_LICENSE_ALL_FEATURES }}
          RASA_PRO_LICENSE: ${{ secrets.RASA_PRO_LICENSE }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          make prepare-tests-ubuntu
          make test-mongodb-tracker-store

      - name: Show mongo-with-tls container logs
        if: always()
        uses: ./.github/actions/debug-tracker-store-tests
        with:
          COMPOSE_FILE_PATH: tests_deployment/integration_tests_tracker_stores/mongo_db_tracker_store/docker-compose.mongodb.yml
          CONTAINER_NAME: mongodb-with-tls

      - name: Show mongo-without-tls container logs
        if: always()
        uses: ./.github/actions/debug-tracker-store-tests
        with:
          COMPOSE_FILE_PATH: tests_deployment/integration_tests_tracker_stores/mongo_db_tracker_store/docker-compose.mongodb.yml
          CONTAINER_NAME: mongodb-without-tls

      - name: Stop containers for tracker store integration testing
        if: always()
        run: |
          make stop-mongodb-container

      - name: Save Test Results
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: Tracker Store Integration Test Results
          path: integration-results-mongo-tracker-store.xml

  dynamo-tracker-store-integration-test:
    name: Run Dynamo Tracker Store Integration Tests
    runs-on: ubuntu-24.04
    if: ${{ inputs.full_ci_mode != 'false' }}
    timeout-minutes: 60

    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Prepare the job for integration tests
        uses: ./.github/actions/test-prerequisites
        with:
          PYTHON_VERSION: ${{ env.DEFAULT_PYTHON_VERSION }}
          POETRY_CACHE_VERSION: ${{ secrets.POETRY_CACHE_VERSION }}

      - name: Install Dependencies (Linux) 📦
        run: |
          make install
        shell: bash

      - name: Run containers for tracker store integration testing
        run: |
          make run-dynamo-container

      - name: Test Code with Services 🩺
        env:
          JOBS: 1
          PYTHONIOENCODING: "utf-8"
          INTEGRATION_TESTS_STUDIO_LICENSE: ${{ secrets.INTEGRATION_TESTS_STUDIO_LICENSE }}
          INTEGRATION_TESTS_PRO_LICENSE: ${{ secrets.INTEGRATION_TESTS_PRO_LICENSE }}
          INTEGRATION_TESTS_PRO_LICENSE_ALL_FEATURES: ${{ secrets.INTEGRATION_TESTS_PRO_LICENSE_ALL_FEATURES }}
          RASA_PRO_LICENSE: ${{ secrets.RASA_PRO_LICENSE }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          AWS_ENDPOINT_URL: "http://0.0.0.0:8000"
          AWS_ACCESS_KEY_ID: "testing"
          AWS_SECRET_ACCESS_KEY: "testing"
        run: |
          make prepare-tests-ubuntu
          make test-dynamo-tracker-store

      - name: Show container logs
        if: always()
        uses: ./.github/actions/debug-tracker-store-tests
        with:
          COMPOSE_FILE_PATH: tests_deployment/integration_tests_tracker_stores/dynamo_tracker_store/docker-compose.dynamo.yml
          CONTAINER_NAME: dynamodb-local

      - name: Stop containers for tracker store integration testing
        if: always()
        run: |
          make stop-dynamo-container

      - name: Save Test Results
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: Dynamo Tracker Store Integration Test Results
          path: integration-results-dynamo-tracker-store.xml

  concurrent-lockstore-integration-test:
    name: Run Concurrent LockStore Integration Tests
    runs-on: ubuntu-24.04
    if: ${{ inputs.full_ci_mode != 'false' }}
    timeout-minutes: 60
    env:
      REDIS_HOST: localhost
      REDIS_PORT: 6379

    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Prepare the job for integration tests
        uses: ./.github/actions/test-prerequisites
        with:
            PYTHON_VERSION: ${{ env.DEFAULT_PYTHON_VERSION }}
            POETRY_CACHE_VERSION: ${{ secrets.POETRY_CACHE_VERSION }}

      - name: Install Dependencies (Linux) 📦
        run: |
          make install
        shell: bash

      - name: Run container for concurrent lock store integration testing
        run: |
          make run-concurrent-lock-store-container

        # these integration tests need to be run separately
      - name: Test Code with Services 🩺 (concurrent_lock_store)
        env:
          JOBS: 1
          INTEGRATION_TEST_PYTEST_MARKERS: "concurrent_lock_store"
          PYTHONIOENCODING: "utf-8"
        run: |
          make test-integration

      - name: Prepare test results
        if: always()
        run: mv report_integration.xml integration-results-concurrent-lockstore.xml

      - name: Save Test Results
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: Concurrent LockStore Integration Test Results
          path: integration-results-concurrent-lockstore.xml

      - name: Show container logs for concurrent lock store integration testing
        run: |
          make show-concurrent-lock-store-container-logs

      - name: Stop container for concurrent lock store integration testing
        run: |
          make stop-concurrent-lock-store-container

  broker_integration_test:
    name: Run Broker Integration Tests
    runs-on: ubuntu-24.04
    if: ${{ inputs.full_ci_mode != 'false' }}
    timeout-minutes: 60

    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Free up disk-space
        uses: RasaHQ/rasa-private/.github/actions/free-disk-space@fe77d93db58f0412e2162fdaa34e2ed596f8536b

      - name: Prepare the job for integration tests
        uses: ./.github/actions/test-prerequisites
        with:
          PYTHON_VERSION: ${{ env.DEFAULT_PYTHON_VERSION }}
          POETRY_CACHE_VERSION: ${{ secrets.POETRY_CACHE_VERSION }}

      - name: Install Dependencies Full (Linux) 📦
        run: |
          sudo apt-get -y install libpq-dev
          make install-full | tee .output
          if grep 'The lock file is not up to date' .output; then exit 1; fi
          make prepare-tests-ubuntu
          make prepare-spacy

      - name: Run the pika test separately
        # these tests need to be run separately as they turn on and off docker container and interfere with the other broker tests
        run: |
          poetry run pytest tests/integration_tests/core/brokers/test_pika.py --junitxml=report_pika_test_integration.xml

      - name: Prepare pika test results
        if: always()
        run: mv report_pika_test_integration.xml integration-results-pika-broker-integration.xml

      - name: Save Test Results
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
            name: Pika Broker Integration Test Results
            path: integration-results-pika-broker-integration.xml

      - name: Run rabbitmq, kafka and zookeeper containers for integration testing
        run: |
          docker compose -f tests_deployment/docker-compose.broker.yml up -d

      - name: Test Code with Services 🩺(broker_integration_test)
        env:
          JOBS: 1
          INTEGRATION_TEST_PYTEST_MARKERS: "broker"
          PYTHONIOENCODING: "utf-8"
        run: |
            make test-integration

      - name: Show container logs
        if: always()
        uses: ./.github/actions/debug-broker-tests
        with:
          COMPOSE_FILE_PATH: tests_deployment/docker-compose.broker.yml

      - name: Prepare test results
        if: always()
        run: mv report_integration.xml integration-results-broker-integration.xml

      - name: Save Test Results
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
            name: Broker Integration Test Results
            path: integration-results-broker-integration.xml

      - name: Stop rabbitmq, kafka and zookeeper containers for integration testing
        run: |
          docker compose -f tests_deployment/docker-compose.broker.yml down

  channel_connector_integration_tests:
    name: Channel Connector Integration Tests With CALM bot
    needs: rasa-private-dev-docker-image
    if: ${{ inputs.full_ci_mode != 'false' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Prepare the job for integration tests
        uses: ./.github/actions/test-prerequisites
        with:
          PYTHON_VERSION: ${{ env.DEFAULT_PYTHON_VERSION }}
          POETRY_CACHE_VERSION: ${{ secrets.POETRY_CACHE_VERSION }}

      - name: Docker version
        run: docker --version && docker compose version

      - name: Download image artifact
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e #v4.2.1
        with:
          name: docker-image-${{ needs.rasa-private-dev-docker-image.outputs.rasa_image_tag }}.tar.gz

      - name: Load Docker image
        run: |
          gunzip -c image-${{ needs.rasa-private-dev-docker-image.outputs.rasa_image_tag }}.tar.gz | docker load

      - name: Channel connector Integration Tests - Run docker containers
        run: |
          make run-channel-connectors-integration-containers
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          RASA_PRO_LICENSE: ${{ secrets.RASA_PRO_LICENSE }}
          RASA_REPOSITORY: ${{ env.RASA_PRO_DEV_REPOSITORY }}
          RASA_IMAGE_TAG: ${{ needs.rasa-private-dev-docker-image.outputs.rasa_image_tag }}

      - name: Channel connector Integration Tests -  Test Code with Services 🩺
        run: |
          make test-channel-connectors-integration-with-calm-bot
        env:
          PYTHONIOENCODING: "utf-8"
          RASA_TELEMETRY_WRITE_KEY: ${{ secrets.SEGMENT_WRITE_DEV_KEY }}

      - name: Integration Test for Custom Broker
        run: make test-custom-broker-integration-with-calm-bot

      - name: Show container logs
        if: always()
        uses: ./.github/actions/debug-rasa-pro-assistant-container-logs
        with:
          COMPOSE_FILE_PATH: tests_deployment/integration_tests_channel_connectors/docker-compose.yml

      - name: Channel connector Integration Tests - Stop docker containers
        if: always()
        run: |
          make stop-channel-connectors-integration-containers

      - name: Save Test Results
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: Channel connector Integration Tests Test Results
          path: |
           integration-results-channel-connectors-with-calm-bot-results.xml
           integration-results-custom-broker-with-calm-bot-results.xml

  check-pii-management-changes:
    runs-on: ubuntu-24.04
    outputs:
      pii-management: ${{ steps.filter.outputs.pii-management }}
    steps:
      - name: Checkout git repository 🕝
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - id: filter
        name: Check for changes in DM1/Tensorflow related files
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36  # v3.0.2
        with:
          filters: .github/change_filters.yml

  pii-management-in-calm-integration-tests:
    name: PII Management in CALM Bot Integration Tests
    needs: [rasa-private-dev-docker-image, check-pii-management-changes]
    if: ${{ inputs.full_ci_mode != 'false' && (needs.check-pii-management-changes.outputs.pii-management == 'true') }}
    runs-on: ubuntu-24.04-4core
    env:
      RASA_SDK_IMAGE_TAG: latest
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Read Poetry Version 🔢
        run: |
          echo "POETRY_VERSION=$(scripts/poetry-version.sh)" >> $GITHUB_ENV
        shell: bash

      - name: Prepare the job for integration tests
        uses: ./.github/actions/test-prerequisites
        with:
          PYTHON_VERSION: ${{ env.DEFAULT_PYTHON_VERSION }}
          POETRY_CACHE_VERSION: ${{ secrets.POETRY_CACHE_VERSION }}

      - name: Get latest Rasa Pro version
        id: get-latest-rasa-pro-version
        run: |
          chmod 755 scripts/get-latest-rasa-version.py
          echo "LATEST_RASA_PRO_VERSION=$(python scripts/get-latest-rasa-version.py)" >> $GITHUB_ENV

      - name: Download image artifact
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e #v4.2.1
        with:
          name: docker-image-${{ needs.rasa-private-dev-docker-image.outputs.rasa_image_tag }}.tar.gz

      - name: Load Docker image
        run: |
          gunzip -c image-${{ needs.rasa-private-dev-docker-image.outputs.rasa_image_tag }}.tar.gz | docker load

      - name: Build Rasa Pro PII image with GLiNER and trained Rasa models
        id: build_rasa_pro_pii_image
        env:
          RASA_IMAGE_TAG: ${{ needs.rasa-private-dev-docker-image.outputs.rasa_image_tag }}
        working-directory: "./tests_deployment/integration_tests_pii_management_in_calm/calm_demo_bot"
        run: |
          docker build --build-arg RASA_REPOSITORY=${{ env.RASA_PRO_DEV_REPOSITORY }} \
                       --build-arg RASA_IMAGE_TAG=${{ env.RASA_IMAGE_TAG }} \
                       --build-arg LATEST_RASA_PRO_VERSION=${{ env.LATEST_RASA_PRO_VERSION }} \
                       -t ${{ env.RASA_PRO_DEV_REPOSITORY }}:${{ env.RASA_IMAGE_TAG }}-pii .

      - name: PII Integration Testing - Run docker containers
        run: |
          make run-pii-calm-containers
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          RASA_PRO_LICENSE: ${{ secrets.RASA_PRO_LICENSE }}
          RASA_REPOSITORY: ${{ env.RASA_PRO_DEV_REPOSITORY }}
          RASA_IMAGE_TAG: ${{ needs.rasa-private-dev-docker-image.outputs.rasa_image_tag }}-pii
          RASA_SDK_REPOSITORY: ${{ env.RASA_SDK_DEV_REPOSITORY }}
          RASA_SDK_IMAGE_TAG: ${{ env.RASA_SDK_IMAGE_TAG }}

      - name: PII Management in CALM Testing -  Test Code with Services 🩺
        run: |
          make test-pii-integration-with-calm-bot
        env:
          PYTHONIOENCODING: "utf-8"
          RASA_TELEMETRY_WRITE_KEY: ${{ secrets.SEGMENT_WRITE_DEV_KEY }}

      - name: Show container logs
        if: always()
        uses: ./.github/actions/debug-pii-management-tests
        with:
          COMPOSE_FILE_PATH: tests_deployment/integration_tests_pii_management_in_calm/docker-compose.yml
          RASA_REPOSITORY: ${{ env.RASA_PRO_DEV_REPOSITORY }}
          RASA_IMAGE_TAG: ${{ needs.rasa-private-dev-docker-image.outputs.rasa_image_tag }}-pii
          BOT_PATH: "./tests_deployment/integration_tests_pii_management_in_calm/calm_demo_bot"

      - name: PII Integration Testing - Stop docker containers
        if: always()
        run: |
          make stop-pii-calm-containers

      - name: Save Test Results
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: PII Management in CALM Bot Integration Tests
          path: pii-management-in-calm-integration-results.xml

  check-voice-code-changes:
    runs-on: ubuntu-24.04
    outputs:
      voice-files: ${{ steps.filter.outputs.voice-files }}
    steps:
      - name: Checkout git repository 🕝
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - id: filter
        name: Check for changes in voice related files
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36  # v3.0.2
        with:
          filters: .github/change_filters.yml

  voice_unit_tests:
    name: Run Voice Unit Tests
    needs: [ check-voice-code-changes ]
    if: ${{ inputs.full_ci_mode != 'false' && (needs.check-voice-code-changes.outputs.voice-files == 'true') }}
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        test:
          - test-audio-manual
        python-version: [ "3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Prepare the job for unit tests
        uses: ./.github/actions/test-prerequisites
        with:
          PYTHON_VERSION: ${{ matrix.python-version }}
          POETRY_CACHE_VERSION: ${{ secrets.POETRY_CACHE_VERSION }}

      - name: Install Dependencies (Linux) 📦
        # Poetry intermittently fails to install dependency if it is not PEP 517 compliant
        # This is a workaround for that issue
        run: |
          sudo apt-get -y install libpq-dev
          make install-full | tee .output
          if grep 'The lock file is not up to date' .output; then exit 1; fi
          make prepare-tests-ubuntu

      - name: Install ddtrace on Linux
        run: poetry run pip install -U ddtrace

      - name: Install additional dependencies for voice tests
        if: matrix.test == 'test-audio-manual'
        run: |
          poetry run python -m pip install azure-cognitiveservices-speech

      - name: Test Code 🔍 (multi-process)
        env:
          JOBS: 6
          PYTHONUTF8: 1
          DD_ENV: ${{ matrix.test }}
          DD_SERVICE: rasa
          DD_ARGS: --ddtrace --ddtrace-patch-all --junitxml=unit-tests-results.xml
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          RASA_PRO_LICENSE: ${{ secrets.RASA_PRO_LICENSE }}
          CARTESIA_API_KEY: ${{ secrets.CARTESIA_API_KEY }}
          DEEPGRAM_API_KEY: ${{ secrets.DEEPGRAM_API_KEY }}
          AZURE_SPEECH_API_KEY: ${{ secrets.AZURE_SPEECH_API_KEY }}
          API_DOCS_FORMAT: yaml
        run: |
          make ${{ matrix.test }}
        shell: bash # bash shell is a way to make code run for both Linux and Windows

      - name: Prepare test results
        if: always()
        run: mv coverage.xml  ${{ github.workspace }}/unit-tests-results-${{ matrix.test }}-python-${{ matrix.python-version }}.xml

      - name: Save Test Results
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: unit-tests-results-${{ matrix.test }}-python-${{ matrix.python-version }}
          path: |
            ${{ github.workspace }}/unit-tests-results-${{ matrix.test }}-python-${{ matrix.python-version }}.xml

  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-24.04-4core
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        test:
          - test-cli
          - test-policies
          - test-nlu-featurizers
          - test-nlu-predictors
          - test-full-model-training
          - test-other-unit-tests
          - test-performance
          - test-flaky
          - test-agents
        python-version: ${{ fromJson(inputs.python-versions) }}

    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Prepare the job for unit tests
        uses: ./.github/actions/test-prerequisites
        with:
            PYTHON_VERSION: ${{ matrix.python-version }}
            POETRY_CACHE_VERSION: ${{ secrets.POETRY_CACHE_VERSION }}

      - name: Install Dependencies (Linux) 📦
        # Poetry intermittently fails to install dependency if it is not PEP 517 compliant
        # This is a workaround for that issue
        run: |
          sudo apt-get -y install libpq-dev
          make install-full | tee .output
          if grep 'The lock file is not up to date' .output; then exit 1; fi
          make prepare-tests-ubuntu

      - name: Install ddtrace on Linux
        run: poetry run pip install -U ddtrace

      - name: Make direcory for Swagger/OpenAPI coverage results
        if: matrix.test == 'test-other-unit-tests'
        run: mkdir -p 'swagger-coverage-output/localhost:5005'

      - name: Test Code 🔍 (multi-process)
        env:
          JOBS: 6
          PYTHONUTF8: 1
          DD_ENV: ${{ matrix.test }}
          DD_SERVICE: rasa
          DD_ARGS: --ddtrace --ddtrace-patch-all --junitxml=unit-tests-results.xml
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          RASA_PRO_LICENSE: ${{ secrets.RASA_PRO_LICENSE }}
          BLOCKED_LICENSE: ${{ secrets.BLOCKED_LICENSE }}
          CHAMPION_LICENSE: ${{ secrets.CHAMPION_LICENSE }}
          CHAMPION_SERVER_INTERNAL_LICENSE: ${{ secrets.CHAMPION_SERVER_INTERNAL_LICENSE }}
          CHAMPION_SERVER_LIMITED_LICENSE: ${{ secrets.CHAMPION_SERVER_LIMITED_LICENSE }}
          EXPIRED_LICENSE: ${{ secrets.EXPIRED_LICENSE }}
          IMMATURE_LICENSE: ${{ secrets.IMMATURE_LICENSE }}
          INVALID_SCHEMA_LICENSE: ${{ secrets.INVALID_SCHEMA_LICENSE }}
          INVALID_SIGNATURE_LICENSE: ${{ secrets.INVALID_SIGNATURE_LICENSE }}
          NON_JWT_LICENSE: ${{ secrets.NON_JWT_LICENSE }}
          UNSCOPED_LICENSE: ${{ secrets.UNSCOPED_LICENSE }}
          VALID_LICENSE: ${{ secrets.VALID_LICENSE }}
          API_DOCS_FORMAT: yaml
        run: |
          make ${{ matrix.test }}
        shell: bash # bash shell is a way to make code run for both Linux and Windows

      - name: Prepare test results
        if: always()
        run: |
          mv coverage.xml ${{ github.workspace }}/unit-tests-results-${{ matrix.test }}-python-${{ matrix.python-version }}.xml

      - name: Generate Rasa server OpenAPI test coverage report
        if: always() && matrix.test == 'test-other-unit-tests'
        run: |
          .venv/lib/python${{ matrix.python-version }}/site-packages/swagger_coverage_py/swagger-coverage-commandline/bin/swagger-coverage-commandline \
          -c swagger-coverage-config-rasa-pro.json \
          -i swagger-coverage-output/localhost:5005 \
          -s swagger-doc-rasa-pro.yaml

      - name: Save Test Results
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: unit-tests-results-${{ matrix.test }}-python-${{ matrix.python-version }}
          path: |
            ${{ github.workspace }}/unit-tests-results-${{ matrix.test }}-python-${{ matrix.python-version }}.xml

      - name: Save Rasa server OpenAPI tests coverage report
        if: always() && matrix.test == 'test-other-unit-tests'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: Rasa Server OpenAPI tests coverage report on python-${{ matrix.python-version }}
          path: swagger-coverage-report-rasa-pro.html

  test-anonymization:
    name: Run Anonymization Unit Tests
    runs-on: ubuntu-24.04-4core
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJson(inputs.python-versions) }}

    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Prepare the job for unit tests
        uses: ./.github/actions/test-prerequisites
        with:
          PYTHON_VERSION: ${{ matrix.python-version }}
          POETRY_CACHE_VERSION: ${{ secrets.POETRY_CACHE_VERSION }}

      - name: Install Dependencies (Linux) 📦
        # Poetry intermittently fails to install dependency if it is not PEP 517 compliant
        # This is a workaround for that issue
        run: |
          sudo apt-get -y install libpq-dev
          make install-mitie
          make install-nlu-pii-channels | tee .output
          if grep 'The lock file is not up to date' .output; then exit 1; fi
          make prepare-tests-ubuntu

      - name: Install spaCy language model
        run: |
          poetry run python -m pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.7.1/en_core_web_lg-3.7.1-py3-none-any.whl

      - name: Install Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@1bad5a8c1bb08ac392c63b4587f3231cf80bb1a4

      - name: Install Hugging Face CLI
        run: |
          brew install huggingface-cli
        shell: bash

      - name: Download GliNER model for PII
        env:
          HUGGINGFACE_API_KEY: ${{ secrets.HUGGINGFACE_API_KEY }}
        run: |
          git config --global credential.helper cache
          huggingface-cli login --token ${{ env.HUGGINGFACE_API_KEY }} --add-to-git-credential
          if [[ ! -d models ]]; then
            mkdir models;
          fi
          huggingface-cli download urchade/gliner_multi_pii-v1 --repo-type model --local-dir models --cache-dir models
        shell: bash

      - name: Install ddtrace on Linux
        run: poetry run pip install -U ddtrace

      - name: Test Code 🔍 (multi-process)
        env:
          JOBS: 6
          PYTHONUTF8: 1
          DD_SERVICE: rasa
          DD_ARGS: --ddtrace --ddtrace-patch-all --junitxml=unit-tests-results.xml
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          HUGGINGFACE_HUB_CACHE_DIR: ${{ github.workspace }}/models
          GLINER_MODEL_PATH: ${{ github.workspace }}/models
          TRANSFORMERS_OFFLINE: 0
          HF_TOKEN: ${{ secrets.HUGGINGFACE_API_KEY }}
        run: |
          make test-anonymization
        shell: bash # bash shell is a way to make code run for both Linux and Windows

      - name: Prepare test results
        if: always()
        run: mv coverage.xml ${{ github.workspace }}/unit-tests-results-test-anonymization-python-${{ matrix.python-version }}.xml

      - name: Save Test Results
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
            name: unit-tests-results-test-anonymization-python-${{ matrix.python-version }}
            path: |
              ${{ github.workspace }}/unit-tests-results-test-anonymization-python-${{ matrix.python-version }}.xml


  run-test-to-monitor-memory-consumption-and-display-on-PR:
    name: Run test to monitor memory consumption and display on PR
    runs-on: ubuntu-24.04
    needs: rasa-private-dev-docker-image
    if: ${{ inputs.full_ci_mode != 'false' && github.event_name == 'pull_request' }}
    timeout-minutes: 30
    env:
      RASA_IMAGE_TAG: ${{ needs.rasa-private-dev-docker-image.outputs.rasa_image_tag }}

    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Python Environment
        uses: ./.github/actions/setup-python-env
        with:
          PYTHON_VERSION: ${{ env.DEFAULT_PYTHON_VERSION }}

      - name: Download image artifact
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e #v4.2.1
        with:
          name: docker-image-${{ needs.rasa-private-dev-docker-image.outputs.rasa_image_tag }}.tar.gz

      - name: Load Docker image
        run: |
          gunzip -c image-${{ needs.rasa-private-dev-docker-image.outputs.rasa_image_tag }}.tar.gz | docker load

      - name: Create tmp directory
        run: |
          mkdir /tmp/rasa-memory-test

      - name: Run rasa init and rasa train consumption test
        uses: ./.github/actions/rasa-memory-consumption-test
        id: read-max-rss
        with:
            RASA_IMAGE_TAG: ${{ env.RASA_IMAGE_TAG }}
            RASA_PRO_DEV_REPOSITORY: ${{ env.RASA_PRO_DEV_REPOSITORY }}
            RASA_PRO_LICENSE: ${{ secrets.RASA_PRO_LICENSE }}
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Display max memory consumption
        uses: marocchino/sticky-pull-request-comment@52423e01640425a022ef5fd42c6fb5f633a02728 #v2.9.1
        if: github.event_name == 'pull_request' && success()
        with:
          header: memory consumption for rasa init and rasa train
          recreate: true
          message: |
            🎉 The maximum resident set size (memory consumption) during `rasa init` is **${{ steps.read-max-rss.outputs.max_rss_mb }} MB**.
            🎉 The maximum resident set size (memory consumption) during `rasa train` is **${{ steps.read-max-rss.outputs.max_rss_train_mb }} MB**.

      - name: Remove tmp directory
        if: always()
        run: |
            rm -rf /tmp/rasa-memory-test


  publish-test-results:
    runs-on: ubuntu-24.04
    if: ${{ inputs.full_ci_mode != 'false' }}
    needs: [ tracing-integration-test,
             metric-integration-test,
             enterprise-search-integration-tests,
             custom-action-integration-tests,
             sequential-integration-test,
             non-sequential-integration-test,
             concurrent-lockstore-integration-test,
             broker_integration_test,
             channel_connector_integration_tests,
             unit-test, test-anonymization ]
    steps:
      - name: Download test reports
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e #v4.2.1
        with:
          path: artifacts

      - name: Publish integration test results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@afb2984f4d89672b2f9d9c13ae23d53779671984 # v2.19.0
        with:
          files: "artifacts/**/integration-results-*.xml"
          check_name: "Integration Test Results"

  sonarqube:
    name: SonarQube
    runs-on: ubuntu-24.04
    needs: [ unit-test, test-anonymization ]
     # We don't want to run the code quality checks on scheduled runs
    if: ${{ inputs.full_ci_mode != 'false' && !cancelled() }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis, removing this messes with PR analysis

      - name: Download test reports
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e #v4.2.1
        with:
          path: ${{ github.workspace }}/artifacts
          pattern: "unit-tests-results-**"
          merge-multiple: true

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@1a6d90ebcb0e6a6b1d87e37ba693fe453195ae25 # v5.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.RASABOT_GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  clean-docker-image-artifact:
    name: Clean docker image artifact
    if: success()
    runs-on: ubuntu-24.04
    needs:
      - train-templates-dev
      - rasa-private-dev-docker-image
      - rasa-private-dev-train-the-model
      - deploy-rasa-private-helm-chart
      - tracing-integration-test
      - metric-integration-test
      - custom-action-integration-tests
      - enterprise-search-integration-tests
      - channel_connector_integration_tests

    steps:
      - uses: geekyeggo/delete-artifact@f275313e70c08f6120db482d7a6b98377786765b # v5.1.0
        with:
          failOnError: false
          name: |
            docker-image-*
            template-artifacts
