name: Build and Push Custom Rasa Image

on:
  push:
    branches:
      - 3.6.x
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorys
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Read Poetry Version
        run: |
          echo "POETRY_VERSION=$(scripts/poetry-version.sh)" >> $GITHUB_ENV
        shell: bash

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker base image
        run: |
          docker buildx bake \
            --set base.args.GH_OWNER=${GITHUB_REPOSITORY_OWNER,,} \
            --set base.args.IMAGE_TAG=localdev \
            -f docker/docker-bake.hcl base --push

      - name: Push Docker mitie base image
        run: |
          docker buildx bake \
            --set base-mitie.args.GH_OWNER=${GITHUB_REPOSITORY_OWNER,,} \
            --set base-mitie.args.IMAGE_TAG=localdev \
            -f docker/docker-bake.hcl base-mitie --push

      - name: Push Docker poetry base image
        run: |
          docker buildx bake \
            --set base-poetry.args.GH_OWNER=${GITHUB_REPOSITORY_OWNER,,} \
            --set base-poetry.args.IMAGE_TAG=localdev \
            -f docker/docker-bake.hcl base-poetry --push

      - name: Push Docker builder base image
        run: |
          docker buildx bake \
            --set base-builder.args.GH_OWNER=${GITHUB_REPOSITORY_OWNER,,} \
            --set base-builder.args.IMAGE_TAG=localdev \
            -f docker/docker-bake.hcl base-builder --push

      - name: Build and push full Rasa image
        run: |
          docker buildx bake \
            --set default.args.GH_OWNER=${GITHUB_REPOSITORY_OWNER,,} \
            --set default.args.IMAGE_TAG=localdev \
            -f docker/docker-bake.hcl default --push