name: DUT and E2E MCP and A2A tests

on:
  workflow_dispatch:
    inputs:
      calm-benchmarking-bot-branch:
        description: "calm-benchmarking-branch containing the mock MCP and A2A servers, bot data, and the DUT and E2E tests to run"
        required: false
        default: main

  pull_request:
    paths:
      - "rasa/agents/**"
      - "rasa/dialogue_understanding/**"
      - "rasa/engine/**"
      - "rasa/core/**/*agent*.py"
      - "rasa/cli/**/train.py"
      - "rasa/core/policies/flows/**"
      - "rasa/shared/agents/**"
      - "rasa/shared/core/**"
      - "rasa/shared/engine/**"
      - "rasa/shared/utils/mcp/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RASA_PRO_LICENSE: ${{ secrets.RASA_PRO_LICENSE }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  RASA_PRO_BETA_PREDICATES_IN_RESPONSE_CONDITIONS: true
  CALM_BENCHMARKING_BOT_READ_TOKEN: ${{ secrets.CALM_BENCH_CLONE }}
  AWS_REGION_NAME: us-east-1
  DEFAULT_PYTHON_VERSION: "3.10"

permissions:
  id-token: write
  contents: read

jobs:
  e2e_mcp_tests:
    runs-on: warp-ubuntu-latest-x64-2x
    strategy:
      fail-fast: false
      matrix:
        model:
          - openai
          - claude-sonnet-4-5-20250929 # Accessed via AWS Bedrock
        command-generator:
          - compact
          - search-ready
        test-type:
          - tool-calling-structured-content
          - tool-calling-unstructured-content
          - tool-calling-meta-param-support
          - open-agent
          - task-agent
        exclude:
          - model: claude-sonnet-4-5-20250929
            command-generator: search-ready

            # Only a single MCP meta-param-support e2e test is required, so exclude from running with
            # combinations involving different models and command-generators.
          - model: claude-sonnet-4-5-20250929
            test-type: tool-calling-meta-param-support
          - test-type: tool-calling-meta-param-support
            command-generator: search-ready
    name: MCP-${{ matrix.test-type }} ${{ matrix.model }} ${{ matrix.command-generator }}-CMD-gen
    steps:
      - name: Checkout `rasa-private` git repository 🕝
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Checkout `calm-benchmarking-bot` git repository 🕝
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: RasaHQ/calm-benchmarking-bot
          path: calm-benchmarking-bot
          ref: ${{ inputs.calm-benchmarking-bot-branch || 'main' }}
          token: ${{ env.CALM_BENCHMARKING_BOT_READ_TOKEN }}
      - name: Setup Python and install rasa-pro
        uses: ./.github/actions/setup-python-env
        with:
          PYTHON_VERSION: ${{ env.DEFAULT_PYTHON_VERSION }}
          RASA_DEFAULT_INSTALLATION_ONLY: false
          OPTIONAL_GROUP_TO_INSTALL: channels
      - name: Run mock MCP finance server
        working-directory: calm-benchmarking-bot
        run: make run-finnhub-mock-mcp-server > mcp-server-logs.txt 2>&1 &
      - name: Verify mock MCP server is up and healthy
        run: curl -v --retry 7 --retry-all-errors http://127.0.0.1:8000/mcp/
      - name: Configure AWS credentials
        if: ${{ matrix.model == 'claude-sonnet-4-5-20250929' }}
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 #v4.1.0
        with:
          role-to-assume: arn:aws:iam::307946638045:role/GitHubAction-BedrockAndSagemakerAccess
          aws-region: ${{ env.AWS_REGION_NAME }}
      - name: Train model
        working-directory: calm-benchmarking-bot
        env:
          MOCK_MCP_CONFIG_FILE: ${{ github.workspace }}/data/test_e2e_mcp_config/${{ matrix.command-generator }}-config.yml
          MOCK_MCP_ENDPOINTS_FILE: ${{ github.workspace }}/data/test_e2e_mcp_config/${{ matrix.model }}-endpoints.yml
        run: make train-with-mock-mcp-sub-agent
      - name: E2E tests
        uses: nick-fields/retry@3f757583fb1b1f940bc8ef4bf4734c8dc02a5847 #v3.0.0
        env:
          MOCK_MCP_ENDPOINTS_FILE: ${{ github.workspace }}/data/test_e2e_mcp_config/${{ matrix.model }}-endpoints.yml
          MOCK_MCP_META_ENDPOINTS_FILE: ${{ github.workspace }}/data/test_e2e_mcp_config/endpoints-with-meta-param-support.yml
          TEST_TYPE: ${{ matrix.test-type }}
          AGENT_CLIENT_ID: google-id-123
          AGENT_CLIENT_SECRET: dummy-google-secret
        with:
          timeout_minutes: 60
          max_attempts: 2
          shell: bash
          command: |
            set -Eeuxov pipefail
            cd calm-benchmarking-bot
            if [[ ! -d tests ]]; then
              mkdir tests;
            fi
            (make e2e-test-mock-mcp-"${TEST_TYPE}" 2>&1 | tee e2e-logs) \
            || (grep -iE 'APITimeoutError|ProviderClientAPIException|BedrockException' e2e-logs \
              && echo "::warning::E2E tests failed due to external/3rd-party service issues (non-blocking)")
      - name: Save E2E test results
        if: failure()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: ${{ matrix.test-type }}-e2e-results-${{ matrix.command-generator }}-${{ matrix.model }}
          path: calm-benchmarking-bot/tests/e2e_results_failed.yml
      - name: Save MCP server logs
        if: failure()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: mcp-server-logs-${{ matrix.test-type }}-${{ matrix.command-generator }}-${{ matrix.model }}
          path: calm-benchmarking-bot/mcp-server-logs.txt

  e2e_a2a_tests:
    runs-on: warp-ubuntu-latest-x64-2x
    strategy:
      fail-fast: false
      matrix:
        model:
          - openai
          - claude-sonnet-4-5-20250929 # Accessed via AWS Bedrock
        command-generator:
          - compact
          - search-ready
        test-type:
          - happy-path
          - digressions
          - cancellations
        exclude:
          - model: claude-sonnet-4-5-20250929
            command-generator: search-ready
    name: A2A ${{ matrix.test-type }} ${{ matrix.model }} ${{ matrix.command-generator }}-CMD-gen
    steps:
      - name: Checkout `rasa-private` git repository 🕝
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Checkout `calm-benchmarking-bot` git repository 🕝
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: RasaHQ/calm-benchmarking-bot
          ref: ${{ inputs.calm-benchmarking-bot-branch || 'main' }}
          path: calm-benchmarking-bot
          token: ${{ env.CALM_BENCHMARKING_BOT_READ_TOKEN }}
      - name: Setup Python and install rasa-pro
        uses: ./.github/actions/setup-python-env
        with:
          PYTHON_VERSION: ${{ env.DEFAULT_PYTHON_VERSION }}
          RASA_DEFAULT_INSTALLATION_ONLY: false
          OPTIONAL_GROUP_TO_INSTALL: channels
      - name: Install UV
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 #v4.1.0
        with:
          role-to-assume: arn:aws:iam::307946638045:role/GitHubAction-BedrockAndSagemakerAccess
          aws-region: ${{ env.AWS_REGION_NAME }}
      - name: Run mock A2A Crypto-assistant server
        working-directory: calm-benchmarking-bot
        run: make run-crypto-ramp-mock-a2a-server > a2a-server-logs.txt 2>&1 &
      - name: Verify mock A2A agent server is healthy
        run: curl -v --retry 7 --retry-all-errors http://localhost:9000/.well-known/agent-card.json
      - name: Train model
        working-directory: calm-benchmarking-bot
        env:
          MOCK_A2A_CONFIG_FILE: ${{ github.workspace }}/data/test_e2e_a2a_config/${{ matrix.command-generator }}-config.yml
          MOCK_A2A_ENDPOINTS_FILE: ${{ github.workspace }}/data/test_e2e_a2a_config/${{ matrix.model }}-endpoints.yml
        run: |
          rasa train \
            -c ${MOCK_A2A_CONFIG_FILE} \
            -d mock_a2a_server/domain \
            --data mock_a2a_server/data \
            --endpoints ${MOCK_A2A_ENDPOINTS_FILE} \
            --sub-agents test_e2e_a2a_sub_agents \
            --debug
      - name: E2E tests
        uses: nick-fields/retry@3f757583fb1b1f940bc8ef4bf4734c8dc02a5847 #v3.0.0
        env:
          MOCK_A2A_ENDPOINTS_FILE: ${{ github.workspace }}/data/test_e2e_a2a_config/${{ matrix.model }}-endpoints.yml
          TEST_TYPE: ${{ matrix.test-type }}
        with:
          timeout_minutes: 60
          retry_wait_seconds: 60
          max_attempts: 2
          shell: bash
          command: |
            set -Eeuxov pipefail
            cd "${GITHUB_WORKSPACE}"/calm-benchmarking-bot
            if [[ ! -d tests ]]; then
              mkdir tests;
            fi
            (make e2e-test-mock-a2a-agent-"${TEST_TYPE}" 2>&1 | tee e2e-logs) \
            || (grep -iE 'APITimeoutError|ProviderClientAPIException|BedrockException' e2e-logs \
              && echo "::warning::E2E tests failed due to external/3rd-party service issues (non-blocking)")
          # Restart mock A2A agent to clear conversation history, before re-running test(s)
          on_retry_command: |
            set -Eeuxv
            killall python || killall make
            cd "${GITHUB_WORKSPACE}"/calm-benchmarking-bot
            docker compose -f mock_a2a_server/crypto-ramp-mock-api-docker-compose-.yml down -v --remove-orphans --rmi all
            make run-crypto-ramp-mock-a2a-server >> a2a-server-logs.txt 2>&1 &
            curl -v --retry 7 --retry-all-errors http://localhost:9000/.well-known/agent-card.json
          new_command_on_retry: |
            set -Eeuxv pipefail
            cd "${GITHUB_WORKSPACE}"/calm-benchmarking-bot
            for failed_test in $(yq '.test_results[].error_path' tests/e2e_results_failed.yml);
            do
              (rasa test e2e "${failed_test%:*}" \
                --e2e-results \
                --endpoints "${MOCK_A2A_ENDPOINTS_FILE}" \
                --sub-agents test_e2e_a2a_sub_agents \
                --debug \
                2>&1 | tee e2e-logs) || (grep -iE 'APITimeoutError|ProviderClientAPIException|BedrockException' e2e-logs \
              && echo "::warning::E2E tests failed due to external/3rd-party service issues (non-blocking)")
            done
      - name: Save E2E test results
        if: failure()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: a2a-e2e-results-${{ matrix.command-generator }}-${{ matrix.model }}-${{ matrix.test-type }}
          path: calm-benchmarking-bot/tests/e2e_results_failed.yml
      - name: Save A2A server logs
        if: failure()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: a2a-server-logs-${{ matrix.command-generator }}-${{ matrix.model }}-${{ matrix.test-type }}
          path: calm-benchmarking-bot/a2a-server-logs.txt

  # Pipeline to test - via one happy-path E2E - MCP agent with major LLM providers in
  # `agent.configuration.llm`, as providers-e2e-tests pipeline does not cover this aspect.
  e2e_mcp_provider_test:
    runs-on: warp-ubuntu-latest-x64-2x
    services:
      redis:
        image: redis:6
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    strategy:
      fail-fast: false
      matrix:
        agent_llm_provider:
          - azure
          - bedrock
    steps:
      - name: Checkout `rasa-private` git repository 🕝
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Checkout `calm-benchmarking-bot` git repository 🕝
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: RasaHQ/calm-benchmarking-bot
          path: calm-benchmarking-bot
          ref: ${{ inputs.calm-benchmarking-bot-branch || 'main' }}
          token: ${{ env.CALM_BENCHMARKING_BOT_READ_TOKEN }}
      - name: Setup Python and install rasa-pro
        uses: ./.github/actions/setup-python-env
        with:
          PYTHON_VERSION: ${{ env.DEFAULT_PYTHON_VERSION }}
          RASA_DEFAULT_INSTALLATION_ONLY: false
          OPTIONAL_GROUP_TO_INSTALL: channels
      - name: Run mock MCP finance server
        working-directory: calm-benchmarking-bot
        run: make run-finnhub-mock-mcp-server > mcp-server-logs.txt 2>&1 &
      - name: Verify mock MCP server is up and healthy
        run: curl -v --retry 7 --retry-all-errors http://127.0.0.1:8000/mcp/
      - name: Configure AWS credentials
        if: ${{ matrix.agent_llm_provider == 'bedrock' }}
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 #v4.1.0
        with:
          role-to-assume: arn:aws:iam::307946638045:role/GitHubAction-BedrockAndSagemakerAccess
          aws-region: ${{ env.AWS_REGION_NAME }}
      - name: Configure Azure credentials
        if: ${{ matrix.agent_llm_provider == 'azure' }}
        env:
          AZURE_DEPLOYMENT_GPT5_2_CSE: "gpt-5.2"
          AZURE_API_BASE_GPT5_2_CSE: "https://ai-csetestingeastus2046236386455.cognitiveservices.azure.com/"
          AZURE_API_VERSION_GPT5_2_CSE: "2024-12-01-preview"
          AZURE_API_KEY_ENGINE: ${{ secrets.AZURE_API_KEY_ENGINE }}
          AZURE_DEPLOYMENT_GPT5_2_ENGINE: "gpt-5.2"
          AZURE_API_BASE_GPT5_2_ENGINE: "https://engine-squad-testing.openai.azure.com/"
          AZURE_API_VERSION_GPT5_2_ENGINE: "2024-12-01-preview"
          AZURE_API_KEY_CSE: ${{ secrets.AZURE_API_KEY_CSE }}
          REDIS_HOST: localhost
          REDIS_PORT: 6379
        run: |
          echo "AZURE_DEPLOYMENT_GPT5_2_CSE=${AZURE_DEPLOYMENT_GPT5_2_CSE}" >> "${GITHUB_ENV}"
          echo "AZURE_API_BASE_GPT5_2_CSE=${AZURE_API_BASE_GPT5_2_CSE}" >> "${GITHUB_ENV}"
          echo "AZURE_API_VERSION_GPT5_2_CSE=${AZURE_API_VERSION_GPT5_2_CSE}" >> "${GITHUB_ENV}"
          echo "AZURE_API_KEY_ENGINE=${AZURE_API_KEY_ENGINE}" >> "${GITHUB_ENV}"
          echo "AZURE_DEPLOYMENT_GPT5_2_ENGINE=${AZURE_DEPLOYMENT_GPT5_2_ENGINE}" >> "${GITHUB_ENV}"
          echo "AZURE_API_BASE_GPT5_2_ENGINE=${AZURE_API_BASE_GPT5_2_ENGINE}" >> "${GITHUB_ENV}"
          echo "AZURE_API_VERSION_GPT5_2_ENGINE=${AZURE_API_VERSION_GPT5_2_ENGINE}" >> "${GITHUB_ENV}"
          echo "AZURE_API_KEY_CSE=${AZURE_API_KEY_CSE}" >> "${GITHUB_ENV}"
          echo "REDIS_HOST=${REDIS_HOST}" >> "${GITHUB_ENV}"
          echo "REDIS_PORT=${REDIS_PORT}" >> "${GITHUB_ENV}"
      - name: Train model
        working-directory: calm-benchmarking-bot
        env:
          MOCK_MCP_CONFIG_FILE: ${{ github.workspace }}/data/test_e2e_mcp_config/compact-config.yml
          MOCK_MCP_ENDPOINTS_FILE: ${{ github.workspace }}/data/test_e2e_mcp_config/agent_llm_provider/${{ matrix.agent_llm_provider }}/sub_agents/mcp_agent/endpoints.yml
          MOCK_MCP_SUB_AGENTS_DIRECTORY: ${{ github.workspace }}/data/test_e2e_mcp_config/agent_llm_provider/${{ matrix.agent_llm_provider }}/sub_agents
        run: make train-with-mock-mcp-sub-agent
      - name: E2E tests
        uses: nick-fields/retry@3f757583fb1b1f940bc8ef4bf4734c8dc02a5847 #v3.0.0
        env:
          MOCK_MCP_ENDPOINTS_FILE: ${{ github.workspace }}/data/test_e2e_mcp_config/agent_llm_provider/${{ matrix.agent_llm_provider }}/sub_agents/mcp_agent/endpoints.yml
          MOCK_MCP_SUB_AGENTS_DIRECTORY: ${{ github.workspace }}/data/test_e2e_mcp_config/agent_llm_provider/${{ matrix.agent_llm_provider }}/sub_agents
          AGENT_CLIENT_ID: google-id-123
          AGENT_CLIENT_SECRET: dummy-google-secret
        with:
          timeout_minutes: 60
          max_attempts: 2
          shell: bash
          command: |
            set -Eeuxov pipefail
            cd calm-benchmarking-bot
            if [[ ! -d tests ]]; then
              mkdir tests;
            fi
            rasa test e2e e2e/e2e_tests_with_assertions/mock_mcp/agents/open_ended/happy_path/conduct_company_finance_research.yml \
              --e2e-results --endpoints "${MOCK_MCP_ENDPOINTS_FILE}" \
              --sub-agents "${MOCK_MCP_SUB_AGENTS_DIRECTORY}" \
              --debug \
              2>&1 \
              | tee e2e-log \
              || (grep -iE 'APITimeoutError|ProviderClientAPIException|BedrockException' e2e-log \
              && echo "::warning::E2E test failed due to external/3rd-party service issues (non-blocking)")
      - name: Save E2E test results
        if: failure()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: e2e-results-${{ matrix.agent_llm_provider }}
          path: calm-benchmarking-bot/tests/e2e_results_failed.yml
      - name: Save MCP server logs
        if: failure()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: mcp-server-logs-${{ matrix.agent_llm_provider }}
          path: calm-benchmarking-bot/mcp-server-logs.txt

  DUT_mcp:
    runs-on: warp-ubuntu-latest-x64-2x
    strategy:
      fail-fast: false
      matrix:
        model:
          - openai
          - claude-sonnet-4-5-20250929 # Accessed via AWS Bedrock
        command-generator:
          - compact
          - search-ready
        exclude:
          - model: claude-sonnet-4-5-20250929
            command-generator: search-ready
    steps:
      - name: Checkout `rasa-private` git repository 🕝
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Checkout `calm-benchmarking-bot` git repository 🕝
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: RasaHQ/calm-benchmarking-bot
          path: calm-benchmarking-bot
          ref: ${{ inputs.calm-benchmarking-bot-branch || 'main' }}
          token: ${{ env.CALM_BENCHMARKING_BOT_READ_TOKEN }}
      - name: Setup Python and install rasa-pro
        uses: ./.github/actions/setup-python-env
        with:
          PYTHON_VERSION: ${{ env.DEFAULT_PYTHON_VERSION }}
          RASA_DEFAULT_INSTALLATION_ONLY: false
          OPTIONAL_GROUP_TO_INSTALL: channels
      - name: Run mock MCP finance server
        working-directory: calm-benchmarking-bot
        run: make run-finnhub-mock-mcp-server > mcp-server-logs.txt 2>&1 &
      - name: Verify mock MCP server is up and healthy
        run: curl -v --retry 7 --retry-all-errors http://127.0.0.1:8000/mcp/
      - name: Configure AWS credentials
        if: ${{ matrix.model == 'claude-sonnet-4-5-20250929' }}
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 #v4.1.0
        with:
          role-to-assume: arn:aws:iam::307946638045:role/GitHubAction-BedrockAndSagemakerAccess
          aws-region: ${{ env.AWS_REGION_NAME }}
      - name: Train model
        working-directory: calm-benchmarking-bot
        env:
          MOCK_MCP_CONFIG_FILE: ${{ github.workspace }}/data/test_e2e_mcp_config/${{ matrix.command-generator }}-config.yml
          MOCK_MCP_ENDPOINTS_FILE: ${{ github.workspace }}/data/test_e2e_mcp_config/${{ matrix.model }}-endpoints.yml
        run: make train-with-mock-mcp-sub-agent
      - name: Run DUTs
        uses: nick-fields/retry@3f757583fb1b1f940bc8ef4bf4734c8dc02a5847 #v3.0.0
        env:
          MOCK_MCP_ENDPOINTS_FILE: ${{ github.workspace }}/data/test_e2e_mcp_config/${{ matrix.model }}-endpoints.yml
          AGENT_CLIENT_ID: google-id-123
          AGENT_CLIENT_SECRET: dummy-google-secret
          RASA_PRO_BETA_DIALOGUE_UNDERSTANDING_TEST: true
        with:
          timeout_minutes: 60
          max_attempts: 2
          shell: bash
          command: |
            set -Eeuxov pipefail
            cd "${GITHUB_WORKSPACE}"/calm-benchmarking-bot
            make dut-mcp
      - name: Save DUT results
        if: failure()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: dut-results-${{ matrix.command-generator }}-${{ matrix.model }}
          path: calm-benchmarking-bot/dialogue_understanding_test*.yml
      - name: Save MCP server logs
        if: failure()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: mcp-server-logs-${{ matrix.command-generator }}-${{ matrix.model }}
          path: calm-benchmarking-bot/mcp-server-logs.txt

  DUT_a2a:
    runs-on: warp-ubuntu-latest-x64-2x
    strategy:
      fail-fast: false
      matrix:
        model:
          - openai
          - claude-sonnet-4-5-20250929 # Accessed via AWS Bedrock
        command-generator:
          - compact
          - search-ready
        exclude:
          - model: claude-sonnet-4-5-20250929
            command-generator: search-ready
    steps:
      - name: Checkout `rasa-private` git repository 🕝
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Checkout `calm-benchmarking-bot` git repository 🕝
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: RasaHQ/calm-benchmarking-bot
          ref: ${{ inputs.calm-benchmarking-bot-branch || 'main' }}
          path: calm-benchmarking-bot
          token: ${{ env.CALM_BENCHMARKING_BOT_READ_TOKEN }}
      - name: Setup Python and install rasa-pro
        uses: ./.github/actions/setup-python-env
        with:
          PYTHON_VERSION: ${{ env.DEFAULT_PYTHON_VERSION }}
          RASA_DEFAULT_INSTALLATION_ONLY: false
          OPTIONAL_GROUP_TO_INSTALL: channels
      - name: Install UV
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 #v4.1.0
        with:
          role-to-assume: arn:aws:iam::307946638045:role/GitHubAction-BedrockAndSagemakerAccess
          aws-region: ${{ env.AWS_REGION_NAME }}
      - name: Run mock A2A Crypto-assistant server
        working-directory: calm-benchmarking-bot
        run: make run-crypto-ramp-mock-a2a-server > a2a-server-logs.txt 2>&1 &
      - name: Verify mock A2A agent server is healthy
        run: curl -v --retry 7 --retry-all-errors http://localhost:9000/.well-known/agent-card.json
      - name: Train model
        working-directory: calm-benchmarking-bot
        env:
          MOCK_A2A_CONFIG_FILE: ${{ github.workspace }}/data/test_e2e_a2a_config/${{ matrix.command-generator }}-config.yml
          MOCK_A2A_ENDPOINTS_FILE: ${{ github.workspace }}/data/test_e2e_a2a_config/${{ matrix.model }}-endpoints.yml
        run: |
          rasa train \
            -c ${MOCK_A2A_CONFIG_FILE} \
            -d mock_a2a_server/domain \
            --data mock_a2a_server/data \
            --endpoints ${MOCK_A2A_ENDPOINTS_FILE} \
            --sub-agents test_e2e_a2a_sub_agents \
            --debug
      - name: Run DUTs
        uses: nick-fields/retry@3f757583fb1b1f940bc8ef4bf4734c8dc02a5847 #v3.0.0
        env:
          MOCK_A2A_ENDPOINTS_FILE: ${{ github.workspace }}/data/test_e2e_a2a_config/${{ matrix.model }}-endpoints.yml
          RASA_PRO_BETA_DIALOGUE_UNDERSTANDING_TEST: true
        with:
          timeout_minutes: 60
          retry_wait_seconds: 60
          max_attempts: 2
          shell: bash
          command: |
            set -Eeuxov pipefail
            cd "${GITHUB_WORKSPACE}"/calm-benchmarking-bot
            make dut-a2a
          # Restart mock A2A agent to clear conversation history, before re-running test(s)
          on_retry_command: |
            set -Eeuxv
            killall python || killall make
            cd "${GITHUB_WORKSPACE}"/calm-benchmarking-bot
            docker compose -f mock_a2a_server/crypto-ramp-mock-api-docker-compose-.yml down -v --remove-orphans --rmi all
            make run-crypto-ramp-mock-a2a-server >> a2a-server-logs.txt 2>&1 &
            curl -v --retry 7 --retry-all-errors http://localhost:9000/.well-known/agent-card.json
      - name: Save DUT results
        if: failure()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: a2a-dut-results-${{ matrix.command-generator }}-${{ matrix.model }}
          path: calm-benchmarking-bot/dialogue_understanding_test*.yml
      - name: Save A2A server logs
        if: failure()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: a2a-server-logs-${{ matrix.command-generator }}-${{ matrix.model }}
          path: calm-benchmarking-bot/a2a-server-logs.txt
