name: CI On Pull Request Closure
on:
  pull_request:
    types: [closed]

env:
  AWS_REGION: eu-west-1

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  aws-ecr:
    # Skip any PR created by dependabot to avoid permission issues
    if: (github.actor != 'dependabot[bot]')
    name: Delete PR docker images
    runs-on: ubuntu-24.04
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 #v4.1.0
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 #v2.0.1

      - name: Remove docker images from all ECR repositories
        run: |
          REPO_NAMES=("rasa/rasa-private-dev")
          SEARCH_STRING="pr${{ github.event.number }}"
          # Iterate through each repository
          for REPO_NAME in "${REPO_NAMES[@]}"
          do
            # List all image tags in the repository that match the search string
            # Escape empty strings and null character
            IMAGES=$(aws ecr list-images --repository-name $REPO_NAME --query "imageIds[?imageTag!=null&&imageTag!=''&&contains(imageTag, '$SEARCH_STRING')].imageTag" --output text)

            # Print the image tags
            echo "Images to be deleted in repository $REPO_NAME:"
            echo "$IMAGES"
            # Delete each image by its tag
            for IMAGE in $IMAGES
            do
              aws ecr batch-delete-image --repository-name $REPO_NAME --image-ids imageTag=$IMAGE
            done
          done

  pulumi-destroy:
    # Skip any PR created by dependabot to avoid permission issues
    # Skip this job from merge queue
    # Skip from Backport PRs
    if: github.event_name != 'merge_group' && !startsWith(github.event.pull_request.title, 'Backport' && github.actor != 'dependabot[bot]')
    name: Destroy pulumi resources
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set stack name
        run: |
          if [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
            echo "STACK_NAME=pr-${{ github.event.number }}" >> $GITHUB_ENV
          else
            echo "STACK_NAME=$(echo "${GITHUB_REF##*/}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@8c3f20df09ac63af7b3ae3d7c91f105f857d8497 # v3.0.1
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}  

      - name: Set up kubeconfig
        run: |
          aws eks update-kubeconfig --name rasa-pro-cluster --region ${{ env.AWS_REGION }}

      
      - uses: pulumi/actions@ae8c5623fbcf1b4781618a60e69d423f9a6b9c92 #v5.1.1
      - name: Destroy resources and remove the stack
        run: |
          pulumi destroy -s rasa/rasa-pro-eks-helm/${{ env.STACK_NAME }} --yes
          pulumi stack rm rasa/rasa-pro-eks-helm/${{ env.STACK_NAME }} --yes
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.HELM_DEPLOY_PULUMI_ACCESS_TOKEN }}
