name: E2E Test on Rasa-Calm-Demo with supported providers

on:
  schedule:
    # Run at 1am UTC each Sunday
    - cron: "0 1 * * SUN"

  # Allow running manually also, specifying the provider
  # and `rasa-calm-demo` branch
  workflow_dispatch:
    inputs:
      provider:
        # In-case provider only has supported model for one
        # (for e.g. only chat-completion), then default OpenAI
        # would be used for the other
        description: "LLM chat-completion and Embeddings model provider"
        type: choice
        required: true
        default: "all" # Run e2e-test on all providers by default

        options:
          - all
          - openai
          - azure
          - bedrock
          - gemini
          - huggingface
          - huggingface_local
          - anthropic
          # - cohere TODO: Enable after ENG-1411 is unblocked
          # - mistral TODO: Enable after ENG-1412 is unblocked
          - together_ai
          - groq
          # - voyage TODO: Enable after ENG-1415 is unblocked
          - ollama
          # - self-hosted
          - azure-multiple-deployments-with-routing
          - gemini-multiple-deployments-with-routing
          - huggingface-multiple-deployments-with-routing

      rasa-calm-demo-branch:
        description: "Branch to checkout for `rasa-calm-demo`"
        type: string
        required: true
        default: "main"

      command-generator:
        description: "Command-generator(s) to use: single-step, multi-step or both (1 job for each)"
        type: choice
        required: true
        default: both
        options:
          - single-step
          - multi-step
          - both

      single-step-e2e-test-with-assertions:
        description: "Path to test file, on `rasa-calm-demo` repository, to be run with single-step trained model"
        type: string
        required: true
        # Test on normal Transaction flows, as well as knowledge/enterprise-search included
        default: "e2e_tests_with_assertions/passing/knowledge/user_starts_with_a_knowledge_question.yml"

      multi-step-e2e-test-with-assertions:
        description: "Path to test file, on `rasa-calm-demo` repository, to be run with multi-step trained model"
        type: string
        required: true
        default: "e2e_tests_with_assertions/passing/happy_path/user_checks_balance.yml"

      llm-as-judge-model:
        description: "Judge model (must be from OpenAI) to be used by assertions."
        type: string
        required: true
        default: gpt-4o-mini

    # Enable optionally calling this re-usable Workflow from
    # `release-artifacts-workflow` also, with same input
    # parameters as above
  workflow_call:
    inputs:
      provider:
        # In-case provider only has supported model for one
        # (for e.g. only chat-completion), then default OpenAI
        # would be used for the other
        description: "LLM chat-completion and Embeddings model provider"
        type: string
        required: true
        default: "all" # Run e2e-test on all providers by default
      rasa-calm-demo-branch:
        description: "Branch to checkout for `rasa-calm-demo`"
        type: string
        required: true
        default: "main"
      command-generator:
        description: "Command-generator(s) to use: single-step, multi-step or both (1 job for each)"
        type: string
        required: true
        default: multi-step # TODO: Change to 'both', after test failures are resolved
      single-step-e2e-test-with-assertions:
        description: "Path to test file, on `rasa-calm-demo` repository"
        type: string
        required: true
        # Test on normal Transaction flows, as well as knowledge/enterprise-search included
        default: "e2e_tests_with_assertions/passing/knowledge/user_starts_with_a_knowledge_question.yml"
      multi-step-e2e-test-with-assertions:
        description: "Path to test file, on `rasa-calm-demo` repository"
        type: string
        required: true
        default: "e2e_tests_with_assertions/passing/happy_path/user_checks_balance.yml"
      llm-as-judge-model:
        description: "Judge model (must be from OpenAI) to be used by assertions."
        type: string
        required: true
        default: gpt-4o-mini
  pull_request:
    branches: main
    paths: [pyproject.toml, rasa/shared/providers/**]

env:
  DEFAULT_PYTHON_VERSION: "3.10"
  RASA_PRO_BETA_E2E_ASSERTIONS: true
  RASA_PRO_BETA_STUB_CUSTOM_ACTION: true
  LOG_LEVEL_LLM: DEBUG
  COMMAND_GENERATOR: ${{ inputs.command-generator || 'multi-step' }} # TODO: Change to 'both', after test failures are resolved
  COMMAND_GENERATOR_MATRIX: '{"single-step": ["singlestep"], "multi-step": ["multistep"], "both": ["singlestep", "multistep"]}'
  ENDPOINTS_FILE_NAME: endpoints
  REDIS_HOST: localhost
  REDIS_PORT: 6379
  RASA_TELEMETRY_DEBUG: true
  DD_API_KEY: ${{ secrets.DD_API_KEY }} # Required for sending OTEL Metrics and Traces to Datadog

  # Providers' required environment variables (API key values also stored in 1Password):
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

  # Azure OpenAI
  AZURE_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY_DEVTRIBE_TESTING_CANADA_EAST }}

  # AWS Bedrock
  AWS_REGION_NAME: us-east-1

  # Gemini - Google AI Studio
  GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
  GEMINI_ALTERNATE_API_KEY: ${{ secrets.GEMINI_ALTERNATE_API_KEY }} # API key for different deployment, to test multi-LLM-routing

  # Anthropic
  ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

  # Hugging Face
  HUGGINGFACE_API_KEY: ${{ secrets.HUGGINGFACE_API_KEY }}

  # Mistral
  MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}

  # Together AI
  TOGETHERAI_API_KEY: ${{ secrets.TOGETHERAI_API_KEY }}

  # Groq
  GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

  # Cohere
  COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}

  # Voyage AI
  VOYAGE_API_KEY: ${{ secrets.VOYAGE_API_KEY }}

  # Ollama
  OLLAMA_API_BASE: http://localhost:11434

  # Azure multi-deployments (for multi-LLM routing):
  LLM_API_HEALTH_CHECK: True

  # Training deployment
  AZURE_DEPLOYMENT_GPT3_5_TURBO: "test-gpt-35-turbo"
  AZURE_API_BASE_GPT3_5_TURBO: "https://engine-testing.openai.azure.com/"
  AZURE_API_VERSION_GPT3_5_TURBO: "2024-02-01"
  AZURE_DEPLOYMENT_TXT_EMBEDDING_ADA: "test-text-embedding-ada-002"
  AZURE_API_BASE_TXT_EMBEDDING_ADA: "https://engine-testing.openai.azure.com/"
  AZURE_API_VERSION_TXT_EMBEDDING_ADA: "2023-05-15"
  AZURE_API_KEY_TRAINING: ${{ secrets.AZURE_OPENAI_API_KEY_ENGINE_TESTING }}

    # Deployment 1
  AZURE_DEPLOYMENT_GPT3_5_TURBO_CA: "test-gpt-35-turbo"
  AZURE_API_BASE_GPT3_5_TURBO_CA: "https://devtribe-testing-canada-east.openai.azure.com/"
  AZURE_API_VERSION_GPT3_5_TURBO_CA: "2024-02-01"
  AZURE_DEPLOYMENT_TXT_EMBEDDING_ADA_CA: "test-text-embedding-ada-002"
  AZURE_API_BASE_TXT_EMBEDDING_ADA_CA: "https://devtribe-testing-canada-east.openai.azure.com"
  AZURE_API_VERSION_TXT_EMBEDDING_ADA_CA: "2023-05-15"
  AZURE_API_KEY_CA: ${{ secrets.AZURE_OPENAI_API_KEY_DEVTRIBE_TESTING_CANADA_EAST }}

    # Deployment 2
  AZURE_DEPLOYMENT_GPT3_5_TURBO_FR: "test-gpt-35-turbo"
  AZURE_API_BASE_GPT3_5_TURBO_FR: "https://devtribe-testing.openai.azure.com/"
  AZURE_API_VERSION_GPT3_5_TURBO_FR: "2024-02-01"
  AZURE_DEPLOYMENT_TXT_EMBEDDING_ADA_FR: "test-text-embedding-ada-002"
  AZURE_API_BASE_TXT_EMBEDDING_ADA_FR: "https://devtribe-testing.openai.azure.com/"
  AZURE_API_VERSION_TXT_EMBEDDING_ADA_FR: "2023-05-15"
  AZURE_API_KEY_FR: ${{ secrets.AZURE_OPENAI_API_KEY_DEVTRIBE_TESTING }}

permissions:
  id-token: write
  contents: read
  pull-requests: read

jobs:
  job_setup:
    runs-on: ubuntu-22.04
    outputs:
      COMMAND_GENERATOR: ${{ env.COMMAND_GENERATOR }}
      COMMAND_GENERATOR_MATRIX: ${{ env.COMMAND_GENERATOR_MATRIX }}
    steps:
      - name: Set command-generator
        run: |
          echo "COMMAND_GENERATOR=${{ env.COMMAND_GENERATOR }}" >> $GITHUB_OUTPUT
          echo "COMMAND_GENERATOR_MATRIX=${{ env.COMMAND_GENERATOR_MATRIX }}" >> $GITHUB_OUTPUT
          echo "${{ fromJson(env.COMMAND_GENERATOR_MATRIX)[env.COMMAND_GENERATOR] }}"

  check_changes_impacting_providers:
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'pull_request' }}
    outputs:
      litellm_upgraded: ${{ steps.check_litellm_upgrade.outcome }}
      openai_upgraded: ${{ steps.check_openai_upgrade.outcome }}
      provider_code_changed: ${{ steps.filter.outputs.providers }}
    steps:
      - name: Checkout git repository 🕝
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          fetch-depth: 0
      - id: filter
        name: Check for changes in `rasa/shared/providers` folder
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50  #v2.11.1
        with:
          filters: .github/change_filters.yml
      - name: Check upgrades to LiteLLM dependency
        continue-on-error: true
        if: ${{ steps.filter.outputs.lock_file == 'true' }}
        id: check_litellm_upgrade
        run: git diff ${{ github.sha }}:pyproject.toml origin/${{ github.base_ref }}:pyproject.toml | grep -e '-litellm\|+litellm2'
      - name: Check upgrades to OpenAI dependency
        continue-on-error: true
        id: check_openai_upgrade
        if: ${{ always() && steps.filter.outputs.lock_file == 'true' }}
        run: git diff ${{ github.sha }}:pyproject.toml origin/${{ github.base_ref }}:pyproject.toml | grep -e '-openai\|+openai'

  e2e_test:
    name: Run e2e Test
    needs: [job_setup, check_changes_impacting_providers]
    if: ${{ always() && (github.event_name == 'schedule' || inputs.provider == 'all' || (needs.check_changes_impacting_providers.outputs.litellm_upgraded == 'success' || needs.check_changes_impacting_providers.outputs.openai_upgraded == 'success' || needs.check_changes_impacting_providers.outputs.provider_code_changed == 'true' )) }}
    runs-on: ubuntu-22.04
    services:
      redis:
        image: redis:6
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    strategy:
      fail-fast: false
      matrix:
        provider: [
            openai,
            azure,
            bedrock,
            gemini,
            huggingface,
            huggingface_local,
            anthropic,
            # cohere, TODO: Enable after ENG-1411 is unblocked
            # mistral, TODO: Enable after ENG-1412 is unblocked
            together_ai,
            groq,
            # voyage, TODO: Enable after ENG-1415 is unblocked
            ollama,
            # self-hosted,
            azure-multiple-deployments-with-routing,
            gemini-multiple-deployments-with-routing,
            huggingface-multiple-deployments-with-routing
          ] # TODO: Enable testing all the providers
        train-and-test: ${{ fromJson(needs.job_setup.outputs.COMMAND_GENERATOR_MATRIX)[needs.job_setup.outputs.COMMAND_GENERATOR] }}
    steps:
      - name: Checkout git repository 🕝
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - name: E2E test
        uses: ./.github/actions/providers-e2e-test
        with:
          provider: ${{ matrix.provider }}
          train-and-test: ${{ matrix.train-and-test }}
          rasa-calm-demo-branch: ${{ inputs.rasa-calm-demo-branch || 'main' }}
          single-step-e2e-test-with-assertions: ${{ inputs.single-step-e2e-test-with-assertions || 'e2e_tests_with_assertions/passing/knowledge/user_starts_with_a_knowledge_question.yml' }}
          multi-step-e2e-test-with-assertions: ${{ inputs.multi-step-e2e-test-with-assertions || 'e2e_tests_with_assertions/passing/happy_path/user_checks_balance.yml' }}
          llm-as-judge-model: ${{ inputs.llm-as-judge-model || 'gpt-4o-mini' }}
          rasa-calm-demo-read-token: ${{ secrets.RASA_CALM_DEMO_READ }}
          rasa-pro-license: ${{ secrets.RASA_PRO_LICENSE }}
          duckling-url: ${{ secrets.DUCKLING_URL }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}

  e2e_test_on_single_provider:
    name: Run e2e Test
    needs: job_setup
    if: ${{ inputs.provider != 'all' && github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-22.04
    services:
      redis:
        image: redis:6
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    strategy:
      fail-fast: false
      matrix:
        train-and-test: ${{ fromJson(needs.job_setup.outputs.COMMAND_GENERATOR_MATRIX)[needs.job_setup.outputs.COMMAND_GENERATOR] }}

    steps:
      - name: Checkout git repository 🕝
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - name: E2E test on single provider
        uses: ./.github/actions/providers-e2e-test
        with:
          provider: ${{ inputs.provider }}
          train-and-test: ${{ matrix.train-and-test }}
          rasa-calm-demo-branch: ${{ inputs.rasa-calm-demo-branch }}
          single-step-e2e-test-with-assertions: ${{ inputs.single-step-e2e-test-with-assertions }}
          multi-step-e2e-test-with-assertions: ${{ inputs.multi-step-e2e-test-with-assertions }}
          llm-as-judge-model: ${{ inputs.llm-as-judge-model }}
          rasa-calm-demo-read-token: ${{ secrets.RASA_CALM_DEMO_READ }}
          rasa-pro-license: ${{ secrets.RASA_PRO_LICENSE }}
          duckling-url: ${{ secrets.DUCKLING_URL }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
