name: E2E Test on Bot with supported CALM providers
run-name: Provider tests on rasa version/branch-head  `${{ inputs.rasa-pro-version != '' && inputs.rasa-pro-version || github.ref_name }}`

on:
  schedule:
    # Run at 1am UTC each Sunday
    - cron: "0 1 * * SUN"

  # Allow running manually also, specifying the provider
  # and Bot branch
  workflow_dispatch:
    inputs:
      provider:
        # In-case provider only has supported model for one
        # (for e.g. only chat-completion), then default OpenAI
        # would be used for the other
        description: "LLM chat-completion and Embeddings model provider"
        type: choice
        required: true
        default: "all" # Run e2e-test on all providers by default

        options:
          - all
          - openai
          - azure
          - azure-oauth
          - bedrock
          - gemini
          - huggingface
          - huggingface_local
          - anthropic
          # - cohere TODO: Enable after ENG-1411 is unblocked
          - mistral
          - together_ai
          - groq
          # - voyage TODO: Enable after ENG-1415 is unblocked
          - ollama
          - self-hosted-vllm
          - self-hosted-llama-cpp
          - azure-multiple-deployments-with-simple-shuffle-routing
          - azure-multiple-deployments-with-least-busy-routing
          - azure-multiple-deployments-with-usage-based-routing
          # - azure-multiple-deployments-with-usage-based-routing-v2 TODO: Enable after ENG-1651 is resolved
          - azure-multiple-deployments-with-latency-based-routing
          - azure-multiple-deployments-with-cost-based-routing
          - gemini-multiple-deployments-with-routing
          # - huggingface-multiple-deployments-with-routing # Disabled as HF inference provider monthly credits exceeded
          - bedrock-multiple-deployments-with-routing
          - sagemaker_chat-multiple-deployments-with-routing
          - litellm-proxy-multiple-deployments-with-routing
          - openai-with-custom-prompt-for-CompactLLMCommandGenerator
          - openai-with-custom-prompt-for-CustomLLMCommandGenerator

      rasa-pro-version:
        description: "Rasa-pro version to run test(s) against. Default: Current commit version"
        type: string
        required: false

      data-repo:
        description: "Bot repository. Ensure provider config files are compatible with data."
        type: choice
        required: true
        default: rasa-calm-demo
        options:
          - rasa-calm-demo
          - calm-benchmarking-bot

      data-repo-branch:
        description: "Branch to checkout for data-repo/bot"
        type: string
        required: true
        default: "main"

      command-generator:
        description: "Command-generator(s) to use: single-step, multi-step, compact, search-ready or all"
        type: choice
        required: true
        default: all
        options:
          - single-step
          - multi-step
          - compact
          - search-ready
          - all

      single-step-e2e-test-with-assertions:
        description: "Path to test file, to be run with single-step trained model"
        type: string
        required: true
        # TODO: Use test that invokes enterprise-search, when flakiness is resolved
        default: "e2e_tests_with_assertions/passing/happy_path/user_checks_balance.yml"

      multi-step-e2e-test-with-assertions:
        description: "Path to test file, to be run with multi-step trained model"
        type: string
        required: true
        default: "e2e_tests_with_assertions/passing/happy_path/user_checks_balance.yml"

      compact-e2e-test-with-assertions:
        description: "Path to test file, to be run with compact-LLM-Generator trained model"
        type: string
        required: true
        default: "e2e_tests_with_assertions/passing/happy_path/user_checks_balance.yml"

      search-ready-e2e-test-with-assertions:
        description: "Path to test file, to be run with search-ready-LLM-Generator trained model"
        type: string
        required: true
        default: "e2e_tests_with_assertions/knowledge_relevancy_check/chitchat_during_flow.yml"

      send-results-notification-to-slack:
        description: "Send results notifications to Slack's #dev-tribe-alerts channel"
        type: boolean
        required: false
        default: false

    # Enable optionally calling this re-usable Workflow from
    # `release-artifacts-workflow` also, with same input
    # parameters as above
  workflow_call:
    inputs:
      provider:
        # In-case provider only has supported model for one
        # (for e.g. only chat-completion), then default OpenAI
        # would be used for the other
        description: "LLM chat-completion and Embeddings model provider"
        type: string
        required: true
      data-repo:
        description: "Bot repository"
        type: string
        required: true
      data-repo-branch:
        description: "Branch to checkout for data-repo/bot"
        type: string
        required: true
      command-generator:
        description: "Command-generator(s) to use: single-step, multi-step, compact, search-ready or all (1 job for each)"
        type: string
        required: true
      single-step-e2e-test-with-assertions:
        description: "Path to test file"
        type: string
        required: true
      multi-step-e2e-test-with-assertions:
        description: "Path to test file"
        type: string
        required: true
      compact-e2e-test-with-assertions:
        description: "Path to test file"
        type: string
        required: true
      search-ready-e2e-test-with-assertions:
        description: "Path to test file"
        type: string
        required: true
  pull_request:
    branches: [main]
    paths: [pyproject.toml, rasa/shared/providers/**]

env:
  DEFAULT_PYTHON_VERSION: "3.11"
  RASA_PRO_BETA_STUB_CUSTOM_ACTION: true
  LOG_LEVEL_LLM: DEBUG
  COMMAND_GENERATOR: ${{ inputs.command-generator || 'all' }}
  COMMAND_GENERATOR_MATRIX: '{"single-step": ["singlestep"], "multi-step": ["multistep"], "compact": ["compact"], "search-ready": ["search-ready"], "all": ["singlestep", "multistep", "compact", "search-ready"]}'
  ENDPOINTS_FILE_NAME: endpoints
  REDIS_HOST: localhost
  REDIS_PORT: 6379
  RASA_TELEMETRY_DEBUG: true
  OTEL_EXPORTER: otlp_grpc
  OTEL_ENDPOINT: http://0.0.0.0:4317
  RASA_PRO_VERSION: ${{ inputs.rasa-pro-version }}
  RASA_PRO_BETA_E2E_ASSERTIONS: ${{ inputs.rasa-pro-version != '' && true || false }}
  API_KEY_NAMES: '{"azure": "AZURE_API_KEY", "gemini": "GEMINI_API_KEY", "huggingface": "HUGGINGFACE_API_KEY", "anthropic": "ANTHROPIC_API_KEY", "together_ai": "TOGETHERAI_API_KEY", "groq": "GROQ_API_KEY", "openai": "OPENAI_API_KEY", "mistral": "MISTRAL_API_KEY", "cohere": "COHERE_API_KEY", "voyage": "VOYAGE_API_KEY"}'
  RASA_PRO_LICENSE: ${{ secrets.RASA_PRO_LICENSE }}
  DUCKLING_URL: ${{ secrets.DUCKLING_URL }}
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  RASA_CALM_DEMO_READ_TOKEN: ${{ secrets.RASA_CALM_DEMO_READ }}
  CALM_BENCHMARKING_BOT_READ_TOKEN: ${{ secrets.CALM_BENCH_CLONE }}
  SEND_RESULTS_NOTIFICATION_TO_SLACK: ${{ github.event_name == 'schedule' && true || inputs.send-results-notification-to-slack }}
  RASA_PRO_BETA_PREDICATES_IN_RESPONSE_CONDITIONS: true

  # Providers' required environment variables (API key values also stored in 1Password):

  # OpenAI
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

   # Hugging Face
  HUGGINGFACE_API_KEY: ${{ secrets.HUGGINGFACE_API_KEY }}

  # AWS Bedrock
  AWS_REGION_NAME: us-east-1

  # Gemini - Google AI Studio
  GEMINI_API_KEY_1: ${{ secrets.GEMINI_API_KEY }}
  GEMINI_API_KEY_2: ${{ secrets.GEMINI_ALTERNATE_API_KEY }} # API key for different deployment, to test multi-LLM-routing

  # Ollama
  OLLAMA_API_BASE: http://localhost:11434

  # Azure multi-deployments (for multi-LLM routing):
  LLM_API_HEALTH_CHECK: True

  # Training deployment
  AZURE_DEPLOYMENT_GPT3_5_TURBO: "test-gpt-35-turbo"
  AZURE_API_BASE_GPT3_5_TURBO: "https://engine-testing.openai.azure.com/"
  AZURE_API_VERSION_GPT3_5_TURBO: "2024-02-01"
  AZURE_DEPLOYMENT_TXT_EMBEDDING_ADA: "test-text-embedding-ada-002"
  AZURE_API_BASE_TXT_EMBEDDING_ADA: "https://engine-testing.openai.azure.com/"
  AZURE_API_VERSION_TXT_EMBEDDING_ADA: "2023-05-15"
  AZURE_API_KEY_TRAINING: ${{ secrets.AZURE_OPENAI_API_KEY_ENGINE_TESTING }}

    # Deployment 1
  AZURE_DEPLOYMENT_GPT3_5_TURBO_CA: "test-gpt-35-turbo"
  AZURE_API_BASE_GPT3_5_TURBO_CA: "https://devtribe-testing-canada-east.openai.azure.com/"
  AZURE_API_VERSION_GPT3_5_TURBO_CA: "2024-02-01"
  AZURE_DEPLOYMENT_TXT_EMBEDDING_ADA_CA: "test-text-embedding-ada-002"
  AZURE_API_BASE_TXT_EMBEDDING_ADA_CA: "https://devtribe-testing-canada-east.openai.azure.com"
  AZURE_API_VERSION_TXT_EMBEDDING_ADA_CA: "2023-05-15"
  AZURE_API_KEY_CA: ${{ secrets.AZURE_OPENAI_API_KEY_DEVTRIBE_TESTING_CANADA_EAST }}

    # Deployment 2
  AZURE_DEPLOYMENT_GPT3_5_TURBO_FR: "test-gpt-35-turbo"
  AZURE_API_BASE_GPT3_5_TURBO_FR: "https://devtribe-testing.openai.azure.com/"
  AZURE_API_VERSION_GPT3_5_TURBO_FR: "2024-02-01"
  AZURE_DEPLOYMENT_TXT_EMBEDDING_ADA_FR: "test-text-embedding-ada-002"
  AZURE_API_BASE_TXT_EMBEDDING_ADA_FR: "https://devtribe-testing.openai.azure.com/"
  AZURE_API_VERSION_TXT_EMBEDDING_ADA_FR: "2023-05-15"
  AZURE_API_KEY_FR: ${{ secrets.AZURE_OPENAI_API_KEY_DEVTRIBE_TESTING }}

    # Deployment 3
  AZURE_DEPLOYMENT_GPT3_5_TURBO_CI_FR: "gpt-35-turbo"
  AZURE_API_BASE_GPT3_5_TURBO_CI_FR: "https://devtribe-ci-france.openai.azure.com/"
  AZURE_API_VERSION_GPT3_5_TURBO_CI_FR: "2024-02-01"
  AZURE_DEPLOYMENT_TXT_EMBEDDING_ADA_CI_FR: "text-embedding-ada-002"
  AZURE_API_BASE_TXT_EMBEDDING_ADA_CI_FR: "https://devtribe-ci-france.openai.azure.com/"
  AZURE_API_VERSION_TXT_EMBEDDING_ADA_CI_FR: "2023-05-15"
  AZURE_API_KEY_CI_FR: ${{ secrets.AZURE_OPENAI_API_KEY_DEVTRIBE_CI_FRANCE }}

    # Azure Oauth
  AZURE_CLIENT_ID: ${{ secrets.DEVTRIBE_CI_OAUTH_CLIENT_ID }}
#  AZURE_OBJECT_ID: ${{ secrets.AZURE_OBJECT_ID }} # this was not added to the 1pass list so skipping temporarily
  AZURE_TENANT_ID: ${{ secrets.DEVTRIBE_CI_OAUTH_TENANT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.DEVTRIBE_CI_OAUTH_CLIENT_SECRET }}

  # AWS Bedrock regions, for multi-LLM-routing testing
  AWS_REGION_NAME_1: us-east-1
  AWS_REGION_NAME_2: eu-central-1

permissions:
  id-token: write
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint_action:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout git repository 🕝
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/lint-action
        with:
          workflow_path: .github/workflows/providers-e2e-tests.yml

  job_setup:
    needs: lint_action
    runs-on: ubuntu-24.04
    outputs:
      COMMAND_GENERATOR: ${{ env.COMMAND_GENERATOR }}
      COMMAND_GENERATOR_MATRIX: ${{ env.COMMAND_GENERATOR_MATRIX }}
    steps:
      - name: Set command-generator
        run: |
          echo "COMMAND_GENERATOR=${{ env.COMMAND_GENERATOR }}" >> "$GITHUB_OUTPUT"
          echo "COMMAND_GENERATOR_MATRIX=${{ env.COMMAND_GENERATOR_MATRIX }}" >> "$GITHUB_OUTPUT"
          echo "${{ fromJson(env.COMMAND_GENERATOR_MATRIX)[env.COMMAND_GENERATOR] }}"

  check_changes_impacting_providers:
    runs-on: ubuntu-24.04
    if: ${{ github.event_name == 'pull_request' }}
    outputs:
      litellm_upgraded: ${{ steps.check_litellm_upgrade.outcome }}
      openai_upgraded: ${{ steps.check_openai_upgrade.outcome }}
      provider_code_changed: ${{ steps.filter.outputs.providers }}
    steps:
      - name: Checkout git repository 🕝
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - id: filter
        name: Check for changes in `rasa/shared/providers` folder
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36  # v3.0.2
        with:
          filters: .github/change_filters.yml
      - name: Check upgrades to LiteLLM dependency
        continue-on-error: true
        if: ${{ steps.filter.outputs.lock_file == 'true' }}
        id: check_litellm_upgrade
        run: git diff ${{ github.sha }}:pyproject.toml origin/${{ github.base_ref }}:pyproject.toml | grep -e '-litellm\|+litellm2'
      - name: Check upgrades to OpenAI dependency
        continue-on-error: true
        id: check_openai_upgrade
        if: ${{ always() && steps.filter.outputs.lock_file == 'true' }}
        run: git diff ${{ github.sha }}:pyproject.toml origin/${{ github.base_ref }}:pyproject.toml | grep -e '-openai\|+openai'

  e2e_test:
    name: Run e2e Test
    needs: [job_setup, check_changes_impacting_providers]
    if: ${{ always() && (github.event_name == 'schedule' || inputs.provider == 'all' || (needs.check_changes_impacting_providers.outputs.litellm_upgraded == 'success' || needs.check_changes_impacting_providers.outputs.openai_upgraded == 'success' || needs.check_changes_impacting_providers.outputs.provider_code_changed == 'true' )) }}
    runs-on: ${{ contains(matrix.provider, 'self-hosted') && 'ubuntu-24.04-16core' || 'ubuntu-24.04' }}
    services:
      redis:
        image: redis:6
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    strategy:
      fail-fast: false
      matrix:
        provider: [
            openai,
            azure,
            azure-oauth,
            bedrock,
            gemini,
            huggingface,
            huggingface_local,
            anthropic,
            # cohere, TODO: Enable after ENG-1411 is unblocked
            mistral,
            together_ai,
            groq,
            # voyage, TODO: Enable after ENG-1415 is unblocked
            ollama,
            self-hosted-vllm,
            self-hosted-llama-cpp,
            azure-multiple-deployments-with-simple-shuffle-routing,
            azure-multiple-deployments-with-least-busy-routing,
            azure-multiple-deployments-with-usage-based-routing,
            # azure-multiple-deployments-with-usage-based-routing-v2, TODO: Enable after ENG-1651 is resolved
            azure-multiple-deployments-with-latency-based-routing,
            azure-multiple-deployments-with-cost-based-routing,
            gemini-multiple-deployments-with-routing,
            # huggingface-multiple-deployments-with-routing, Disabled as HF inference provider monthly credits exceeded
            bedrock-multiple-deployments-with-routing,
            sagemaker_chat-multiple-deployments-with-routing,
            litellm-proxy-multiple-deployments-with-routing,
            openai-with-custom-prompt-for-CompactLLMCommandGenerator,
            openai-with-custom-prompt-for-CustomLLMCommandGenerator
          ] # TODO: Enable testing all the providers
        train-and-test: ${{ fromJson(needs.job_setup.outputs.COMMAND_GENERATOR_MATRIX)[needs.job_setup.outputs.COMMAND_GENERATOR] }}
    steps:
      - name: Checkout git repository 🕝
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: rasa-private

      # Skip job if required config file for provider does not exist
      - name: Job to be skipped
        run: |
          if [[ -e rasa-private/data/test_config/providers/${{ matrix.provider }}/${{ matrix.train-and-test }}-config.yml ]]; then
            echo "JOB_TO_BE_SKIPPED=false" >> "$GITHUB_ENV"
          else
              echo "JOB_TO_BE_SKIPPED=true" >> "$GITHUB_ENV"
          fi

      - name: Set provider API key
        if: ${{ env.JOB_TO_BE_SKIPPED == 'false' }}
        continue-on-error: true
        run: |
          : Set provider API key
          echo "${{ fromJson(env.API_KEY_NAMES)[matrix.provider] }}=${{ secrets[fromJson(env.API_KEY_NAMES)[matrix.provider]] }}" >> "$GITHUB_ENV"

      - name: E2E test
        if: ${{ env.JOB_TO_BE_SKIPPED == 'false' }}
        uses: ./rasa-private/.github/actions/providers-tests
        env:
          OTEL_SERVICE_NAME: e2e-tests-${{ matrix.provider }}
        with:
          provider: ${{ matrix.provider }}
          train-and-test: ${{ matrix.train-and-test }}
          data-repo: ${{ inputs.data-repo || 'rasa-calm-demo' }}
          data-repo-branch: ${{ inputs.data-repo-branch || 'main' }}
          single-step-tests: ${{ inputs.single-step-e2e-test-with-assertions || 'e2e_tests_with_assertions/passing/happy_path/user_checks_balance.yml' }} # TODO: Use test that invokes enterprise-search, when flakiness is resolved
          multi-step-tests: ${{ inputs.multi-step-e2e-test-with-assertions || 'e2e_tests_with_assertions/passing/happy_path/user_checks_balance.yml' }}
          compact-tests: ${{ inputs.compact-e2e-test-with-assertions || 'e2e_tests_with_assertions/passing/happy_path/user_checks_balance.yml' }}
          search-ready-tests: ${{ inputs.search-ready-e2e-test-with-assertions || 'e2e_tests_with_assertions/knowledge_relevancy_check/chitchat_during_flow.yml' }}

  e2e_test_on_single_provider:
    name: Run e2e Test
    needs: job_setup
    if: ${{ inputs.provider != 'all' && github.event_name == 'workflow_dispatch' }}
    runs-on: ${{ contains(inputs.provider, 'self-hosted') && 'ubuntu-24.04-16core' || 'ubuntu-24.04' }}
    services:
      redis:
        image: redis:6
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    strategy:
      fail-fast: false
      matrix:
        train-and-test: ${{ fromJson(needs.job_setup.outputs.COMMAND_GENERATOR_MATRIX)[needs.job_setup.outputs.COMMAND_GENERATOR] }}

    steps:
      - name: Checkout git repository 🕝
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: rasa-private

      # Skip job if required config file for provider does not exist
      - name: Job to be skipped
        env:
          PROVIDER: ${{ inputs.provider }}
        run: |
          if [[ -e rasa-private/data/test_config/providers/${{ env.PROVIDER }}/${{ matrix.train-and-test }}-config.yml ]]; then
            echo "JOB_TO_BE_SKIPPED=false" >> "$GITHUB_ENV"
          else
              echo "JOB_TO_BE_SKIPPED=true" >> "$GITHUB_ENV"
          fi

      - name: Set provider API key
        if: ${{ env.JOB_TO_BE_SKIPPED == 'false' }}
        continue-on-error: true
        env:
          PROVIDER: ${{ inputs.PROVIDER }}
        run: |
          : Set provider API key
          echo "${{ fromJson(env.API_KEY_NAMES)[env.PROVIDER] }}=${{ secrets[fromJson(env.API_KEY_NAMES)[env.PROVIDER]] }}" >> "$GITHUB_ENV"

      - name: E2E test on single provider
        if: ${{ env.JOB_TO_BE_SKIPPED == 'false' }}
        uses: ./rasa-private/.github/actions/providers-tests
        env:
          OTEL_SERVICE_NAME: e2e-tests-${{ inputs.provider }}
        with:
          provider: ${{ inputs.provider }}
          train-and-test: ${{ matrix.train-and-test }}
          data-repo: ${{ inputs.data-repo || 'rasa-calm-demo' }}
          data-repo-branch: ${{ inputs.data-repo-branch || 'main' }}
          single-step-tests: ${{ inputs.single-step-e2e-test-with-assertions }}
          multi-step-tests: ${{ inputs.multi-step-e2e-test-with-assertions }}
          compact-tests: ${{ inputs.compact-e2e-test-with-assertions }}
          search-ready-tests: ${{ inputs.search-ready-e2e-test-with-assertions }}
