name: E2E Test on Rasa-Calm-Demo with supported providers and specified config

on:
  workflow_dispatch:
    inputs:
      provider:
        # In-case provider only has supported model for one
        # (for e.g. only chat-completion), then default OpenAI
        # would be used for the other
        description: "LLM chat-completion and Embeddings model provider."
        type: choice
        required: true
        default: openai

        options:
          - openai
          - azure
          - bedrock
          - gemini
          - huggingface
          - huggingface_local
          - anthropic
          # - cohere TODO: Enable after ENG-1411 is unblocked
          # - mistral TODO: Enable after ENG-1412 is unblocked
          - together_ai
          - groq
          # - voyage TODO: Enable after ENG-1415 is unblocked
          - ollama
          - self-hosted-vllm
          - self-hosted-llama-cpp
          - azure-multiple-deployments-with-simple-shuffle-routing
          - azure-multiple-deployments-with-least-busy-routing
          - azure-multiple-deployments-with-usage-based-routing
          # - azure-multiple-deployments-with-usage-based-routing-v2 TODO: Enable after ENG-1651 is resolved
          - azure-multiple-deployments-with-latency-based-routing
          - azure-multiple-deployments-with-cost-based-routing
          - gemini-multiple-deployments-with-routing
          - huggingface-multiple-deployments-with-routing
          - bedrock-multiple-deployments-with-routing
          - litellm-proxy-multiple-deployments-with-routing

      llm-model-name:
        description: "Model from LLM provider (for `azure` provider, use `llm-deployment` input instead). Default: model from `data/test_config/providers/<provider>/*endpoint|config*.yml`"
        type: string
        required: false

      embeddings-model-name:
        description: "Embeddings model from provider (for `azure` provider, fill `embeddings-deployment` input instead). Default: model from `data/test_config/providers/<provider>/*endpoint|config*.yml`"
        type: string
        required: false

      llm-deployment:
        description: "Azure LLM model deployment. Default: deployment in `data/test_config/providers/<*azure*>/*endpoint|config*.yml`"
        type: string
        required: false

      embeddings-deployment:
        description: "Azure Embeddings model deployment. Default: deployment in `data/test_config/providers/<*azure*>/*endpoint|config*.yml`"
        type: string
        required: false

      llm-api-version:
        description: "Azure LLM API version. Default: API version in `data/test_config/providers/<*azure*>/*endpoint|config*.yml`"
        type: string
        required: false

      embeddings-api-version:
        description: "Azure Embeddings API version. Default: API version in `data/test_config/providers/<*azure*>/*endpoint|config*.yml`"
        type: string
        required: false

      llm-api-base:
        description: "Azure or Hugging Face Inference Endpoint LLM API base. Default: API base in `data/test_config/providers/<*azure|huggingface*>/*endpoint|config*.yml`"
        type: string
        required: false

      embeddings-api-base:
        description: "Azure or Hugging Face Inference Endpoint Embeddings API base. Default: API base in `data/test_config/providers/<*azure|huggingface*>/*endpoint|config*.yml`"
        type: string
        required: false

      rasa-calm-demo-branch:
        description: "Branch to checkout for `rasa-calm-demo`"
        type: string
        required: true
        default: "main"

env:
  DEFAULT_PYTHON_VERSION: "3.11"
  RASA_PRO_BETA_E2E_ASSERTIONS: true
  RASA_PRO_BETA_STUB_CUSTOM_ACTION: true
  LOG_LEVEL_LLM: DEBUG
  ENDPOINTS_FILE_NAME: endpoints
  REDIS_HOST: localhost
  REDIS_PORT: 6379
  RASA_TELEMETRY_DEBUG: true
  OTEL_EXPORTER: otlp_grpc
  OTEL_ENDPOINT: http:/0.0.0.0:4317
  HONEYCOMB_API_KEY: ${{ secrets.HONEYCOMB_API_KEY }}
  API_KEY_NAMES: '{"azure": "AZURE_API_KEY", "gemini": "GEMINI_API_KEY", "huggingface": "HUGGINGFACE_API_KEY", "anthropic": "ANTHROPIC_API_KEY", "together_ai": "TOGETHERAI_API_KEY", "groq": "GROQ_API_KEY", "openai": "OPENAI_API_KEY", "mistral": "MISTRAL_API_KEY", "cohere": "COHERE_API_KEY", "voyage": "VOYAGE_API_KEY"}'
  RASA_PRO_LICENSE: ${{ secrets.RASA_PRO_LICENSE }}
  DUCKLING_URL: http://localhost:8000
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  RASA_CALM_DEMO_READ_TOKEN: ${{ secrets.RASA_CALM_DEMO_READ }}

  # Providers' required environment variables (API key values also stored in 1Password):

  # OpenAI
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

   # Hugging Face
  HUGGINGFACE_API_KEY: ${{ secrets.HUGGINGFACE_API_KEY }}

  # AWS Bedrock
  AWS_REGION_NAME: us-east-1

  # Gemini - Google AI Studio
  GEMINI_API_KEY_1: ${{ secrets.GEMINI_API_KEY }}
  GEMINI_API_KEY_2: ${{ secrets.GEMINI_ALTERNATE_API_KEY }} # API key for different deployment, to test multi-LLM-routing

  # Ollama
  OLLAMA_API_BASE: http://localhost:11434

  # Azure multi-deployments (for multi-LLM routing):
  LLM_API_HEALTH_CHECK: True

  # Training deployment
  AZURE_DEPLOYMENT_GPT4o: "test-gpt-4o"
  AZURE_API_BASE_GPT4o: "https://engine-testing.openai.azure.com/"
  AZURE_API_VERSION_GPT4o: "2024-02-01"
  AZURE_DEPLOYMENT_TXT_EMBEDDING_3_LARGE: "test-text-embedding-3-large"
  AZURE_API_BASE_TXT_EMBEDDING_3_LARGE: "https://engine-testing.openai.azure.com/"
  AZURE_API_VERSION_TXT_EMBEDDING_3_LARGE: "2023-05-15"
  AZURE_API_KEY_TRAINING: ${{ secrets.AZURE_OPENAI_API_KEY_ENGINE_TESTING }}

    # Deployment 1
  AZURE_DEPLOYMENT_GPT4o_CA: "test-gpt-4o"
  AZURE_API_BASE_GPT4o_CA: "https://devtribe-testing-canada-east.openai.azure.com/"
  AZURE_API_VERSION_GPT4o_CA: "2024-02-01"
  AZURE_DEPLOYMENT_TXT_EMBEDDING_3_LARGE_CA: "test-text-embedding-3-large"
  AZURE_API_BASE_TXT_EMBEDDING_3_LARGE_CA: "https://devtribe-testing-canada-east.openai.azure.com"
  AZURE_API_VERSION_TXT_EMBEDDING_3_LARGE_CA: "2023-05-15"
  AZURE_API_KEY_CA: ${{ secrets.AZURE_OPENAI_API_KEY_DEVTRIBE_TESTING_CANADA_EAST }}

    # Deployment 2
  AZURE_DEPLOYMENT_GPT4o_FR: "test-gpt-4o"
  AZURE_API_BASE_GPT4o_FR: "https://devtribe-testing.openai.azure.com/"
  AZURE_API_VERSION_GPT4o_FR: "2024-02-01"
  AZURE_DEPLOYMENT_TXT_EMBEDDING_3_LARGE_FR: "test-text-embedding-3-large"
  AZURE_API_BASE_TXT_EMBEDDING_3_LARGE_FR: "https://devtribe-testing.openai.azure.com/"
  AZURE_API_VERSION_TXT_EMBEDDING_3_LARGE_FR: "2023-05-15"
  AZURE_API_KEY_FR: ${{ secrets.AZURE_OPENAI_API_KEY_DEVTRIBE_TESTING }}

  # AWS Bedrock regions, for multi-LLM-routing testing
  AWS_REGION_NAME_1: us-east-1
  AWS_REGION_NAME_2: eu-central-1

permissions:
  id-token: write
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint_action:
    runs-on: warp-ubuntu-latest-x64-2x
    steps:
      - name: Checkout git repository 🕝
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/lint-action
        with:
          workflow_path: .github/workflows/providers-e2e-tests-with-custom-model-or-config.yml

  e2e_test_with_user_provided_config_and_endpoint_files:
    name: Run e2e Test
    needs: lint_action
    runs-on: ${{ inputs.provider == 'self-hosted' && 'warp-ubuntu-latest-x64-8x' || 'warp-ubuntu-latest-x64-2x' }}
    services:
      redis:
        image: redis:6
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    strategy:
      fail-fast: false
      matrix:
        train-and-test: ["singlestep", "multistep"]

    steps:
      - name: Checkout git repository 🕝
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set provider API key
        continue-on-error: true
        run: |
          : Set provider API key
          echo "${{ fromJson(env.API_KEY_NAMES)[inputs.provider] }}=${{ secrets[fromJson(env.API_KEY_NAMES)[inputs.provider]] }}" >> "$GITHUB_ENV"

      - name: Update endpoint and config files to use specified model config
        if: ${{ !(inputs.llm-model-name == '' && inputs.embeddings-model-name == '' && inputs.llm-deployment == '' && inputs.embeddings-deployment == '' && inputs.llm-api-version == '' && inputs.embeddings-api-version == '' && inputs.llm-api-base == '' && inputs.embeddings-api-base == '') }}
        working-directory: data/test_config/providers
        env:
            PROVIDER: ${{ inputs.provider }}
            LLM_MODEL_NAME: ${{ inputs.llm-model-name }}
            EMBEDDINGS_MODEL_NAME: ${{ inputs.embeddings-model-name }}
            LLM_DEPLOYMENT: ${{ inputs.llm-deployment }}
            EMBEDDINGS_DEPLOYMENT: ${{ inputs.embeddings-deployment }}
            LLM_API_VERSION: ${{ inputs.llm-api-version }}
            EMBEDDINGS_API_VERSION: ${{ inputs.embeddings-api-version }}
            LLM_API_BASE: ${{ inputs.llm-api-base }}
            EMBEDDINGS_API_BASE: ${{ inputs.embeddings-api-base }}
        run: ./update-model-name-in-config-and-endpoint-files.py

      - name: E2E test with user provided config and endpoint files
        uses: ./.github/actions/providers-tests
        env:
            LLM_MODEL_NAME: ${{ inputs.llm-model-name }}
        with:
          provider: ${{ inputs.provider }}
          train-and-test: ${{ matrix.train-and-test }}
          rasa-calm-demo-branch: ${{ inputs.rasa-calm-demo-branch }}
          single-step-tests: e2e_tests/tests_for_github_workflows/user_checks_balance.yml
          multi-step-tests: e2e_tests/tests_for_github_workflows/user_checks_balance.yml
          llm-judge-model: gpt-4.1-mini
