name: Run Voice Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - '[0-9]+.[0-9]+.x'
    paths: [ rasa/core/channels/voice_ready/**,
      rasa/core/channels/voice_stream/**,
      rasa/core/channels/channel.py,
      rasa/core/channels/socketio.py,
      rasa/core/channels/studio_chat.py,]
  pull_request:
permissions:
  id-token: write
  contents: read
  pull-requests: read


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-voice-code-changes:
    runs-on: warp-ubuntu-latest-x64-2x
    outputs:
      voice-files: ${{ steps.filter.outputs.voice-files }}
    steps:
      - name: Checkout git repository 🕝
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - id: filter
        name: Check for changes in voice related files
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36  # v3.0.2
        with:
          filters: .github/change_filters.yml
      - name: Debug voice-files output
        run: |
          echo "voice-files: ${{  steps.filter.outputs.voice-files }}"


  voice_integration_tests:
    name: Run Voice Integration Tests
    runs-on: warp-ubuntu-latest-x64-4x
    needs: [check-voice-code-changes]
    if: needs.check-voice-code-changes.outputs.voice-files == 'true'
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Debug voice-files output
        run: |
          echo "voice-files: ${{ needs.check-voice-code-changes.outputs.voice-files }}"
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Free up disk-space
        uses: RasaHQ/rasa-private/.github/actions/free-disk-space@fe77d93db58f0412e2162fdaa34e2ed596f8536b

      - name: Prepare the job for integration tests
        uses: ./.github/actions/test-prerequisites
        with:
          PYTHON_VERSION:  ${{ matrix.python-version }}
          POETRY_CACHE_VERSION: ${{ secrets.POETRY_CACHE_VERSION }}

      - name: Install Dependencies (Linux) 📦
        # Poetry intermittently fails to install dependency if it is not PEP 517 compliant
        # This is a workaround for that issue
        run: |
          sudo apt-get -y install libpq-dev
          make install-full | tee .output
          if grep 'The lock file is not up to date' .output; then exit 1; fi
          make prepare-tests-ubuntu

      - name: Install additional dependencies for voice tests
        run: |
          poetry run python -m pip install azure-cognitiveservices-speech

      - name: Test Code 🔍 (multi-process)
        env:
          JOBS: 2
          PYTHONUTF8: 1
          RASA_PRO_LICENSE: ${{ secrets.RASA_PRO_LICENSE }}
          CARTESIA_API_KEY: ${{ secrets.CARTESIA_API_KEY }}
          DEEPGRAM_API_KEY: ${{ secrets.DEEPGRAM_API_KEY }}
          AZURE_SPEECH_API_KEY: ${{ secrets.AZURE_SPEECH_API_KEY_TTS }}
          AZURE_OPENAI_ENDPOINT: "https://eastus.api.cognitive.microsoft.com/"
          AZURE_SPEECH_REGION: "eastus"
        run: |
          make test-voice-integration
        shell: bash # bash shell is a way to make code run for both Linux and Windows

      - name: Prepare test results
        if: always()
        run: mv integration-test-results.xml ${{ github.workspace }}/integration-results-voice-ready-and-stream-results-python-${{ matrix.python-version }}.xml

      - name: Save Test Results
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: integration-results-voice-ready-and-stream-results-python-${{ matrix.python-version }}
          path: |
            ${{ github.workspace }}/integration-results-voice-ready-and-stream-results-python-${{ matrix.python-version }}.xml


  send_slack_notification_on_failure:
    name: Notify Slack
    runs-on: warp-ubuntu-latest-x64-2x
    needs: [ check-voice-code-changes, voice_integration_tests ]

    steps:
      - name: Notify Slack of failure ⛔️
        # send notification if 'voice_integration_tests' is skipped (previous needed job failed) or failed
        if: ${{ needs.check-voice-code-changes.outputs.voice-files == 'true' && needs.voice_integration_tests.result != 'success' }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_RELEASE_ASSISTANT_ATOM_ALERTS_WEBHOOK }}
        uses: Ilshidur/action-slack@689ad44a9c9092315abd286d0e3a9a74d31ab78a
        with:
          args: "⛔️ *Voice Integration Tests on Main* failed 😱! Please check out GitHub Actions: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
