name: Scheduled CI Tests

on:
  schedule:
    # Runs at 3AM Monday to Friday
    - cron: "0 3 * * 1-5"
  workflow_dispatch:


permissions:
  contents: read
  id-token: write
  checks: write
  issues: read
  pull-requests: write

# Reusing continous-integration.yml workflow
# Inputs:
# - python-versions: Python versions to run the tests on
# - run_code_quality: Whether to run the Code Quality checks
jobs:
  scheduled-tests:
    if: false
     # Temporarily disabling scheduled tests until we resolve some test failures with python versions 3.11, 3.12, 3.13
    uses: ./.github/workflows/continous-integration.yml
    with:
      python-versions: '["3.11","3.12","3.13"]'
      # We don't want to run the code quality checks on scheduled runs
      run_code_quality: 'false'
      # We only want to run the CI checks for unit tests that need to be run against multiple python versions
      full_ci_mode: 'true'
      pr-author: ${{ github.event.pull_request.user.login }}
      pr-is-draft: ${{ github.event.pull_request.draft }}
    secrets: inherit

  rasa-init-sanity-check:
    runs-on: warp-ubuntu-latest-x64-2x
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
        template:
          - default
          - tutorial
          - basic
          - finance
          - telco
        install-group:
          - default
          - nlu
          - channels
          - full
        install-method:
          - poetry
          - pip
          - uv
        exclude:
          - python-version: "3.9"
            template: tutorial
          - python-version: "3.9"
            template: basic
          - python-version: "3.9"
            template: finance
          - python-version: "3.9"
            template: telco
          - python-version: "3.9"
            install-method: pip
          - python-version: "3.9"
            install-method: uv
          - python-version: "3.13"
            install-group: nlu
          - python-version: "3.13"
            install-group: full
    name: rasa init Py${{ matrix.python-version }} ${{ matrix.install-group }}-group (with ${{ matrix.install-method }} install) ${{ matrix.template }}-template
    env:
      RASA_INIT_TEST_DIRECTORY: test-rasa-init
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Python ${{ matrix.python-version }} and install rasa-pro (via ${{ matrix.install-method }}) with default installation
        if: ${{ matrix.python-version != '3.9' && matrix.install-group == 'default' }}
        uses: ./.github/actions/setup-python-env
        with:
          PYTHON_VERSION: ${{ matrix.python-version }}
          RASA_DEFAULT_INSTALLATION_ONLY: "true"
          DEPENDENCIES_AND_PACKAGE_MANAGEMENT_TOOL: ${{ matrix.install-method }}

      - name: Setup Python ${{ matrix.python-version }} and install rasa-pro (via ${{ matrix.install-method }}) with ${{ matrix.install-group }} group
        if: ${{ matrix.python-version != '3.9' && matrix.install-group != 'default'  }}
        uses: ./.github/actions/setup-python-env
        with:
          PYTHON_VERSION: ${{ matrix.python-version }}
          OPTIONAL_GROUP_TO_INSTALL: ${{ matrix.install-group }}
          RASA_DEFAULT_INSTALLATION_ONLY: "false"
          DEPENDENCIES_AND_PACKAGE_MANAGEMENT_TOOL: ${{ matrix.install-method }}

      - name: Set up Python 3.9
        if: ${{ matrix.python-version == '3.9' }}
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Read Poetry Version 🔢
        if: ${{ matrix.python-version == '3.9' }}
        run: |
          echo "POETRY_VERSION=$(scripts/poetry-version.sh)" >> "${GITHUB_ENV}"

      - name: Install Poetry ${{ env.POETRY_VERSION }}
        if: ${{ matrix.python-version == '3.9' }}
        uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a # v1.4.1
        with:
          version: ${{ env.POETRY_VERSION }}
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Check error warning on Rasa install if using Python 3.9
        if: ${{ matrix.python-version == '3.9' }}
        run: |
          make install > error-log 2>&1 || true
          echo 'Error log:'
          cat error-log
          echo 'Search log for error, on Rasa installation in Python 3.9 environment:'
          grep -E 'Current Python version \(3.9.[0-9]+\) is not allowed by the project \(>=3.10.0,<3.14\)' error-log

      - name: Make empty directory for `rasa init`
        run: mkdir "${RASA_INIT_TEST_DIRECTORY}"

      - name: Sanity check of `rasa init`
        if: ${{ matrix.python-version != '3.9' }}
        working-directory: ${{ env.RASA_INIT_TEST_DIRECTORY }}
        env:
          LLM_API_HEALTH_CHECK: true
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          RASA_PRO_LICENSE: ${{ secrets.RASA_PRO_LICENSE }}
          TEMPLATE: ${{ matrix.template }}
        run: rasa init --template "${TEMPLATE}" --no-prompt --debug
  send_slack_notification_on_failure:
    name: Notify Slack
    runs-on: warp-ubuntu-latest-x64-2x
    if: always()
    needs:
      - rasa-init-sanity-check

    steps:
      - name: Notify Slack of failure ⛔️
        # send notification if any of the steps above is skipped (previous needed job failed) or failed or cancelled
        if: ${{ needs.rasa-init-sanity-check.result != 'success' }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_RELEASE_ASSISTANT_ATOM_ALERTS_WEBHOOK }}
        uses: Ilshidur/action-slack@689ad44a9c9092315abd286d0e3a9a74d31ab78a
        with:
          args: "⛔️ *Scheduled CI Run on Main* failed 😱! Please check out GitHub Actions: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

