name: Weekly Scheduled Dev releases
on:
  schedule:
    - cron: '0 9 * * 1' # Every Monday at 9:00 UTC
  workflow_dispatch:


env:
    DEFAULT_PYTHON_VERSION: "3.11" # Default Python version for the workflow

jobs:
  run_script_and_tag_weekly_dev_release:
    name: Run release script and tag a new dev release
    runs-on: ubuntu-24.04
    outputs:
      tag_name: ${{ steps.set_tagname.outputs.tag_name }}

    steps:
      - name: Checkout git repository 🕝
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          ref: main # update this to branch to test

      - name: Setup Python Environment
        uses: ./.github/actions/setup-python-env
        with:
          PYTHON_VERSION: ${{ env.DEFAULT_PYTHON_VERSION }}

      - name: Compose tag name
        id: set_tagname
        run: |
          DATE=$(date +'%Y%m%d')
          echo "Trying to find the latest rasa version..."
          LATEST_RASA_MINOR=$(python -c "import sys; import os; sys.path.append('${{ github.workspace }}/rasa'); from rasa.version import __version__; print(__version__)")
          
           # Find latest rasa version on branch and split dev tag if available
          if [[ "${LATEST_RASA_MINOR}" != *"dev"* && "${LATEST_RASA_MINOR}" != *"a"* ]]; then         
              echo "Current RASA version: ${LATEST_RASA_MINOR}"
          
              ## Increment the minor version for the weekly dev release and make the patch version 0, e.g. 3.12.17 to 3.13.0
              LATEST_WEEKLY_VERSION=$(python -c "v='${LATEST_RASA_MINOR}'; parts=v.split('.'); parts[1]=str(int(parts[1])+1); parts[2]='0'; print('.'.join(parts))")
          else
              echo "Current RASA version is already a dev or alpha version, skipping version increment."
              LATEST_RASA_MINOR=$(python -c "import sys; import os; sys.path.append('${{ github.workspace }}/rasa'); from rasa.version import __version__; import re; print(re.sub(r'(\.dev.*$|a\d+$)', '', __version__))")
              echo "Current RASA version: ${LATEST_RASA_MINOR}"
              LATEST_WEEKLY_VERSION="${LATEST_RASA_MINOR}"
            fi
          
          echo "Composing weekly build tag name..."
          GH_TAG=${LATEST_WEEKLY_VERSION}.dev${DATE}
          echo "New weekly dev release version: ${GH_TAG}"
          echo "tag_name=${GH_TAG}" >> $GITHUB_OUTPUT

      - name: Check if tag already exists
        id: check_tag
        run: |
          if git rev-parse "${{ steps.set_tagname.outputs.tag_name }}" >/dev/null 2>&1; then
            echo "Tag ${{ steps.set_tagname.outputs.tag_name }} already exists. Exiting."
            exit 0
          else
            echo "Tag ${{ steps.set_tagname.outputs.tag_name }} does not exist. Proceeding with tagging."
          fi

      - name: Run release script
        id: run_release_script
        run: |
          echo "Running release script..."
          source .venv/bin/activate
          python scripts/release.py prepare --automated-release --next_version "${{ steps.set_tagname.outputs.tag_name }}"

      - name: Create Pull Request
        id: create_pr
        if: steps.run_release_script.outcome == 'success'
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c
        with:
          token: ${{ secrets.RASABOT_GITHUB_TOKEN }}
          signoff: false
          branch: prepare-release-pre-${{ steps.set_tagname.outputs.tag_name }}
          delete-branch: true
          title: "Prepare release of version ${{ steps.set_tagname.outputs.tag_name }}"
          draft: false
          base: main  # or the appropriate branch name

      - name: ✅ Approve the pull request
        if: steps.create_pr.outcome == 'success'
        run: gh pr review -a ${{ steps.create_pr.outputs.pull-request-url }}
        env:
          # the approver needs to be different than the creator of the PR
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🔀 Enable pull request auto-merge
        if: steps.create_pr.outcome == 'success'
        run: gh pr merge --merge --auto ${{ steps.create_pr.outputs.pull-request-url }}
        env:
          GH_TOKEN: ${{ secrets.RASABOT_GITHUB_TOKEN }}
