# Name of this GitHub Actions workflow.
name: Semgrep

on:
  # Scan mainline branches and report all findings:
  push:
    branches:
      - main
  # Scan changed files in PRs (diff-aware scanning):
  pull_request:

jobs:
  semgrep:
    # User-definable name of this GitHub Actions job:
    name: Semgrep Workflow Security Scan
    # If you are self-hosting, change the following `runs-on` value:
    runs-on: warp-ubuntu-latest-x64-2x

    container:
      # A Docker image with Semgrep installed. Do not change this.
      image: returntocorp/semgrep@sha256:37736e4992c539f760e36e14d48924bd9fa70d0abbde39a6d86d93f66a1affd4

    # To skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')

    steps:
      # Fetch project source with GitHub Actions Checkout.
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      # Run the "semgrep ci" command on the command line of the docker image.
      - run: semgrep ci
        env:
          # Add the rules that Semgrep uses by setting the SEMGREP_RULES environment variable.
          SEMGREP_RULES: p/github-actions

      - name: Notify Slack on failure (main branch) ⛔️
        if: failure() && github.ref == 'refs/heads/main'
        uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d #v 2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          # Send notification to #prodeng-internal slack channel
          payload: |
            channel: "C36SS4N8M"
            text: "⛔️ *Semgrep scan failed on main branch! Please check out GitHub Actions: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
