name: Verify patch releases are not model breaking
run-name: Verify backwards compatibility between rasa-pro "${{ inputs.rasa_pro_new_version || github.ref_name }}" and ${{ inputs.rasa_pro_old_version || 'oldest patch version' }}

on:
  workflow_dispatch:
    inputs:
      rasa_pro_new_version:
        description: Newer patch version of rasa-pro. Latest current version by default.
        type: string
        required: false
      rasa_pro_old_version:
        description: Older patch version of rasa-pro, to check backwards-compatibility of newer version against. Oldest patch version by default.
        type: string
        required: false
      command_generator:
        description: Command generator to use for model training and inference.
        type: choice
        required: true
        default: compact
        options:
          - compact
          - singlestep
          - multistep
      rasa-calm-demo-branch:
          description: Branch (or tag) to checkout for rasa-calm-demo git repo
          type: string
          required: true
          default: main

  pull_request:
    types: opened
    branches:
      - '[0-9]+.[0-9]+.x'

  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  DEFAULT_PYTHON_VERSION: "3.11"
  RASA_PRO_LICENSE: ${{ secrets.RASA_PRO_LICENSE }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  RASA_PRO_BETA_E2E_ASSERTIONS: true
  RASA_PRO_BETA_PREDICATES_IN_RESPONSE_CONDITIONS: true
  RASA_CALM_DEMO_READ_TOKEN: ${{ secrets.RASA_CALM_DEMO_READ }}
  LLM_API_HEALTH_CHECK: true

jobs:
  train_model_on_older_patch_version:
    runs-on: ubuntu-24.04
    outputs:
      MODEL_NAME: model-trained-on-rasa-pro-${{ steps.install-rasa-pro-older-version.outputs.RASA_PRO_OLDER_VERSION }}
    steps:
      - name: Checkout rasa-private git repository 🕝
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: rasa-private
          fetch-depth: 0
      - name: Checkout rasa-calm-demo git repository 🕝
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: RasaHQ/rasa-calm-demo
          ref: ${{ inputs.rasa-calm-demo-branch || 'main' }}
          path: data-repo
          token: ${{ env.RASA_CALM_DEMO_READ_TOKEN }}
      - name: Set up Python 🐍
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b
        with:
            python-version: ${{ env.DEFAULT_PYTHON_VERSION }}
      - name: Install rasa-pro ${{ inputs.rasa_pro_old_version || 'oldest patch version' }}
        id: install-rasa-pro-older-version
        working-directory: rasa-private
        env:
          RASA_OLD_VERSION: ${{ inputs.rasa_pro_old_version }}
        run: |
          python"${DEFAULT_PYTHON_VERSION}" -m venv ./venv
          source ./venv/bin/activate
          if [[ -n "${RASA_OLD_VERSION}" ]]; then
            pip install rasa-pro=="${RASA_OLD_VERSION}"
            echo "RASA_PRO_OLDER_VERSION=${RASA_OLD_VERSION}" >> "${GITHUB_OUTPUT}"
          else
            latest_version="$(git describe --tags "$(git rev-list --tags --max-count=1)")"
            oldest_version="${latest_version%.*}.0"
            pip install rasa-pro=="${oldest_version}"
            echo "RASA_PRO_OLDER_VERSION=${oldest_version}" >> "${GITHUB_OUTPUT}"
          fi
          rasa --version
          echo "PATH=${PATH}" >> "${GITHUB_ENV}"
      - name: Run OTEL collector for Tracing and Metrics collection
        working-directory: rasa-private
        id: run-otel-collector
        run: |
          : Run OTEL collector for Tracing and Metrics collection
          make run-otel-collector
        shell: bash
      - name: Train model
        env:
          COMMAND_GENERATOR: ${{ inputs.command_generator || 'compact' }}
          RASA_PRO_OLDER_VERSION: ${{ steps.install-rasa-pro-older-version.outputs.RASA_PRO_OLDER_VERSION }}
        run: |
          rm -rf rasa-private/.rasa rasa-private/models \
            && rasa train \
            --config rasa-private/data/test_config/providers/openai/"${COMMAND_GENERATOR}"-config.yml \
            --endpoints rasa-private/data/test_config/providers/openai/endpoints.yml \
            --domain data-repo/domain \
            --data data-repo/data \
            --fixed-model-name model-trained-on-rasa-pro-"${RASA_PRO_OLDER_VERSION}" \
            --debug
      - name: Upload trained model as GHA artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: model-trained-on-rasa-pro-${{ steps.install-rasa-pro-older-version.outputs.RASA_PRO_OLDER_VERSION }}
          path: models/model-trained-on-rasa-pro-${{ steps.install-rasa-pro-older-version.outputs.RASA_PRO_OLDER_VERSION }}.tar.gz
          if-no-files-found: error

  e2e_test_with_newer_patch_version_without_retraining_model:
    needs: train_model_on_older_patch_version
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout rasa-private git repository 🕝
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: rasa-private
      - name: Checkout rasa-calm-demo git repository 🕝
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: RasaHQ/rasa-calm-demo
          ref: ${{ inputs.rasa-calm-demo-branch || 'main' }}
          path: data-repo
          token: ${{ env.RASA_CALM_DEMO_READ_TOKEN }}
      - name: Set up Python 🐍
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b
        with:
            python-version: ${{ env.DEFAULT_PYTHON_VERSION }}
      - name: Install rasa-pro ${{ inputs.rasa_pro_new_version || 'latest current patch version' }}
        env:
          RASA_PRO_NEW_VERSION: ${{ inputs.rasa_pro_new_version }}
        working-directory: rasa-private
        run: |
          python"${DEFAULT_PYTHON_VERSION}" -m venv ./venv
          source ./venv/bin/activate
          if [[ -n "${RASA_PRO_NEW_VERSION}" ]]; then
            pip install rasa-pro=="${RASA_PRO_NEW_VERSION}"
          else
            pip install .
          fi
          rasa --version
          echo "PATH=${PATH}" >> "${GITHUB_ENV}"
      - name: Download model
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
        with:
          name: ${{ needs.train_model_on_older_patch_version.outputs.MODEL_NAME }}
          path: models
      - name: Run OTEL collector for Tracing and Metrics collection
        working-directory: rasa-private
        id: run-otel-collector
        run: |
          : Run OTEL collector for Tracing and Metrics collection
          make run-otel-collector
        shell: bash
      - name: Run duckling server
        working-directory: data-repo
        run: |
          : Run duckling server
          make run-duckling
        shell: bash
      - name: Run action server
        id: run-action-server
        env:
          RASA_DUCKLING_HTTP_URL: ${{ secrets.DUCKLING_URL }}
          RASA_PRO_BETA_INTENTLESS: true
        working-directory: data-repo
        run: |
          : Run action server
          rasa run actions &
        shell: bash
      - name: Run E2E test
        env:
          MODEL_NAME: ${{ needs.train_model_on_older_patch_version.outputs.MODEL_NAME }}
        run: |
          if [[ ! -d tests ]]; then
            mkdir tests;
          fi
          rasa test e2e data-repo/e2e_tests_with_assertions/passing/happy_path/user_checks_balance.yml \
            --e2e-results \
            --debug \
            --endpoints rasa-private/data/test_config/providers/openai/endpoints.yml \
            --model models/"${MODEL_NAME}".tar.gz \
            --debug
      - name: Save E2E test results
        if: failure()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: E2E-test-result
          path: tests/e2e_results_failed.yml
